### PR TITLE
Add DB::DeleteRange for the default cf

### PR DESCRIPTION
**Pull request by hhkbp2**
Hi,

This PR adds `DB::DeleteRange` method for the default cf. PTAL.

### CODE REVIEW

**Comment by siying** [comment]
Why do you need that?

**Comment by siddontang** [comment]
We don't need to get the default handler outside like other API (E.g CompactRange) does.

**Comment by hhkbp2** [comment]
Ping @siying 
It's convenient to delete some range of the default CF without getting the default CF handle, by adding `DB::DeleteRange` in this PR.

**Comment by siying** [comment]
@hhkbp2 but getting the default CF handle is not a big deal, right? db.h is already too long. I hope we can avoid it to be even longer. It makes it harder for people to use.

**Pull request closed without merging**
