### PR TITLE
Remove deprecated option DBOptions::skip_log_error_on_recovery

### PR DESCRIPTION
**Pull request by akankshamahajan15**
Summary: In  RocksDB DBOptions::skip_log_error_on_recovery is marked as
"NOT SUPPORTED" for a long time, and setting this option does not have
any effect on the behavior of RocksDB library. Therefore, we are removing it
in the upcoming 7.0 release.

Test Plan: CircleCI

### CODE REVIEW

**Review by riversand963 — APPROVED** [review]
Thanks @akankshamahajan15 . 
Can you update PR description by removing unnecessary sections and update HISTORY.md?

**Review by mrambacher — APPROVED** [review]
LGTM.  Thanks!

**Review by ajkr — APPROVED** [review]
Not that you need three accepts, but the other two didn't seem to include Phabricator accept, so giving a third...

**Comment by akankshamahajan15** [comment]
Backward compatible test run https://app.circleci.com/pipelines/github/facebook/rocksdb/11132/workflows/90b9eecf-dfb3-4949-91e4-de3da7047100/jobs/281000

**Pull request closed without merging**
