### PR TITLE
Refactor sync_point to make implementation either customizable or replaceable

### PR DESCRIPTION
**Pull request by yuslepukhin**

### CODE REVIEW

**Comment by yuslepukhin** [comment]
@ajkr We are running the product with different instances using separate memory pools. Thus global facilities need to allocate memory within a neutral memory pool which would not be unloaded with any specific instance. SyncPoint being a test only facility  was never an issue until someone decided to debug a recent problem.

Thus the goal here is to switch to a specific memory pool before allocating/destroying the internals and forwarding calls that originate from the code that runs on behalf of a specific instance. impl works well because we only need to replace sync_point.cc file so we can do the above.  Memory pool switching takes place by overloading operator-> during forwarding.

We also inherit from Data to add some related data members and customize a couple of entry points while reusing the rest. This allows for greatest code reuse while achieving the purpose.

I am aware of the pattern that your are referring to. IMHO, this choice minimizes the amount of our internal code, simplifies code merges downstream and code re-use.

I realize that my view of things may be somewhat narrow. So, let me know. I can add the missing file to Makefile depending which way we'd like to go.

**Comment by ajkr** [comment]
Thanks for the explanation. Seems a good idea to use operator-> to select the memory pool. BTW, how do you figure out which DB instance (or memory pool) to use? We occasionally encounter a similar problem since we want to be able to access the Logger or Statistics instance from arbitrary places in the code. But we can't as they're DB instance-specific, so we end up passing them around in countless function calls.

**Comment by ajkr** [comment]
Oh, do you mind also updating the TARGETS file? Otherwise we'll get an error when building internally.

**Comment by yuslepukhin** [comment]
@ajkr Will update TARGETS.
Memory switching is based on a few main ideas.
1) db instances can be accessed only through specific APIs where memory pool id is set in the thread local storage for a given thread while it is accessing the instance. The instance stores the memory pool id.
2) Memory allocation is made via overriding new/delete (or their aligned versions). This functions can extract the thread local storage id and select the memory pool. The memory pool id is recorded at the start of the allocation for diagnostics. On delete we check if the invoking thread has the same id set as the allocation it is trying free.
3) Global facilities should live in a neutral memory pool which is designated before hand. So the memory pool id is switched back/forth while accessing them. The pattern is in threadpool_imlp, envirnoment and other examples. Global facilities  store the arena they are allocated in and provide a generic interface so a templated overload of operator -> can be applied.
4) Thread pool is a special case where the TP allocations are made in a neutral arena but the threads must remember the client arena id and switch to it when they start running the requested code.

The approach allows us to avoid any expensive code instrumentation which would be in order should we choose to pass memory pool around as an argument OR custom STL allocators.

Jemalloc supports separate arenas natively so the arena id is simply an integer. When the instance goes away we reset and purge the jemalloc arena to make sure there is no residual allocations.

**Comment by ajkr** [comment]
Thanks a lot for the explanation!

**Pull request closed without merging**
