### PR TITLE
Comment out unused variables

### PR DESCRIPTION
**Pull request by ajkr**
Submitting on behalf of another employee.

Test Plan: teammates helped to verify build succeeds on non-fbcode linux, windows, mac, powerpc, and freebsd

### CODE REVIEW

**Comment by siying** [comment]
Ready to go?

**Comment by sagar0** [comment]
Confirmed that this builds on PowerPC arch as well.

**Comment by ajkr** [comment]
I can't turn it on by default, unfortunately. A lot of unused variables were missed. Let me check why.

**Comment by siying** [comment]
@ajkr then fine. Get it in first. And then do this check.

**Pull request closed without merging**
