### PR TITLE
Ask travis to use JDK 7

### PR DESCRIPTION
**Pull request by adamretter**
@yhchiang This may or may not help

### CODE REVIEW

**Comment by yhchiang** [comment]
Let's wait until the test completed :p

**Comment by adamretter** [comment]
@yhchiang Okay so that fixed the Linux build, the Mac build requires something else, so I am just asking the Travis guys about that...

**Comment by adamretter** [comment]
https://github.com/travis-ci/travis-ci/issues/6716

**Comment by yhchiang** [comment]
LGTM.

**Comment by yhchiang** [comment]
The Land to Master seems not responding.  Anyone happens to know why?

**Comment by yiwu-arbug** [comment]
It's landing: https://phabricator.intern.facebook.com/D4098424

**Pull request closed without merging**
