### PR TITLE
Replace Status with IOStatus for block fetcher IO function

### PR DESCRIPTION
**Pull request by zhichao-cao**
To propagate the IOStatus from file reads to RocksDB read logic, some of the existing status needs to be replaced by IOStatus.

test plan: make check

### CODE REVIEW

**Review by mrambacher — COMMENTED** [review]
This change feels off to me.  Is there a reason we cannot replace the status_ completely with io_status_ and have only one status (instead of status and io_status) in the class?  The fact that every use of the class must ignore the io status is suspect.

With this change, there are two places that update status_ left that are not io_status -- in CheckBlockChecksum and UncompressBlockContents.  (I think the call in TryGetCompressedBlockFromPersistentCache should be a local variable, like TryGetUncompressed.

Is there a reason not to convert these two remaining status into an io_status?

**Comment by zhichao-cao** [comment]
> This change feels off to me. Is there a reason we cannot replace the status_ completely with io_status_ and have only one status (instead of status and io_status) in the class? The fact that every use of the class must ignore the io status is suspect.
> 
> With this change, there are two places that update status_ left that are not io_status -- in CheckBlockChecksum and UncompressBlockContents. (I think the call in TryGetCompressedBlockFromPersistentCache should be a local variable, like TryGetUncompressed.
> 
> Is there a reason not to convert these two remaining status into an io_status?

Actually, we hope that io_status_ only carries the IO related error to the upper layer. Its status can be overwritten by other status as you mentioned like TryGetUncompressed. The follow up PR's will check the io_status_ or pass it higher. Currently, we just ignore it.

**Comment by mrambacher** [comment]
> > This change feels off to me. Is there a reason we cannot replace the status_ completely with io_status_ and have only one status (instead of status and io_status) in the class? The fact that every use of the class must ignore the io status is suspect.
> > With this change, there are two places that update status_ left that are not io_status -- in CheckBlockChecksum and UncompressBlockContents. (I think the call in TryGetCompressedBlockFromPersistentCache should be a local variable, like TryGetUncompressed.
> > Is there a reason not to convert these two remaining status into an io_status?
> 
> Actually, we hope that io_status_ only carries the IO related error to the upper layer. Its status can be overwritten by other status as you mentioned like TryGetUncompressed. The follow up PR's will check the io_status_ or pass it higher. Currently, we just ignore it.

(I would argue that the TryGetUncompressed code is wrong and should use a local status). 

My concern is all of the places that now need to ignore the IO Status.  That feels like a bad programming practice to me.  If there is an error, it should not matter if it is an IO or Status.  I understand that the IO status carries more information, but am not clear why you need to maintain both in this class.  Are you suggesting that a different action would be taken on a Status::NotFound then an IOStatus::NotFound (for example)?

**Comment by zhichao-cao** [comment]
> > > This change feels off to me. Is there a reason we cannot replace the status_ completely with io_status_ and have only one status (instead of status and io_status) in the class? The fact that every use of the class must ignore the io status is suspect.
> > > With this change, there are two places that update status_ left that are not io_status -- in CheckBlockChecksum and UncompressBlockContents. (I think the call in TryGetCompressedBlockFromPersistentCache should be a local variable, like TryGetUncompressed.
> > > Is there a reason not to convert these two remaining status into an io_status?
> > 
> > 
> > Actually, we hope that io_status_ only carries the IO related error to the upper layer. Its status can be overwritten by other status as you mentioned like TryGetUncompressed. The follow up PR's will check the io_status_ or pass it higher. Currently, we just ignore it.
> 
> (I would argue that the TryGetUncompressed code is wrong and should use a local status).
> 
> My concern is all of the places that now need to ignore the IO Status. That feels like a bad programming practice to me. If there is an error, it should not matter if it is an IO or Status. I understand that the IO status carries more information, but am not clear why you need to maintain both in this class. Are you suggesting that a different action would be taken on a Status::NotFound then an IOStatus::NotFound (for example)?

For example, if we have retryable read error, the information can only be stored in IOStatus, then another non IO related error happens in the block_fetcher logic and override the previous one. In this case, IOStatus has retryable flag, but Status show other error. We will not do retry for this read. But if IOStatus and Status matches, we can re-read the data.

**Comment by anand1976** [comment]
As @mrambacher said, it would be cleaner to just store and return ```IOStatus``` throughout ```BlockFetcher```. I don't think we need to worry too much about the ```TryGet*BlockFromPersistentCache```, as the persistent cache is not used much and will likely be deprecated at some point. The caller of ```ReadBlockContents``` can decide whether to act on the ```IOStatus``` or not, right?

**Comment by zhichao-cao** [comment]
> As @mrambacher said, it would be cleaner to just store and return `IOStatus` throughout `BlockFetcher`. I don't think we need to worry too much about the `TryGet*BlockFromPersistentCache`, as the persistent cache is not used much and will likely be deprecated at some point. The caller of `ReadBlockContents` can decide whether to act on the `IOStatus` or not, right?

Right. I did not consider that the persistent cache will be deprecated. Will make the change accordingly.

**Review by anand1976 — APPROVED** [review]
LGTM!

**Comment by zhichao-cao** [comment]
> LGTM!

Thanks for the review!

**Pull request closed without merging**
