### PR TITLE
Add amalgamation to .travis.yml

### PR DESCRIPTION
**Pull request by edsrzf**
Also add unity rule to the makefile.

### CODE REVIEW

**Comment by igorcanadi** [comment]
Should we also have a simple amalgation_test.cc that includes amalgated "rocksdb.h" and verifies that some simple commands (Put, Get) work?

**Comment by edsrzf** [comment]
I can do that. Any suggestions on where to put it?

**Comment by igorcanadi** [comment]
Hmm. Let's put it in tools/

**Comment by igorcanadi** [comment]
Yo, this went a bit stale, so going to close it. Please create a new issue if you still plan to work on it.

**Pull request closed without merging**
