### PR TITLE
Support rocksdbjava aarch64 build and test

### PR DESCRIPTION
**Pull request by cnqpzhang**
Verified with an Ampere Computing eMAG aarch64 system.

### CODE REVIEW

**Comment by cnqpzhang** [comment]
CLA completed already

**Comment by adamretter** [comment]
@cnqpzhang the changes themselves in this PR look good.

@maysamyabandeh I unfortunately have no way of testing this, as I don't have access to an `aarch64` platform? Do you have anything available at FB that we could use?

**Comment by maysamyabandeh** [comment]
@adamretter Unfortunately no. I think as long as the change does not break other platforms and there is a github user confirming that they have tested on the newly added platform, we should be ok with landing the patch.

**Comment by cnqpzhang** [comment]
@maysamyabandeh @adamretter thanks for review. Do you know how the builds for other platforms got generated, for example, 6.0.1 binaries at Maven: http://central.maven.org/maven2/org/rocksdb/rocksdbjni/6.0.1/

**Comment by adamretter** [comment]
@cnqpzhang Yup. I build those releases using the `rocksdbjavastaticreleasedocker` target.

**Comment by cnqpzhang** [comment]
@adamretter Understood (perhaps), it means maven releases could not automatically include aarch64 lib binary unless I would add more things just like what ppc64le did (imagine compiler supported so).

**Comment by cnqpzhang** [comment]
Missed a tiny change [#7d54c94](https://github.com/facebook/rocksdb/pull/5258/commits/7d54c948d522a6bd68b3b20450bed027e59df86f) for fixing ARCH to be 64 instead of 32, if $(PLATFORM) is OS_OPENBSD, $(MACHINE) is arch64, I am unable to verify it, which looks very straight-forward and should be fine.

**Comment by adamretter** [comment]
@cnqpzhang For releases, IBM/OSUOSL have provided me SSH access to an IBM PowerPC 64LE machine, so I do the ppc64le part of the release build on there.

If someone wants to give me SSH access to other platforms, I am happy to add those to the release process.

**Comment by cnqpzhang** [comment]
@adamretter I would take this concern (no aarch64 platform to generate aarch64 binaries for maven release) to Ampere Computing, and see if anyone could help.

**Comment by cnqpzhang** [comment]
@maysamyabandeh @adamretter Could this pull-request be merged? The two commits are both needed.

**Comment by cnqpzhang** [comment]
> @maysamyabandeh I unfortunately have no way of testing this, as I don't have access to an aarch64 platform? Do you have anything available at FB that we could use?
> @adamretter Unfortunately no.

Hi @maysamyabandeh @adamretter 
There would be two options of helping this out, 
1. Try https://github.com/WorksOnArm/cluster/issues, the allocated aarch64 systems can serve for temp use, but it may not guarantee a long-term env for release builds. 
2. I raised this issue in team. [Ampere ](https://amperecomputing.com/)(@Santa Clara) could send a dev system to FB for this, and other similar dev/testing work (if any) on aarch64 . If okay @maysamyabandeh please write to my email (I cannot find yours) and I’d like to set up the connection for detailed follow-ups.

**Comment by siying** [comment]
@adamretter is there qualified hosts in Cloud providers like AWS EC2? We can discuss whether it is possible reimburse the cost for the use.

**Comment by adamretter** [comment]
@siying Yes both AWS EC2 and Scaleway are the aarch64 providers that I know, there may also be others.

However... just to be clear, I am not in any way saying that I can support the aarch64 platform! I am saying that I could perform release builds on aarch64 and report if the builds fail ;-)

**Comment by cnqpzhang** [comment]
@siying @adamretter [Packet](https://www.packet.com/cloud/servers/c2-large-arm/) (similar as Scaleway) can be an option as well, if FB does not want to maintain a physical aarch64 system in office. In addition, I may have a more convenient channel to help access systems there, if selected Ampere eMAG.

About the overall aarch64 support, I haven't seen much work by far, almost all linux64 source and scripts can be used directly. Maybe my estimation is rough, while the 1st step should be "not to break other platforms", which can be easily achieved and verified. Enabling aarch64 build with this PR helped me successfully run [Flink ](https://github.com/apache/flink)and [flink-benchmarks](https://github.com/dataArtisans/flink-benchmarks), however this sounds beyond the scope of this discussion.

**Comment by cnqpzhang** [comment]
Hi @adamretter, I wonder whether this pull-in request can be merged suppose no further concerns about the code changes and on the condition that it would not bring any negative impact on other builds. Thanks.

**Comment by wangxiyuan** [comment]
@cnqpzhang, When I run test on ARM, I hit these tests failures: `make check_some` #5736 and `make jtest` #5751

Do you  hit them as well? Do you have any suggestion?

Thanks very much.

**Pull request closed without merging**
