### PR TITLE
Fix WriteBatch rep_ format for RangeDeletion records

### PR DESCRIPTION
**Pull request by nvanbenschoten**
This is a small amount of general cleanup I made while experimenting with https://github.com/facebook/rocksdb/issues/3391.

### CODE REVIEW

**Comment by yiwu-arbug** [comment]
@nvanbenschoten do you mind signing the CLA? Thanks.

**Comment by nvanbenschoten** [comment]
Huh, I did before but nothing happened. Now it's saying "Email is already associated with an existing contributor."

**Comment by yiwu-arbug** [comment]
@nvanbenschoten You need to email cla@fb.com to get the issue resolve. Do you mind doing that?

**Comment by nvanbenschoten** [comment]
@yiwu-arbug email sent!

**Pull request closed without merging**
