### PR TITLE
Exclude more Travis builds for each pull request

### PR DESCRIPTION
**Pull request by pdillinger**
Summary: On recently adding ARM64 and PPC64LE builds to Travis, we
seem to have hit some parallel build limits that dramatically increased
queue times.

This change majorly limits the configurations for ARM64 and PPC64LE to
build on each pull request, but keeps the large matrix for branch
builds.

In the process, I changed some previously excluded osx build configurations
to happen in branch builds.

NB: we might want to move master branch Travis build to daily trigger
rather than push trigger to further reduce contention.

Test Plan: Travis only

### CODE REVIEW

**Comment by siying** [comment]
The Travis build launched for the PR seems to run more builds, not less. Not sure whether I missed anything.

**Comment by pdillinger** [comment]
> The Travis build launched for the PR seems to run more builds, not less. Not sure whether I missed anything.

It's the same, but I have a double-negation problem 🤣

**Comment by pdillinger** [comment]
> NB: we might want to move master branch Travis build to daily trigger
> rather than push trigger to further reduce contention.

Push trigger applies to all branches. Disabling and moving to cron trigger would be terrible state for maintenance branches, because cron trigger cannot skip if no changes since last build. Either over-build or unresponsive build. 😡

**Comment by pdillinger** [comment]
cc @adamretter

**Comment by adamretter** [comment]
@pdillinger Do I understand correctly, that you have removed tests for Pull Requests, but kept them for branches?

If so, then IMHO I think this is the wrong way around.

For example as a contributor I want to know if my Pull Request passes the test suite. As a project maintainer I want to know if each Pull Request passes the test suite before I merge.

Feature branches are maintained in other peoples forks, so they won't be present to test here.

**Comment by adamretter** [comment]
@pdillinger This got merged even after I had questions about whether it was the right approach... I still have those questions ;-) Could you respond to my questions above please?

**Comment by pdillinger** [comment]
We have never run all the tests we possibly can on every pull request. That continues to be the case. Pretty good feedback quickly is better than almost no feedback for hours and hours. This is 100% a pragmatic change open to future revision.

**Comment by adamretter** [comment]
@pdillinger Sure, but my concern is that we are now excluding too much. For Arm64 and ppc64le the tests that seemed to have the biggest problems were in TEST_GROUP 1 to 4.

Additionally, I initially started these multi-platform efforts for RocksJava as requested by users, but now RocksJava tests have been removed for non-x64 platforms. I think there might be another option... I will contact you directly about.

**Pull request closed without merging**
