### PR TITLE
remove unnecessary code in super version getter

### PR DESCRIPTION
**Pull request by ywave620**
Do not bother comparing the version of the local super version handle with the global one.

An inequality comparison result indicates nothing but a spurious obsoleteness. It only happens when the writer has increased the `ColumnFamilyData::super_version_number_`(https://github.com/facebook/rocksdb/blob/5fc57eec2b44337289f25c1b5687beb54ad709a2/db/column_family.cc#L1309) but has not yet called `ResetThreadLocalSuperVersions()`(https://github.com/facebook/rocksdb/blob/5fc57eec2b44337289f25c1b5687beb54ad709a2/db/column_family.cc#L1328) at the time when a reader reads the local handle(`void* ptr = local_sv_->Swap(SuperVersion::kSVInUse);`). In other words, the existence of a local handle is a sufficent evidence of its fressness.

With this PR, we save one or even two atomic instructions when getting a handle of super version.

### CODE REVIEW

**Comment by cbi42** [comment]
> Because the comparison yields inequality only in a small and non-interruptable window ...

I don't think this is true though: if a thread completes `ResetThreadLocalSuperVersions()` right after another thread does `void* ptr = local_sv_->Swap(SuperVersion::kSVInUse);`, wouldn't the inequality holds after `ResetThreadLocalSuperVersions()`?

**Comment by cbi42** [comment]
> the existence of a local handle is a sufficent evidence of its fressness

I tend to agree with this. For the local handle to be outdated, a new superversion needs to be installed (specifically, `ResetThreadLocalSuperVersions()` needs to be called) after the local handle is taken at 

https://github.com/facebook/rocksdb/blob/509116c53b69120133aa9d89eea056bd67634a12/db/column_family.cc#L1240

in which case the local handle seems up-to-date enough.

**Comment by ywave620** [comment]
@cbi42 yeah! The read-write competition is(and should be) resolved by the atomic instruction conducted on the thread local handle, rather than the global superversion number.

**Review by cbi42 — APPROVED** [review]

**Review by cbi42 — APPROVED** [review]

**Comment by cbi42** [comment]
> > Because the comparison yields inequality only in a small and non-interruptable window ...
> 
> I don't think this is true though: if a thread completes `ResetThreadLocalSuperVersions()` right after another thread does `void* ptr = local_sv_->Swap(SuperVersion::kSVInUse);`, wouldn't the inequality holds after `ResetThreadLocalSuperVersions()`?

@ywave620  Could you update the PR description accordingly?

**Comment by ywave620** [comment]
@cbi42 Done. PTAL :)

**Pull request closed without merging**
