### PR TITLE
Update cmake to not build tests when not in Debug

### LINKED ISSUE #3816: Cmake release should not compile *_test.cc files
### Expected behavior

No compile error in cmake Release build.

### Actual behavior

In Release build (i.e. with `NDEBUG`):
rocksdb::SyncPoint is not defined due to `#ifdef NDEBUG`

https://github.com/facebook/rocksdb/blob/72942ad7a40d23ef9b6edf6cf1f53628e37c56b4/util/sync_point.h#L44-L48

But still referenced by files:

https://github.com/facebook/rocksdb/blob/72942ad7a40d23ef9b6edf6cf1f53628e37c56b4/util/auto_roll_logger_test.cc#L294

### Steps to reproduce the behavior

```
mkdir -p build
cd $_
cmake -DCMAKE_BUILD_TYPE=Release <other arguments> ..
```

### PR DESCRIPTION
**Pull request by gfosco**
Fixes #3816

### CODE REVIEW

**Comment by yuslepukhin** [comment]
@gfosco   This is already the case because all tests projects are excluded from Release configurations.

**Comment by gfosco** [comment]
@yuslepukhin I would've thought so, but I was able to reproduce the issue and this line fixes it in my testing.

**Comment by yuslepukhin** [comment]
@ajkr I think it depends on what the target is. There is an artificially generated project ALL and when you build it the exclusions do not work on Windows. One has to build rocksdb.sln not All. Not sure what the story with other platform generated makefiles.

**Comment by mrambacher** [comment]
This was fixed by #6921

**Pull request closed without merging**
