### PR TITLE
WriteBatchWithIndex refactory: Allow third party index implementation

### PR DESCRIPTION
**Pull request by rockeet**
WriteBatchWithIndex hard coded `SkipList` as index implementation, this PR refactory the interface to allow third party index implementation, `SkipList` is used as default.

### CODE REVIEW

**Comment by zhichao-cao** [comment]
Thanks for the contributions! make format to correct the code formatting issues.

**Comment by rockeet** [comment]
> Thanks for the contributions! make format to correct the code formatting issues.

`make format` touched many files which didn't touched in this PR, is there a way to just touch the changed files ?

**Comment by rockeet** [comment]
> Thanks for the contributions! make format to correct the code formatting issues.

format was corrected, is it time to merging?

**Comment by zhichao-cao** [comment]
> > Thanks for the contributions! make format to correct the code formatting issues.
> 
> format was corrected, is it time to merging?

I will defer it to someone who is familiar with the WriteBatch

**Comment by rockeet** [comment]
> > > Thanks for the contributions! make format to correct the code formatting issues.
> > 
> > 
> > format was corrected, is it time to merging?
> 
> I will defer it to someone who is familiar with the WriteBatch

OK, I'm waiting for good news

**Pull request closed without merging**
