### PR TITLE
fixes 1217: rocksdbjni javac and javah execute_processes fail on windows

### PR DESCRIPTION
**Pull request by clumsy**
picking execute_process command based on OS

### CODE REVIEW

**Comment by adamretter** [comment]
@yuslepukhin Could you give me an opinion on the changes to `java/CMakeLists.txt` for Windows please?

**Comment by yuslepukhin** [comment]
@adamretter I think this looks fine. It would work nicely to support cross-platform CMake.

**Comment by adamretter** [comment]
@yuslepukhin Thanks, much appreciated :-)

**Comment by adamretter** [comment]
Closes https://github.com/facebook/rocksdb/issues/1217

**Pull request merged**
