### PR TITLE
use verify checksum option in block based table reader Open()

### PR DESCRIPTION
**Pull request by matkt**
## Description 
In this issue https://github.com/facebook/rocksdb/issues/11002 we found that when we use rocksdb with the `verify checksum` read_option to false the verification is done anyway

By analyzing the code along the stacktrace I saw that at the level of https://github.com/facebook/rocksdb/compare/main...matkt:feature/use-verify-checksum-in-block-based-table-reader?expand=1#diff-57ed8c49db2bdd4db7618646a177397674bbf25beacacecb104070071d30129f we are not keeping all the options and we forget the `verify_checksum`

the comment in this class suggests that it should be managed https://github.com/facebook/rocksdb/compare/main...matkt:feature/use-verify-checksum-in-block-based-table-reader?expand=1#diff-57ed8c49db2bdd4db7618646a177397674bbf25beacacecb104070071d30129fL581

204511641-86ab4b9b-45e5-4a2b-a13d-81fa26435d38

this PR just adds the line to manage the `verify checksum`

## Tests

- Running unit tests
- Test without setting `verify checksum` and verifying that we are calling the checksum code
- Test by setting `verify checksum` to true and verifying that we are calling the checksum code
- Test by setting `verify checksum` to false and verifying that we are **not** calling the checksum code

### CODE REVIEW

**Comment by matkt** [comment]
hi @ajkr this modification is impacting a test https://github.com/facebook/rocksdb/blob/main/db/corruption_test.cc#L498 but when I check at the description is seems to be a problem in the test but I can miss something 

here we can see that the test try to disable the checksum  https://github.com/facebook/rocksdb/blob/main/db/corruption_test.cc#L174 but when I checked the code I found that without this PR we are doing the checksum even if the option is set to false. By doing the modification in this PR we are really disabling checksum and the result is different

**Review by ajkr — COMMENTED** [review]
> It seems we are trying to disable checksum for the DB but not for the block fetcher. The problem we have the same flag for the two parts

I think the test "TableFileIndexData" is written in a way that letting the DB detect the index block is corrupted is correct. So maybe we can set `ReadOptions::verify_checksums=true` when creating the iterator in that particular test.

**Comment by matkt** [comment]
I did the modification of the test. The PR is ready for a review . thanks for your help @ajkr :)

**Review by ajkr — APPROVED** [review]
LGTM, thanks!

Can we add a line like below to HISTORY.md "Behavior Changes" section?

```
* `ReadOptions::verify_checksums=false` disables checksum verification for more reads of non-`CacheEntryRole::kDataBlock` blocks.
```

I should probably try to finish #10427 in the same release; that way, there's only one behavior change for the known cases of verifying checksum against the user's wish.

**Comment by matkt** [comment]
it seems the pipeline is not passing anymore and I cannot check the lint issue

**Comment by cbi42** [comment]
> it seems the pipeline is not passing anymore and I cannot check the lint issue

The linter issue is not related to your change, it is just pending review now.

**Comment by matkt** [comment]
I updated the HISTORY file . thanks

**Comment by matkt** [comment]
I fixed the HISTORY conflict . I think we can merge

**Comment by matkt** [comment]
Hi do you know if this PR will be in the next Rocksdb release? This is something we need for our project but I don't know when it will be released. @ajkr thanks

**Comment by Dan-SPDB** [comment]
this change was merged into RocksDB 2 weeks ago. This most likely means that it will be in RocksDB 8.0 (the next release).

**Pull request closed without merging**
