### PR TITLE
Fix the RocksJava Release on Windows

### PR DESCRIPTION
**Pull request by adamretter**
This was previously broken accidentally by https://github.com/facebook/rocksdb/pull/2107

Closes https://github.com/facebook/rocksdb/issues/2293

### CODE REVIEW

**Comment by tamird** [comment]
@adamretter is it correct that the java release build uses cmake? That's interesting, since the travis CI configuration still uses the Makefile. Would you be in favor of a PR removing the makefile in favour of the cmake build system (for Java)?

**Comment by adamretter** [comment]
@tamird The CMake build was added for building on Windows platforms. So CMake is used on Windows to generate the build files for Visual Studio, after that `msbuild` does the build.

As far as RocksJava goes, we only use CMake on Windows platforms, the `Makefile` is used on all other platforms as far as I am aware, e.g. Mac, Linux etc.

I wouldn't be in favour of removing the Makefile, as we use it for Mac and crossbuilding linux32/linux64 etc when publishing RocksJava.

**Comment by tamird** [comment]
Ouch. It'd be nice to converge everything into a single build system, but I
don't think it will happen with an internal (read: facebook employee)
champion.

**Comment by adamretter** [comment]
@tamird I agree that a single build system would be nice. I also agree that for it to support it likely needs to be driven by Facebook.

**Comment by tamird** [comment]
@adamretter is the windows release build part of this repository? I can't find it, and attempting to run `cmake <path-to-rocksdb/java>` produces:
```
javac: file not found: /Users/tamird/src/rocksdb/java/java/src/main/java/org/rocksdb/util/*.java
Usage: javac <options> <source files>
use -help for a list of possible options
Error: Could not find class file for 'org.rocksdb.AbstractCompactionFilter'.
Error: Could not find class file for 'org.rocksdb.AbstractComparator'.
Error: Could not find class file for 'org.rocksdb.AbstractImmutableNativeReference'.
Error: Could not find class file for 'org.rocksdb.AbstractNativeReference'.
Error: Could not find class file for 'org.rocksdb.AbstractRocksIterator'.
Error: Could not find class file for 'org.rocksdb.AbstractSlice'.
Error: Could not find class file for 'org.rocksdb.AbstractWriteBatch'.
Error: Could not find class file for 'org.rocksdb.BackupableDBOptions'.
Error: Could not find class file for 'org.rocksdb.BackupEngine'.
Error: Could not find class file for 'org.rocksdb.BackupEngineTest'.
Error: Could not find class file for 'org.rocksdb.BlockBasedTableConfig'.
Error: Could not find class file for 'org.rocksdb.BloomFilter'.
Error: Could not find class file for 'org.rocksdb.Cache'.
Error: Could not find class file for 'org.rocksdb.Checkpoint'.
Error: Could not find class file for 'org.rocksdb.ClockCache'.
Error: Could not find class file for 'org.rocksdb.ColumnFamilyHandle'.
Error: Could not find class file for 'org.rocksdb.ColumnFamilyOptions'.
Error: Could not find class file for 'org.rocksdb.CompactionOptionsFIFO'.
Error: Could not find class file for 'org.rocksdb.CompactionOptionsUniversal'.
Error: Could not find class file for 'org.rocksdb.Comparator'.
Error: Could not find class file for 'org.rocksdb.ComparatorOptions'.
Error: Could not find class file for 'org.rocksdb.CompressionOptions'.
Error: Could not find class file for 'org.rocksdb.DBOptions'.
Error: Could not find class file for 'org.rocksdb.DirectComparator'.
Error: Could not find class file for 'org.rocksdb.DirectSlice'.
Error: Could not find class file for 'org.rocksdb.Env'.
Error: Could not find class file for 'org.rocksdb.EnvOptions'.
Error: Could not find class file for 'org.rocksdb.ExternalSstFileInfo'.
Error: Could not find class file for 'org.rocksdb.Filter'.
Error: Could not find class file for 'org.rocksdb.FlushOptions'.
Error: Could not find class file for 'org.rocksdb.HashLinkedListMemTableConfig'.
Error: Could not find class file for 'org.rocksdb.HashSkipListMemTableConfig'.
Error: Could not find class file for 'org.rocksdb.Logger'.
Error: Could not find class file for 'org.rocksdb.LRUCache'.
Error: Could not find class file for 'org.rocksdb.MemTableConfig'.
Error: Could not find class file for 'org.rocksdb.MergeOperator'.
Error: Could not find class file for 'org.rocksdb.NativeLibraryLoader'.
Error: Could not find class file for 'org.rocksdb.Options'.
Error: Could not find class file for 'org.rocksdb.PlainTableConfig'.
Error: Could not find class file for 'org.rocksdb.RateLimiter'.
Error: Could not find class file for 'org.rocksdb.ReadOptions'.
Error: Could not find class file for 'org.rocksdb.RemoveEmptyValueCompactionFilter'.
Error: Could not find class file for 'org.rocksdb.RestoreOptions'.
Error: Could not find class file for 'org.rocksdb.RocksDB'.
Error: Could not find class file for 'org.rocksdb.RocksDBExceptionTest'.
Error: Could not find class file for 'org.rocksdb.RocksEnv'.
Error: Could not find class file for 'org.rocksdb.RocksIterator'.
Error: Could not find class file for 'org.rocksdb.RocksIteratorInterface'.
Error: Could not find class file for 'org.rocksdb.RocksMemEnv'.
Error: Could not find class file for 'org.rocksdb.RocksMutableObject'.
Error: Could not find class file for 'org.rocksdb.RocksObject'.
Error: Could not find class file for 'org.rocksdb.SkipListMemTableConfig'.
Error: Could not find class file for 'org.rocksdb.Slice'.
Error: Could not find class file for 'org.rocksdb.Snapshot'.
Error: Could not find class file for 'org.rocksdb.SnapshotTest'.
Error: Could not find class file for 'org.rocksdb.SstFileWriter'.
Error: Could not find class file for 'org.rocksdb.Statistics'.
Error: Could not find class file for 'org.rocksdb.StringAppendOperator'.
Error: Could not find class file for 'org.rocksdb.TableFormatConfig'.
Error: Could not find class file for 'org.rocksdb.TransactionLogIterator'.
Error: Could not find class file for 'org.rocksdb.TtlDB'.
Error: Could not find class file for 'org.rocksdb.VectorMemTableConfig'.
Error: Could not find class file for 'org.rocksdb.WBWIRocksIterator'.
Error: Could not find class file for 'org.rocksdb.WriteBatch'.
Error: Could not find class file for 'org.rocksdb.WriteBatch.Handler'.
Error: Could not find class file for 'org.rocksdb.WriteBatchTest'.
Error: Could not find class file for 'org.rocksdb.WriteBatchTestInternalHelper'.
Error: Could not find class file for 'org.rocksdb.WriteBatchWithIndex'.
Error: Could not find class file for 'org.rocksdb.WriteOptions'.
```
Which seems to be the result of my running the wrong command.

**Comment by sagar0** [comment]
Am curious why appveyor build did not get invoked for this.

**Comment by sagar0** [comment]
nvm, I am just a little behind in reading all the comments. There's already seems to be ongoing conversation in other PRs and Issues about windows and appveyor build break.

**Comment by adamretter** [comment]
@tamird The process I use for CMake on Windows is described here - https://github.com/facebook/rocksdb/wiki/Building-on-Windows

Afterwards RocksJava is in `build\java\Release`.

**Comment by tamird** [comment]
Interesting. Looks like CMake's [`execute_process`](https://cmake.org/cmake/help/latest/command/execute_process.html) doesn't work the same on *nix as it does on Windows:

(note the error **`javac: file not found: /Users/tamird/src/rocksdb/java/src/main/java/org/rocksdb/util/*.java`**)

```
[tamird:~/src/rocksdb/build] master ± cmake .. -DJNI=1
-- JNI library is enabled
Downloading /Users/tamird/src/rocksdb/java/test-libs/junit-4.12.jar
Downloading /Users/tamird/src/rocksdb/java/test-libs/hamcrest-core-1.3.jar
Downloading /Users/tamird/src/rocksdb/java/test-libs/mockito-all-1.10.19.jar
Downloading /Users/tamird/src/rocksdb/java/test-libs/cglib-2.2.2.jar
Downloading /Users/tamird/src/rocksdb/java/test-libs/assertj-core-1.7.1.jar
javac: file not found: /Users/tamird/src/rocksdb/java/src/main/java/org/rocksdb/util/*.java
Usage: javac <options> <source files>
use -help for a list of possible options
Error: Could not find class file for 'org.rocksdb.AbstractCompactionFilter'.
Error: Could not find class file for 'org.rocksdb.AbstractComparator'.
Error: Could not find class file for 'org.rocksdb.AbstractImmutableNativeReference'.
Error: Could not find class file for 'org.rocksdb.AbstractNativeReference'.
Error: Could not find class file for 'org.rocksdb.AbstractRocksIterator'.
Error: Could not find class file for 'org.rocksdb.AbstractSlice'.
Error: Could not find class file for 'org.rocksdb.AbstractWriteBatch'.
Error: Could not find class file for 'org.rocksdb.BackupableDBOptions'.
Error: Could not find class file for 'org.rocksdb.BackupEngine'.
Error: Could not find class file for 'org.rocksdb.BackupEngineTest'.
Error: Could not find class file for 'org.rocksdb.BlockBasedTableConfig'.
Error: Could not find class file for 'org.rocksdb.BloomFilter'.
Error: Could not find class file for 'org.rocksdb.Cache'.
Error: Could not find class file for 'org.rocksdb.Checkpoint'.
Error: Could not find class file for 'org.rocksdb.ClockCache'.
Error: Could not find class file for 'org.rocksdb.ColumnFamilyHandle'.
Error: Could not find class file for 'org.rocksdb.ColumnFamilyOptions'.
Error: Could not find class file for 'org.rocksdb.CompactionOptionsFIFO'.
Error: Could not find class file for 'org.rocksdb.CompactionOptionsUniversal'.
Error: Could not find class file for 'org.rocksdb.Comparator'.
Error: Could not find class file for 'org.rocksdb.ComparatorOptions'.
Error: Could not find class file for 'org.rocksdb.CompressionOptions'.
Error: Could not find class file for 'org.rocksdb.DBOptions'.
Error: Could not find class file for 'org.rocksdb.DirectComparator'.
Error: Could not find class file for 'org.rocksdb.DirectSlice'.
Error: Could not find class file for 'org.rocksdb.Env'.
Error: Could not find class file for 'org.rocksdb.EnvOptions'.
Error: Could not find class file for 'org.rocksdb.ExternalSstFileInfo'.
Error: Could not find class file for 'org.rocksdb.Filter'.
Error: Could not find class file for 'org.rocksdb.FlushOptions'.
Error: Could not find class file for 'org.rocksdb.HashLinkedListMemTableConfig'.
Error: Could not find class file for 'org.rocksdb.HashSkipListMemTableConfig'.
Error: Could not find class file for 'org.rocksdb.Logger'.
Error: Could not find class file for 'org.rocksdb.LRUCache'.
Error: Could not find class file for 'org.rocksdb.MemTableConfig'.
Error: Could not find class file for 'org.rocksdb.MergeOperator'.
Error: Could not find class file for 'org.rocksdb.NativeLibraryLoader'.
Error: Could not find class file for 'org.rocksdb.Options'.
Error: Could not find class file for 'org.rocksdb.PlainTableConfig'.
Error: Could not find class file for 'org.rocksdb.RateLimiter'.
Error: Could not find class file for 'org.rocksdb.ReadOptions'.
Error: Could not find class file for 'org.rocksdb.RemoveEmptyValueCompactionFilter'.
Error: Could not find class file for 'org.rocksdb.RestoreOptions'.
Error: Could not find class file for 'org.rocksdb.RocksDB'.
Error: Could not find class file for 'org.rocksdb.RocksDBExceptionTest'.
Error: Could not find class file for 'org.rocksdb.RocksEnv'.
Error: Could not find class file for 'org.rocksdb.RocksIterator'.
Error: Could not find class file for 'org.rocksdb.RocksIteratorInterface'.
Error: Could not find class file for 'org.rocksdb.RocksMemEnv'.
Error: Could not find class file for 'org.rocksdb.RocksMutableObject'.
Error: Could not find class file for 'org.rocksdb.RocksObject'.
Error: Could not find class file for 'org.rocksdb.SkipListMemTableConfig'.
Error: Could not find class file for 'org.rocksdb.Slice'.
Error: Could not find class file for 'org.rocksdb.Snapshot'.
Error: Could not find class file for 'org.rocksdb.SnapshotTest'.
Error: Could not find class file for 'org.rocksdb.SstFileWriter'.
Error: Could not find class file for 'org.rocksdb.Statistics'.
Error: Could not find class file for 'org.rocksdb.StringAppendOperator'.
Error: Could not find class file for 'org.rocksdb.TableFormatConfig'.
Error: Could not find class file for 'org.rocksdb.TransactionLogIterator'.
Error: Could not find class file for 'org.rocksdb.TtlDB'.
Error: Could not find class file for 'org.rocksdb.VectorMemTableConfig'.
Error: Could not find class file for 'org.rocksdb.WBWIRocksIterator'.
Error: Could not find class file for 'org.rocksdb.WriteBatch'.
Error: Could not find class file for 'org.rocksdb.WriteBatch.Handler'.
Error: Could not find class file for 'org.rocksdb.WriteBatchTest'.
Error: Could not find class file for 'org.rocksdb.WriteBatchTestInternalHelper'.
Error: Could not find class file for 'org.rocksdb.WriteBatchWithIndex'.
Error: Could not find class file for 'org.rocksdb.WriteOptions'.
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   rocksdbjni

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/tamird/src/rocksdb/build
```
But the files are there:

```
[tamird:~/src/rocksdb/build] master ± ls /Users/tamird/src/rocksdb/java/src/main/java/org/rocksdb/util/*.java
-rw-r--r--  1 tamird  staff   2.8K May 15 14:52 /Users/tamird/src/rocksdb/java/src/main/java/org/rocksdb/util/BytewiseComparator.java
-rw-r--r--  1 tamird  staff   2.7K May 15 14:52 /Users/tamird/src/rocksdb/java/src/main/java/org/rocksdb/util/DirectBytewiseComparator.java
-rw-r--r--  1 tamird  staff   2.5K May 15 14:52 /Users/tamird/src/rocksdb/java/src/main/java/org/rocksdb/util/Environment.java
-rw-r--r--  1 tamird  staff   1.2K May 15 14:52 /Users/tamird/src/rocksdb/java/src/main/java/org/rocksdb/util/ReverseBytewiseComparator.java
-rw-r--r--  1 tamird  staff   578B May 15 14:52 /Users/tamird/src/rocksdb/java/src/main/java/org/rocksdb/util/SizeUnit.java
```

**Comment by adamretter** [comment]
@tamird I have almost no experience with CMake, I am really just a Java developer who knows some C++.

The build with CMake was originally contributed by Microsoft (@yuslepukhin) to be able to build RocksDB on Windows. I would be happy if it supports both Windows and MinGW, but my priority is that it just builds RocksJava on Windows correctly, as I am somewhat responsible for building and publishing RocksJava.

If you can improve it to work on both platforms, then that is great. Apart from learning it myself, I am not sure I can be particularly helpful though with supporting MinGW. My fear is that any changes for MinGW should not break the current facility for building on Windows.

**Pull request closed without merging**
