### PR TITLE
(6.16.fb) range_tree requires GNU libc on ppc64

### PR DESCRIPTION
**Pull request by adamretter**
Backport to 6.16.fb of https://github.com/facebook/rocksdb/pull/8070

If the platform is ppc64 and the libc is not GNU libc, then we exclude the range_tree from compilation.

See https://jira.percona.com/browse/PS-7559

### CODE REVIEW

**Review by mrambacher — APPROVED** [review]
LGTM.

**Comment by jay-zhuang** [comment]
Once #8070 is merged in master, we're going to cherry-pick the change to 6.16.fb. Thanks for the fix.

**Comment by adamretter** [comment]
@jay-zhuang as per my email. The PRs are not identical. You will not only have to cherry pick but you would also have to make changes. Perhaps it's easier to merge this?

**Comment by jay-zhuang** [comment]
@adamretter sounds good, I'll still wait on #8070 to be merged first.

**Pull request closed without merging**
