### PR TITLE
[RocksJava] Allow using ReadOptions with iterators

### PR DESCRIPTION
**Pull request by fyrz**
With this pull request a iterator can be retrieved using a Snapshot.

This pull request depends on: https://github.com/facebook/rocksdb/pull/462

Differential: https://reviews.facebook.net/D31857

### CODE REVIEW

**Comment by adamretter** [comment]
Hey @yhchiang, any chance this one could get some attention. I could really use this in the `master` branch ;-)

**Comment by yhchiang** [comment]
The patch LGTM.  Once rebased it's good to go :).  Thanks for your effort on this, @fyrz and @adamretter.

**Comment by fyrz** [comment]
@yhchiang done.

**Comment by yhchiang** [comment]
@fryz done. :)

**Pull request merged**
