### PR TITLE
RocksJava must compile on JDK7

### PR DESCRIPTION
**Pull request by adamretter**
Fixes some RocksJava regressions recently introduced, whereby RocksJava would not build on JDK 7.
These should have been visible on Travis-CI!

### CODE REVIEW

**Comment by sagar0** [comment]
Its surprising that Travis hasn't caught them! This would make me suspect every java travis run from now on :( .

**Comment by Myasuka** [comment]
@adamretter @sagar0 Recently, we're building rocksdb-5.18.3 to combine our own features for java cross build. However, I found current [v5.18.3](https://github.com/facebook/rocksdb/tree/v5.18.3) branch has at least two bugs to block our building. One is this java bug and the other is #5053 . I'm a bit confused that what is the real process for you to release rocksdb-java package. IMO, if we strictly follow the release guide, we must come across these two bugs.

**Comment by adamretter** [comment]
@Myasuka So, when I do the builds from the tags, there is sometimes an issue or two. These have usually been fixed and merged, but not cherry-picked back into the tag. As such I take the tag and cherry-pick the fixes, before then releasing. I then let @gfosco know which fixes I had to cherry-pick, so that hopefully they make it into the next release tag.

**Comment by Myasuka** [comment]
@adamretter @gfosco Would you please tell me what issues encountered when releasing 5.18.3?
Actually I found the two issues I mentioned not picked into [5.18](https://github.com/facebook/rocksdb/tree/5.18.fb). 
Moreover, would you please share some information about performance check when release a new version. We just use [flink-benchmarks](https://github.com/dataArtisans/flink-benchmarks) to verify the performance change for RocksDB state but found a bit performance regression of less than 6% when comparing 5.18.3 to 5.17.2

**Comment by adamretter** [comment]
@Myasuka I can't comment on performance testing, as I am not involved in that. Perhaps @gfosco  could comment on that?

Unfortunately as 5.18.3 was released back in February, I cannot now remember exactly what fixes I had to back-port. Sorry.

**Comment by Myasuka** [comment]
@gfosco  Could you please share some information on the performance testing when release?

**Pull request closed without merging**
