### PR TITLE
Some minor fix-ups

### PR DESCRIPTION
**Pull request by riversand963**
Cleanup some code without any real change in functionality.

### CODE REVIEW

**Comment by zhichao-cao** [comment]
@riversand963 One question, for the class `ArenaWrappedDBIter` and `BlockIter`, if virtual is removed, the future derived class functions cannot be called by the base. So you assume the derivation will not happen or the derivation member function will not be called by the base pointer?

**Comment by riversand963** [comment]
Thanks @zhichao-cao for the review. I think `override` without `virtual` in the derived class provides more check, as [post](https://stackoverflow.com/questions/39932391/virtual-override-or-both-c) and [post](https://stackoverflow.com/questions/13880205/is-the-override-keyword-just-a-check-for-a-overridden-virtual-method) explain. The methods will still remain virtual because they are marked as `virtual` in the base class, i.e. `Iterator` and `InternalIteratorBase`.
Can you give an example to illustrate when it goes wrong?

**Comment by zhichao-cao** [comment]
> Thanks @zhichao-cao for the review. I think `override` without `virtual` in the derived class provides more check, as [post](https://stackoverflow.com/questions/39932391/virtual-override-or-both-c) and [post](https://stackoverflow.com/questions/13880205/is-the-override-keyword-just-a-check-for-a-overridden-virtual-method) explain. The methods will still remain virtual because they are marked as `virtual` in the base class, i.e. `Iterator` and `InternalIteratorBase`.
> Can you give an example to illustrate when it goes wrong?

Thanks for the explanation. Yes, it can provide more check during compile. I'm thinking the following case, not sure it will happen or not:

```
class BlockIter:public Iter{
virtual seek() override{ func 1};
};

class DerBlockIter:public BlockIter {
seek() override{ func 2};
}

BlockIter* bp = new DerBlockIter();
bp->seek(); 
```

In this case, if virtual is removed, it can only call func1 instead of func2. I'm not sure, if the two class might be used in this way or not? Or we always use the abstract class pointer for all of them, if so, removing virtual is fine.

**Comment by riversand963** [comment]
I don't think that is going to happen due to C++ polymorphism.
```
#include <cstdio>

class Base {
 public:
  virtual void foo() {
    fprintf(stdout, "base foo\n");
  }
};

class Derived : public Base {
 public:
   void foo() override {
    fprintf(stdout, "derived foo\n");
   }
};


int main() {
  Base* ptr = new Derived();
  ptr->foo();
  delete ptr;
  return 0;
}
```


```
$g++ -std=c++11 test.cc -o test
$./test
derived foo
```

**Comment by zhichao-cao** [comment]
> I don't think that is going to happen due to C++ polymorphism.
> 
> ```
> #include <cstdio>
> 
> class Base {
>  public:
>   virtual void foo() {
>     fprintf(stdout, "base foo\n");
>   }
> };
> 
> class Derived : public Base {
>  public:
>    void foo() override {
>     fprintf(stdout, "derived foo\n");
>    }
> };
> 
> class Derived2 : public Derived {
>  public:
>   void foo() override {
>     fprintf(stdout, "derived2 foo\n");
>   }
> };
> 
> int main() {
>   Base* ptr = new Derived2();
>   ptr->foo();
>   delete ptr;
>   return 0;
> }
> ```
> 
> ```
> $g++ -std=c++11 test.cc -o test
> $./test
> derived2 foo
> ```

Thanks for the detailed example. You are right, removing virtual has no influence here.

**Comment by riversand963** [comment]
Thanks again!

**Pull request closed without merging**
