### PR TITLE
CMake: more MinGW fixes

### PR DESCRIPTION
**Pull request by tamird**
See individual commits.

@yuslepukhin @siying

### CODE REVIEW

**Comment by tamird** [comment]
@IslamAbdelRahman LGTY?

**Comment by siying** [comment]
@tamird we are not able to review the Windows part. I need to wait for @yuslepukhin or other experts to comment.

**Comment by tamird** [comment]
cc @orgads as well.

**Comment by yuslepukhin** [comment]
@siying Thanks for checking. This looks fine to me.

**Comment by siying** [comment]
Sorry I have to revert it for now as it breaks Linux build:

db/db_impl.cc: In function ‘void rocksdb::DumpMallocStats(std::string*)’:
db/db_impl.cc:614:54: error: ‘je_malloc_stats_print’ was not declared in this scope
   je_malloc_stats_print(GetJemallocStatus, &mstat, "");
                                                      ^

**Comment by siying** [comment]
Reverted: https://github.com/facebook/rocksdb/commit/43010a929f8123b6b554870abff1720186a3e929
Sorry for not telling you the failure before the commit. Feel free to resubmit a diff that works for all the platforms.

**Comment by tamird** [comment]
Was this an internal build? What version of jemalloc are you using?

**Comment by tamird** [comment]
@siying?

**Pull request closed without merging**
