### PR TITLE
env_chroot.cc: FreeBSD likes stdlib.h for realpaht() and friends

### PR DESCRIPTION
**Pull request by wjwithagen**

### CODE REVIEW

**Comment by facebook-github-bot-3** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-6** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by ajkr** [comment]
Thank you!

**Comment by wjwithagen** [comment]
On 6-6-2016 02:23, Andrew Kryczka wrote:
> Thank you!
> 
Hi Andrew,

Thanx for picking this up so swiftly.
Makes my porting of Ceph for FreeBSD a bit less cumbersome.

**Pull request merged**
