### PR TITLE
modified format-diff.sh with updated instructions in case "make format" command fails

### PR DESCRIPTION
**Pull request by raza15**
modified format-diff.sh with updated instructions in case "make format" command fails

### CODE REVIEW

**Comment by yiwu-arbug** [comment]
Thank you! And please remove unrelated changes.

**Comment by raza15** [comment]
@yiwu-arbug is it fine now? If not, can you please specify what unrelated changes?

**Comment by yiwu-arbug** [comment]
Can you remove changes from #2004? I've merge that PR.

**Comment by mhlakhani** [comment]
@raza15 this PR has many commits, and is a super set of your other PR. Over here you just want one commit with just the changes to the makefile.

**Comment by raza15** [comment]
@mhlakhani yeah i also thought so. So what should i do? Create a fresh clone?

**Comment by mhlakhani** [comment]
For reference, there are a few ways of approaching a pull request and editing them: http://stackoverflow.com/questions/7947322/preferred-github-workflow-for-updating-a-pull-request-after-code-review

Ideally, the recommended approach is to have separate branches in your local git repo for each PR. I'm assuming you were using just one repo which caused this issue. 

One way to fix this would be to pull the latest commits in from master, rebase the commits you have changing the Makefile on to master and resubmitting the pull request with just those commits. That would be a great practice exercise, but if you get stuck it might be easier to submit a fresh PR from a fresh repo clone.

**Comment by raza15** [comment]
New PR created #2016. Closing this.

**Pull request closed without merging**
