### PR TITLE
Fix dead loop with kSkipAnyCorruptedRecords mode selected in some cases (#11955)

### PR DESCRIPTION
**Pull request by qiuchengxuan**
Summary:

With fragmented record span across multiple blocks, if any following blocks corrupted with arbitary data, and intepreted log number less than the current log number, program will fall into infinite loop due to
not skipping buffer leading bytes

Test Plan: existing unit tests

### CODE REVIEW

**Review by jowlyzhang — COMMENTED** [review]
Thank you for finding this issue and the fix. Just curious, how did you notice this issue in the first place?

**Review by jowlyzhang — APPROVED** [review]

**Comment by jowlyzhang** [comment]
Would you mind run `make format` and rebase, thanks!

**Comment by qiuchengxuan** [comment]
> Thank you for finding this issue and the fix. Just curious, how did you notice this issue in the first place?

Partially memtioned in issue

We have a ceph cluster and several days ago encountered a power cut, therefore a lot OSDs refuses to start.
After investigation we figure out it's due to data corruption, which mentioned in this [issue](https://tracker.ceph.com/issues/63239). The only thing we can do is to salvage as much data as we could so we use this mode to start ceph OSD, and encountered this issue.

**Comment by qiuchengxuan** [comment]
> Would you mind run `make format` and rebase, thanks!

Done

**Pull request closed without merging**
