### PR TITLE
ErrorExit if num<1000 for fillsync and fill100K

### PR DESCRIPTION
**Pull request by thatsafunnyname**
This is to avoid an exception and core dump when running
  db_bench -benchmarks fillsync -num 999
https://github.com/facebook/rocksdb/issues/8390

### CODE REVIEW

**Review by mrambacher — APPROVED** [review]
This works, but is there a reason not to say have num_ be a minimum of 1?

This is already kind of screwy, in that if num=1001, it goes to 1.  I wonder if it might be better to have num_ = (num_+999)/1000

**Comment by thatsafunnyname** [comment]
>> This works, but is there a reason not to say have num_ be a minimum of 1?

Maybe to avoid a change in behaviour?
 
Maybe the error could help point the user to the N/1000 behaviour of these two benchmarks, so if using ```-num 10``` the user may not notice 1 and not 10 keys were written?  But I suppose the same could be said for ```-num 1001```.
 
I think this is less of a change in behaviour compared to ```num_ = (num_+999)/1000```:

```
<< "\tfillsync      -- write N/1000 values in random key order in "
>> "\tfillsync      -- write max(1, N/1000) values in random key order in "

<< "\tfill100K      -- write N/1000 100K values in random order in"
>> "\tfill100K      -- write max(1, N/1000) 100K values in random order in"

<< num_ /= 1000;
>> num_ = (num_ >= 1000) ? (num_ / 1000) : 1;
```

Maybe this is better?

**Comment by mrambacher** [comment]
> > > This works, but is there a reason not to say have num_ be a minimum of 1?
> 
> Maybe to avoid a change in behaviour?
> 
> Maybe the error could help point the user to the N/1000 behaviour of these two benchmarks, so if using `-num 10` the user may not notice 1 and not 10 keys were written? But I suppose the same could be said for `-num 1001`.
> 
> I think this is less of a change in behaviour compared to `num_ = (num_+999)/1000`:
> 
> ```
> << "\tfillsync      -- write N/1000 values in random key order in "
> >> "\tfillsync      -- write max(1, N/1000) values in random key order in "
> 
> << "\tfill100K      -- write N/1000 100K values in random order in"
> >> "\tfill100K      -- write max(1, N/1000) 100K values in random order in"
> 
> << num_ /= 1000;
> >> num_ = (num_ >= 1000) ? (num_ / 1000) : 1;
> ```
> 
> Maybe this is better?

Yes, I think that is better.  Thanks!

**Comment by thatsafunnyname** [comment]
I now do not like how using ```-num 0``` results in 1 operation.  Thinking about a better fix for this.

**Comment by thatsafunnyname** [comment]
@mrambacher , I ended up adding a guard to the ```while``` loop in ```DoWrite``` on if the number of keys used in the key gens is zero.
This avoids the crash without a change in behaviour.

**Comment by siying** [comment]
@mrambacher do you plan to merge the code?

**Comment by mrambacher** [comment]
@siying Can you please accept it so I can merge it?

**Pull request closed without merging**
