### PR TITLE
replace shell call with a file based detection + user opt in/out 

### PR DESCRIPTION
**Pull request by DRoppelt**
#9956

### CODE REVIEW

**Comment by DRoppelt** [comment]
I have no idea how to add a test that could cover this part.

I have however verified it manually on an alpine and ubuntu image of adoptium

Alpine
```
➜  rocksdb git:(main) ✗ docker run -it --entrypoint sh eclipse-temurin:17.0.3_7-jdk-alpine
/ # jshell
May 10, 2022 8:03:23 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
|  Welcome to JShell -- Version 17.0.3
|  For an introduction type: /help intro

jshell> boolean resolveIsMuslLibc() {
   ...>     File[] allFilesInLib = new File("/lib/").listFiles();
   ...>     if(allFilesInLib == null) return false;
   ...>     for(File f : allFilesInLib) {
   ...>       if(f.getPath().startsWith("/lib/libc.musl")) return true;
   ...>     }
   ...>     return false;
   ...>   }
|  created method resolveIsMuslLibc()

jshell> resolveIsMuslLibc()
$2 ==> true

jshell>

```

Ubuntu

```
➜  rocksdb git:(main) ✗ docker run -it --entrypoint sh eclipse-temurin:17.0.3_7-jdk
# jshell
May 10, 2022 7:23:08 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
|  Welcome to JShell -- Version 17.0.3
|  For an introduction type: /help intro
jshell> boolean resolveIsMuslLibc() {
   ...>     File[] allFilesInLib = new File("/lib/").listFiles();
   ...>     if(allFilesInLib == null) return false;
   ...>     for(File f : allFilesInLib) {
   ...>       if(f.getPath().startsWith("/lib/libc.musl")) return true;
   ...>     }
   ...>     return false;
   ...>   }
|  created method resolveIsMuslLibc()

jshell> resolveIsMuslLibc()
$6 ==> false
```

**Comment by riversand963** [comment]
Hi @adamretter, could you take a look at this sometime?

**Comment by adamretter** [comment]
@DRoppelt I created a new PR which incorporates your work and extends it here - https://github.com/facebook/rocksdb/pull/10889

**Comment by DRoppelt** [comment]
@adamretter LGTM, thank you. For *my* usecase I would like to see the filebased approach first but I understand that preserving the previous behavior is more important. In a security rescricted env, a failed call to shell might still be flagged. But I can opt-out via the env-var so all good for me 👍

**Pull request closed without merging**
