### PR TITLE
[internal] Parallelize sandcastle tests

### PR DESCRIPTION
**Pull request by jay-zhuang**
Summary: Some tests are timeout, increase the parallelism

Test Plan: https://www.internalfb.com/intern/sandcastle/group/nonce/666666/

### CODE REVIEW

**Review by riversand963 — APPROVED** [review]

**Review by pdillinger — CHANGES_REQUESTED** [review]
I'm concerned that test output is no longer dumped to console, making it much harder to retrieve (if it's available at all)

**Comment by jay-zhuang** [comment]
> I'm concerned that test output is no longer dumped to console, making it much harder to retrieve (if it's available at all)

that's true, let me see if we could output that to console, or upload the test result at the end.

**Comment by pdillinger** [comment]
It looks like setting PRINT_PARALLEL_OUTPUTS=1 in the make call would suffice. Stdout and Stderr are in the output, though I suspect there will be interleaving of output in cases.

**Comment by pdillinger** [comment]
Fixed (hopefully) in #9178 based on this one

**Pull request closed without merging**
