### PR TITLE
Remove orphaned Java classes

### PR DESCRIPTION
**Pull request by adamretter**
Remove orphaned Java classes that were missed from commit 9385fd7
Closes https://github.com/facebook/rocksdb/issues/2210

### CODE REVIEW

**Comment by maysamyabandeh** [comment]
@adamretter Should we also remove BackupableDB from CMakeLists.txt as well as from the comments?
```
$ git grep "\<BackupableDB\>"  | grep -v BackupableDB.java | grep -v BackupInfo.java | grep -v BackupableDBOptions.java | grep -v HISTORY | grep -v docs
include/rocksdb/utilities/backupable_db.h:  // next time you create BackupableDB or RestoreBackupableDB.
java/CMakeLists.txt:        org.rocksdb.BackupableDB
java/rocksjni/backupablejni.cc:// calling c++ rocksdb::BackupableDB and rocksdb::BackupableDBOptions methods
java/rocksjni/env_options.cc:// calling c++ rocksdb::BackupableDB and rocksdb::BackupableDBOptions methods
java/rocksjni/external_sst_file_info.cc:// calling c++ rocksdb::BackupableDB and rocksdb::BackupableDBOptions methods
java/rocksjni/sst_file_writerjni.cc:// calling c++ rocksdb::BackupableDB and rocksdb::BackupableDBOptions methods
utilities/backupable/backupable_db_test.cc:  DummyDB* dummy_db_; // BackupableDB owns dummy_db_
utilities/backupable/backupable_db_test.cc:  fprintf(stderr, "SKIPPED as BackupableDB is not supported in ROCKSDB_LITE\n");
```

**Comment by adamretter** [comment]
@maysamyabandeh Good point. I have updated the PR so those are removed from RocksJava now.

**Comment by maysamyabandeh** [comment]
Thanks @adamretter Should we also update these three cases?
```
include/rocksdb/utilities/backupable_db.h:  // next time you create BackupableDB or RestoreBackupableDB.
utilities/backupable/backupable_db_test.cc:  DummyDB* dummy_db_; // BackupableDB owns dummy_db_
utilities/backupable/backupable_db_test.cc:  fprintf(stderr, "SKIPPED as BackupableDB is not supported in ROCKSDB_LITE\n");
```

**Comment by adamretter** [comment]
@maysamyabandeh I intentionally left those as they are outside of RocksJava and I did not want to correct something where I was not 100% sure of the intention.

**Comment by maysamyabandeh** [comment]
Unfortunately target-determinator-buck does not pass. There has been a new change in our test infra that requires updating the TARGET file when files are removed/added and I am guessing that is the problem.  Can you run "python ./buckifier/buckify_rocksdb.py" and update the PR with changes?

**Comment by sagar0** [comment]
@maysamyabandeh I believe target-determinator-buck issue is unrelated. I too ran into it multiple times today morning, and just doing a rebase/re-run helped. So, here, may be a re-import is all that might be needed.

**Pull request closed without merging**
