### PR TITLE
Fix Plumbing WriteBufferManager through JNI

### PR DESCRIPTION
**Pull request by jbhati**
Building fixes identified on top of https://github.com/facebook/rocksdb/pull/4492

### CODE REVIEW

**Comment by jbhati** [comment]
@sagar0 Submitting some fixes on my last PR. Thanks in advance :)

**Comment by benclay** [comment]
@jbhati this needs to be rebased on master, it also contains the already-merged changes in https://github.com/facebook/rocksdb/pull/4492

**Comment by jbhati** [comment]
Yeah, right! Missed that. Will fix it. Thanks

**Comment by jbhati** [comment]
Having trouble getting this branch cleaned up, will resubmit as a different PR

**Comment by jbhati** [comment]
submitted a new PR https://github.com/facebook/rocksdb/pull/4579 instead

**Pull request closed without merging**
