### PR TITLE
Fix various small build issues

### PR DESCRIPTION
**Pull request by adamretter**
* Compatibility with older GCC.
* Compatibility with older jemalloc libraries.
* Remove Docker warning when building i686 binaries.

### CODE REVIEW

**Comment by pdillinger** [comment]
Failure in testAllCallbacksInvocation(org.rocksdb.EventListenerTest) that is not present in master and repeated on re-run

**Comment by pdillinger** [comment]
Now there's a breaking Java API change. That should be mentioned in PR description (to be commit message) and HISTORY.md.

**Comment by adamretter** [comment]
@pdillinger Sorry which API change do you refer to and in which release was it established?

**Comment by pdillinger** [comment]
> @pdillinger Sorry which API change do you refer to and in which release was it established?

https://github.com/facebook/rocksdb/pull/7776/commits/71ea824338959f04e05ed72b4edc88a254c35c43#diff-3e3d56fb4fc4f8b7bcad6defca457c3694f0e2231c0d8d627b2a06f0ab3fd6ec

**Comment by adamretter** [comment]
@pdillinger As far as I can see the last release was 6.14.6 and that wasn't in there - https://github.com/facebook/rocksdb/tree/v6.14.6/java/src/main/java/org/rocksdb/

So how can it be an API change if it was never released before?

**Comment by pdillinger** [comment]
This PR includes an API change by changing case of Java method names in *EventListener.java

**Comment by adamretter** [comment]
> This PR includes an API change by changing case of Java method names in *EventListener.java

I understand that. However, my point was that that API and code had never been released before. So is it really an API change that needs documenting with respect to users of RocksDB. As the users cannot have used it before, IMHO it would rather seem like a new API that is about to be released for the first time.

**Comment by pdillinger** [comment]
https://github.com/facebook/rocksdb/blob/6.15.fb/java/src/main/java/org/rocksdb/AbstractEventListener.java#L268

6.16 is current development (for the next ~day)

**Pull request closed without merging**
