### PR TITLE
only change the date once when the build-directory is created

### PR DESCRIPTION
**Pull request by dothebart**
This can save you re-compile / re-link cycles when using rocksdb.

### CODE REVIEW

**Comment by sagar0** [comment]
@dothebart Could you explain more about what you are trying to achieve with this PR, as I don't understand it. I don't see ROCKSDB_WINDOWS_UTF8_FILENAMES used anywhere.

**Comment by riversand963** [comment]
@sagar0 I think it's introduced in #4469 . I think these two PRs should be combined.

**Comment by dothebart** [comment]
oh you're right. this wasn't the change I meant to create a pr from. sorry for wasting your time.

**Comment by sagar0** [comment]
Closing this one, as #4469 is the correct PR to look at.

**Pull request closed without merging**
