### PR TITLE
Configurate ccache in CMakeLists.txt to speed up compilation

### PR DESCRIPTION
**Pull request by qinzuoyan**

### CODE REVIEW

**Comment by siying** [comment]
Can some one is interested in reviewing it? CC @burtonli @tchaikov @huachaohuang

**Comment by tchaikov** [comment]
@qinzuoyan could you fix the typo in the commit message, remove the merge commit, and then repush your branch?

**Comment by qinzuoyan** [comment]
@tchaikov @siying , new pull request has been pushed as https://github.com/facebook/rocksdb/pull/5388

**Comment by tchaikov** [comment]
@qinzuoyan JFYI, next time, you could just use `git push -f` for pushing your change to your `qinzuoyan1` branch for updating an existing PR.

**Comment by qinzuoyan** [comment]
@tchaikov ok, thanks.

**Comment by sagar0** [comment]
Closing, as this has been taken care of in #5388 .

**Pull request closed without merging**
