### PR TITLE
Remove function local statics that interfere with memory pooling

### PR DESCRIPTION
**Pull request by yuslepukhin**

### CODE REVIEW

**Comment by yiwu-arbug** [comment]
LGTM. Can you explain a little bit why the change is needed?

**Comment by yuslepukhin** [comment]
@yiwu-arbug when different instances of the database live in separate memory pools then function local statics area allocated from a pool that is associated with that instances. When instance goes away so is the memory pool and then a global object is left hanging in the air. globals do not have that problem.

**Comment by yiwu-arbug** [comment]
Thank you! Will merge after contbuild finishes.

**Comment by yuslepukhin** [comment]
@yiwu-arbug Just wondering if Tavis is in fact doing anything

**Comment by yiwu-arbug** [comment]
@yuslepukhin seems Travis is having trouble. Let me merge anyway since AppVeyor build passes.

**Pull request merged**
