### PR TITLE
Address MS Visual Studio 2017 issue with autovector

### PR DESCRIPTION
**Pull request by yuslepukhin**
This addresses https://github.com/facebook/rocksdb/issues/2262

### CODE REVIEW

**Comment by yuslepukhin** [comment]
@siying Seems there is not an AppVeyor build

**Comment by yiwu-arbug** [comment]
Asking internally.

**Comment by yiwu-arbug** [comment]
@yuslepukhin Mind rebase and see if AppVeyor can be triggered? Thanks.

**Comment by yuslepukhin** [comment]
@IslamAbdelRahman Failures not related

**Comment by yiwu-arbug** [comment]
Merging.

**Pull request closed without merging**
