### PR TITLE
approximate histogram stats to save cpu

### PR DESCRIPTION
**Pull request by ajkr**
sounds like we're willing to tradeoff minor inaccuracy in stats for speed. start with histogram stats. ticker stats will be harder (and, IMO, we shouldn't change them in this manner) as many test cases rely on them being exactly correct.

Test Plan:

command:

```
TEST_TMPDIR=/dev/shm perf record -g ./db_bench -num=5000000 -benchmarks=readwhilewriting -threads=16 -statistics
```

before:

```
+    1.87%     1.86%  db_bench     db_bench             [.] rocksdb::HistogramStat::Add
```

after:

```
+    0.61%     0.61%  db_bench     db_bench             [.] rocksdb::HistogramStat::Add
```

### CODE REVIEW

**Comment by ajkr** [comment]
Yeah I was also wondering why we write a loop to set `min`, when it still doesn't guarantee we will store the true min after concurrent calls to `Add`.

**Comment by ajkr** [comment]
the CAS should be correct and I expect the conditions under which it executes (`value < old_min` or `value < old_max`) are almost never true. So I'd rather leave it computed correctly if there's no perf benefit.

**Comment by siying** [comment]
@ajkr it makes sense.

**Comment by ajkr** [comment]
Actually I measured it with your suggested changes and it did improve. Idk if it's noise or not.

```
-    0.54%     0.54%  db_bench     db_bench             [.] rocksdb::HistogramStat::Add
```

**Comment by siying** [comment]
@ajkr you can look at the asm and see what can be the reason. Maybe it makes things better inlined, or maybe it makes the icache miss lower. Or maybe it's just noise.

**Comment by ajkr** [comment]
@siying couldn't tell easily. seems there's an optimization where the arguments for `compare_exchange_weak` are pushed to the stack even when it won't be called. perf attributes 7-10% of `HistogramStat::Add` CPU to these `mov` instructions.

**Comment by siying** [comment]
@ajkr good investigation

**Pull request closed without merging**
