### PR TITLE
Delete .deprecated_arcconfig

### PR DESCRIPTION
**Pull request by IslamAbdelRahman**

### CODE REVIEW

**Comment by zpao** [comment]
Do you want to remove `arcanist_util/` as well?

**Comment by ajkr** [comment]
btw, @IslamAbdelRahman, how do you run `arc lint` these days? mine depended on `.arcconfig` and `arcanist_util/`.

**Comment by IslamAbdelRahman** [comment]
@ajkr, I forgot about `arc lint` .. there is no way to run it, but I assume that the imported diff have the lint errors I assume

**Comment by siying** [comment]
@ajkr good point. I don't run `arc lint`. I run `make format`. I don't know whether it covers too little.

**Comment by ajkr** [comment]
Thanks, @siying, didn't know about `make format`.

**Comment by yiwu-arbug** [comment]
@IslamAbdelRahman Is it safe the land this one?

**Pull request closed without merging**
