### PR TITLE
RocksJava: Add the missing FIFO compaction options

### PR DESCRIPTION
**Pull request by sagar0**
Make CompactionOptionsFIFO's ttl and allow_compaction options to be available in RocksJava.

Test Plan:
New tests.

### CODE REVIEW

**Comment by sagar0** [comment]
@adamretter ping!

**Comment by Dealus** [comment]
Hello,
Why wasn't this merged ? The TTL option is missing hard

**Comment by adamretter** [comment]
@Dealus they were merged, just not through GitHub - see https://github.com/facebook/rocksdb/commit/0d65315cb14584aada933658674d7cfbd83ea912

**Comment by Dealus** [comment]
Ok found it, but then it was removed as the option disapeared from master.
I feel like the option was moved to another place, but can't figure where

**Pull request closed without merging**
