### PR TITLE
[tools] simplify user_access_only expression

### PR DESCRIPTION
**Pull request by gaurav1086**

### CODE REVIEW

**Comment by riversand963** [comment]
Sorry @gaurav1086 I forgot to merge this. Could you rebase onto latest master? Thanks

**Comment by gaurav1086** [comment]
@riversand963 np. sure, will do. thanks.

**Comment by gaurav1086** [comment]
@riversand963 , its done. Thank you.

**Comment by riversand963** [comment]
@gaurav1086 , thanks for working on this. It has been merged.

**Pull request closed without merging**
