### PR TITLE
jni: uniformly use GetByteArrayRegion() to copy bytes

### PR DESCRIPTION
**Pull request by javeme**
Uniformly use GetByteArrayRegion() instead of GetByteArrayElements()
to copy bytes.
In addition, it can avoid an inefficient ReleaseByteArrayElements()
operation.
Some benefits of GetByteArrayRegion() can be referred to:
https://stackoverflow.com/a/2480493

### CODE REVIEW

**Comment by javeme** [comment]
I tested with rocksdb v7.0.0(debug mode) and found that the performance of are almost the same, seek() 100000000 times cost about 64s.

GetByteArrayElements Flame Graph:
image

GetByteArrayRegion Flame Graph:
image


> I can only compile the debug version rocksdb in my mac environment.

> I looked at the benchmark code and found that it is mainly write tests. Is there a guide for read tests?
https://github.com/facebook/rocksdb/blob/main/java/benchmark/src/main/java/org/rocksdb/benchmark/DbBenchmark.java#L904

**Comment by adamretter** [comment]
@alanpaxton As you were looking at the benchmarks not so long ago, would you be able to comment on this?

**Comment by alanpaxton** [comment]
I definitely approve the principle @adamretter @javeme - To quote from my benchmarking report "GetElements methods for transferring data from C++ to Java are consistently less efficient than other methods." and "SetRegion and GetCritical mechanisms for copying data into a byte[] are of very comparable performance; presumably the behaviour behind the scenes of SetRegion is very similar to that of declaring a critical region, doing a memcpy() and releasing the critical region."

The report is DataBenchmarks.md in https://github.com/alanpaxton/jni-benchmarks

**Comment by javeme** [comment]
@alanpaxton Thank you for the detailed report [Data Transfer Benchmarks](https://github.com/alanpaxton/jni-benchmarks/blob/main/DataBenchmarks.md), The performance comparison is very good and can be used as a reference for jni programming.

**Comment by adamretter** [comment]
Thanks @alanpaxton  :-)
@jay-zhuang could we get this merged please?

**Comment by javeme** [comment]
@adamretter Thank you.
@jay-zhuang Kindly ping~

**Pull request closed without merging**
