### PR TITLE
[DNM] Cache: Expose usage/capacity for high priority pool.

### PR DESCRIPTION
**Pull request by markhpc**
This is a rebased version of #3732 and is what we are using for testing high priority cache prioritization in Ceph.

### CODE REVIEW

**Comment by yiwu-arbug** [comment]
@markhpc BTW you might be interested in some of the cache improvement I'm working on, including #3877.

**Comment by markhpc** [comment]
@yiwu-arbug Very nice!  The idea with your PR being that writes shouldn't be promoted to the front of the cache until you actually see a read?  That seems quite reasonable.

FWIW, I am also planning to implement an age-binned counter scheme, ie how many cache items are under 5s, 30s, 5m, 1h, etc, old.  I've already done this in an experimental ceph branch for our own LRU and 2Q caches:
https://github.com/markhpc/ceph/commit/1eaebf64a06d30465af1c7a9990598adabcbb8d7

This let's us adjust cache sizes based on a prioritization scheme, IE if rocksdb has a lot of hot items in the block cache or row cache, we can give it a larger portion of our pool of available memory, but if those items are old relative to other caches (like our internal metadata or data caches) we can shift memory in that direction.

**Comment by ltamasi** [comment]
@markhpc Based on your latest comment, I'm assuming this PR is no longer needed; would you be OK with closing it?

**Comment by markhpc** [comment]
@ltamasi Oh my, I forgot this was still open!  We did in fact implement our own version of the LRU cache and have it working with our adaptive priority cache scheme competing against other caches.  We don't need this anymore at all.

Thanks!

**Pull request closed without merging**
