### PR TITLE
Expose all remaining read and write options via the C API

### PR DESCRIPTION
**Pull request by glittershark**
Expose read and write options via the C API

### CODE REVIEW

**Comment by maysamyabandeh** [comment]
Thanks @glittershark. Can you expose all the options that are missing from the C API? It is better to do them all in one shot rather than having a separate PR for each.

**Comment by glittershark** [comment]
Happy to!

**Comment by glittershark** [comment]
@maysamyabandeh Updated to expose all options except `ReadOptions.table_filter`, as I didn't know how you wanted to allow C callers to pass `std::function`s - there's a *little* prior art here with merge operators, but as that's an implemented interface rather than a `std::function` I didn't want to move forward with it unilaterally.

**Comment by glittershark** [comment]
also I should mention this is literally my first time writing C++ so I'm kind of shooting in the dark a little bit

**Pull request closed without merging**
