### PR TITLE
Cherry pick PR 7660 and update HISTORY

### PR DESCRIPTION
**Pull request by cheng-chang**
Cherry picks https://github.com/facebook/rocksdb/pull/7660 and adds new option `track_and_verify_wals_in_manifest`  to HISTORY.

Test Plan:
N/A

### CODE REVIEW

**Comment by cheng-chang** [comment]
should I directly push the cherry picked commit to the 6.15.fb branch?

**Comment by pdillinger** [comment]
> should I directly push the cherry picked commit to the 6.15.fb branch?

Yes, that is how to resolve the PR. However, since CI was complete infrastructure failure, it would be nice to re-trigger, perhaps with a trivial commit --amend and force-push.

**Review by riversand963 — APPROVED** [review]
LGTM if it's just cherry-pick. We usually just push directly to the target branch without going through the landing process.

**Comment by cheng-chang** [comment]
I'll cherry-pick directly to the branch.

**Pull request closed without merging**
