### PR TITLE
Concurrent write operations

### PR DESCRIPTION
**Pull request by guyg8**
Basic concurrent write operations + WAL + snapshots.

### CODE REVIEW

**Comment by siying** [comment]
Let me backport the three previous commits so that your change is clean with just this patch.

**Comment by siying** [comment]
I cherry-picked the two patches you picked. Can you rebase?

**Comment by siying** [comment]
Why close this?

**Comment by guyg8** [comment]
I mistakenly closed this pull request.
Pull request #610 contains the same updates.

**Pull request closed without merging**
