### PR TITLE
Set status to NoSpace when max allowed space was reached

### PR DESCRIPTION
**Pull request by xiaosuo**

### CODE REVIEW

**Comment by yiwu-arbug** [comment]
@xiaosuo Mind rebase to re-trigger travis? Thanks!

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.

**Comment by xiaosuo** [comment]
I will return back later.

**Comment by gfosco** [comment]
Will take care of this in #3531.

**Pull request closed without merging**
