### PR TITLE
RocksDB now requires gflags v2.2.0

### PR DESCRIPTION
**Pull request by adamretter**

### CODE REVIEW

**Comment by chencang1980** [comment]
maybe 2.2.0 is least for work, and shared library wanted

for build gflags from source
```
mkdir cmake-build-release/
cd cmake-build-release/
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=1 ..
cmake --build .
cmake --install .
```


https://github.com/gflags/gflags/commit/eaf05340dc9e5367fdd43a9eea0c39a0aec44f16

**Comment by adamretter** [comment]
@chencang1980 I just tested and it appears that 2.2.0 works fine as well, so I have updated this PR.

**Comment by adamretter** [comment]
@anand1976 rebased and once again ready for review/import.

**Comment by adamretter** [comment]
@anand1976 rebased and once again ready for review/import.

**Review by jowlyzhang — APPROVED** [review]
LGTM, thank you for the change! Can you try rebase and kick off the CI tests again, Thanks!

**Comment by adamretter** [comment]
@jowlyzhang that is now rebased again, thanks.

**Comment by adamretter** [comment]
@jowlyzhang Looks like a compilation issue with Snappy 1.10, I have rolled back to 1.1.9.

**Pull request closed without merging**
