### PR TITLE
Change GTEST_SKIP to BYPASS for MemoryAllocatorTest

### PR DESCRIPTION
**Pull request by mrambacher**

### CODE REVIEW

**Comment by riversand963** [comment]
Thanks @mrambacher for the PR. Can you import it to phabricator?

**Review by riversand963 — APPROVED** [review]

**Comment by pdillinger** [comment]
Let's look at the API comments

```
// A "skipped" test has a specific meaning in Facebook infrastructure: the
// test is in good shape and should be run, but something about the
// compilation or execution environment means the test cannot be run.
// Specifically, there is a hole in intended testing if any
// parameterization of a test (e.g. Foo/FooTest.Bar/42) is skipped for all
// tested build configurations/platforms/etc.
```

This sounds exactly appropriate for skipping an entire test when some feature is not compiled in.

> I haven't tried ROCKSDB_GTEST_BYPASS, but it's being used in external_sst_file_basic_test, thus looks promising.

Could that be related?

```
TEST_P(ExternalSSTFileBasicTest, IngestExternalFileWithCorruptedPropsBlock) {
  bool verify_checksums_before_ingest = std::get<1>(GetParam());
  if (!verify_checksums_before_ingest) {
    ROCKSDB_GTEST_BYPASS("Bypassing test when !verify_checksums_before_ingest");
    return;
  }
  ...
```

No it's not. This snippet is excluding some instantiations. The test is run regardless of the compilation/execution environment. This approach is simpler than creating another version of ExternalSSTFileBasicTest with the specific subset of instantiations we want. This `IngestExternalFile...` case is consistent with the documented recommended use of bypass, while `MemoryAllocatorTest` is not.

```
// We add "bypass" as an alternative to ROCKSDB_GTEST_SKIP that is allowed to
// be a permanent condition, e.g. for intentionally omitting or disabling some
// parameterizations for some tests. (Use _DISABLED at the end of the test
// name to disable an entire test.)
```

**Comment by pdillinger** [comment]
It looks like the test was reported as skipping continuously for TSAN build (and likely also would on ASAN, UBSAN where we disable jemalloc, at least in Makefile build). It's unfortunate that not skipping in regular build is not considered sufficient.

This change as-is encourages copied misuse of BYPASS because there's no clarification on why BYPASS is used rather than SKIP where SKIP is the recommended choice. Given the infrastructure quirk, we would ideally only BYPASS for sanitizer builds, but also OK with a clarifying comment that the test would be reported as always skipped because sanitizer builds do not use jemalloc.

**Comment by mrambacher** [comment]
@pdillinger @riversand963 I had it as SKIP and changed it to BYPASS on request to not aggravate the FB infrastructure.  If it should be SKIP instead, are you requesting this PR be rolled back or another submitted?  And how do we get out of the loop of change SKIP to BYPASS to SKIP?

**Comment by pdillinger** [comment]
I took "Our internal infra reports this as warning which is a mixed signal" (https://github.com/facebook/rocksdb/pull/8980#discussion_r776017606) as a hypothetical based on experience, or if actual, then probably a "true positive" report that the test was not ever being run as intended. The missing context was that it was effectively a false report, because the test is being run as intended in the non-sanitizer builds.

**Comment by pdillinger** [comment]
I can post a PR with recommended clarifying comment. Sorry for the alarm.

**Pull request closed without merging**
