### PR TITLE
[RocksJava] ColumnFamily name JNI correction

### PR DESCRIPTION
**Pull request by fyrz**
Previous to this commit there was a problem with unterminated
String usage as jByteArrays are not zero terminated.

Differential: https://reviews.facebook.net/D31809

### CODE REVIEW

**Comment by fyrz** [comment]
@yhchiang can you look into this ?

**Comment by yhchiang** [comment]
I want to review it more carefully, can you create a diff review for this?

**Comment by fyrz** [comment]
@yhchiang i added the differential to the pull request description and integrated your comments.

**Comment by yhchiang** [comment]
Sorry for the delay, I will review it sometime later today.

**Comment by yhchiang** [comment]
Hey @fryz.  I left a comment under the diff.  Once the issue has been fixed it's ready to go :)

**Pull request merged**
