### PR TITLE
move static msgs out of Status class

### LINKED ISSUE #3831: Move static_msgs out of Status class
People are getting confused by 'static_msgs' whenever they dump a Status object.  We should consider moving this field outside of Status class so that it doesn't get dumped.

`static const char* msgs[static_cast<int>(kMaxSubCode)];
`
Example:
```
(gdb) p s
$1 = {code_ = rocksdb::Status::kOk, subcode_ = rocksdb::Status::kNone, state_ = 0x0, static msgs = {0x9eee15 "", 0x9f7b14 "Timeout Acquiring Mutex",
    0x9f7b2c "Timeout waiting to lock key", 0x9e2e40 "Failed to acquire lock due to max_num_locks limit", 0x9f7b48 "No space left on device", 0x9f7b60 "Deadlock",
    0x9f7b69 "Stale file handle", 0x9f7b7b "Memory limit reached"}}
```

### PR DESCRIPTION
**Pull request by Maxosc**
Summary:
The member msgs of class Status contains all types of status messages.
When users dump a Status object, msgs will confuse users. So move it out
of class Status by making it as file-local static variable.

Closes #3831 .

Test Plan:
- Compile on Linux and Windows platform
- Verified via gdb

### CODE REVIEW

**Comment by Maxosc** [comment]
It is interesting that my change breaks the build since it doesn't contain any logic change and just some refactoring here. Is there a way I can investigate that build failure? I try to re-run the test locally, but cannot reproduce the failure.

**Comment by sagar0** [comment]
The failure is due to: #4151 . I restarted the failing Travis job for you for now.

**Comment by sagar0** [comment]
Verified that this works.

Setup:
```
~/rocksdb (status-msgs) $ TEST_TMPDIR=/dev/shm gdb ./db_flush_test
(gdb) set args --gtest_filter=DBFlushTest.SyncFail
(gdb) br rocksdb::DBImpl::Flush
(gdb) i br
Num     Type           Disp Enb Address            What
1       breakpoint     keep y   0x00000000005ac3d9 in rocksdb::DBImpl::Flush(rocksdb::FlushOptions const&, rocksdb::ColumnFamilyHandle*) at db/db_impl_compaction_flush.cc:935
(gdb) run
...
Thread 1 "db_flush_test" hit Breakpoint 1, rocksdb::DBImpl::Flush (this=this@entry=0x7ffff59ee000, flush_options=..., column_family=0x7ffff59aefe0)
    at db/db_impl_compaction_flush.cc:935
935       ROCKS_LOG_INFO(immutable_db_options_.info_log, "[%s] Manual flush start.",
(gdb) until 939
rocksdb::DBImpl::Flush (this=this@entry=0x7ffff59ee000, flush_options=..., column_family=0x7ffff59aefe0) at db/db_impl_compaction_flush.cc:939
939       ROCKS_LOG_INFO(immutable_db_options_.info_log,
```
Before:
```
(gdb) p s
$2 = {code_ = rocksdb::Status::kOk, subcode_ = rocksdb::Status::kNone, sev_ = rocksdb::Status::kNoError, state_ = 0x0, static msgs = {0xa23165 "",
    0xa2c739 "Timeout Acquiring Mutex", 0xa2c751 "Timeout waiting to lock key", 0xa4a148 "Failed to acquire lock due to max_num_locks limit", 0xa240b1 "No space left on device",
    0xa2c76d "Deadlock", 0xa2c776 "Stale file handle", 0xa2c788 "Memory limit reached", 0xa2c79d "Space limit reached"}}
```
After:
```
(gdb) p s
$1 = {code_ = rocksdb::Status::kOk, subcode_ = rocksdb::Status::kNone, sev_ = rocksdb::Status::kNoError, state_ = 0x0}
```

**Comment by sagar0** [comment]
`DBTest2.CompactionStall` test is hanging with this fix when run on our internal test infra; the test hung a few times so far. I am looking into it.

**Comment by sagar0** [comment]
Subsequent runs of the test succeeded.

**Pull request closed without merging**
