### PR TITLE
Enable multiread_batched for benchmark.sh

### LINKED ISSUE #9907: Multireadrandom in benchmark.sh doesn't use batched MultiGet
https://github.com/facebook/rocksdb/blob/3653029dda238692564773552c55cc29fea10310/tools/db_bench_tool.cc#L1548
https://github.com/facebook/rocksdb/blob/3653029dda238692564773552c55cc29fea10310/tools/benchmark.sh#L521
https://github.com/facebook/rocksdb/blob/3653029dda238692564773552c55cc29fea10310/include/rocksdb/db.h#L586
https://github.com/facebook/rocksdb/wiki/Performance-Benchmarks#test-3-multi-random-read-benchmarksh-multireadrandom

Fortunately, regression_test.sh does use batched MultiGet:
https://github.com/facebook/rocksdb/blob/3653029dda238692564773552c55cc29fea10310/tools/regression_test.sh#L249

### PR DESCRIPTION
**Pull request by lhsoft**
Fixes #9907

### CODE REVIEW

**Review by ajkr — APPROVED** [review]
LGTM. cc @mdcallag as this might cause a visible change.

**Comment by mdcallag** [comment]
> LGTM. cc @mdcallag as this might cause a visible change.

Thanks for the notice. This was needed, although I will tweak this so I can disable it when I test older versions as this first arrived in 6.2.

Also, I didn't know until recently that this also was sufficient:
benchmark.sh multireadrandom --multiread_batched=true

**Comment by lhsoft** [comment]
@mdcallag thanks for your comments. `benchmark.sh multireadrandom --multiread_batched=true` is sufficient. 
@ajkr I think we can close this PR and the related issue.  Because the command above is sufficient.

**Comment by ajkr** [comment]
Closing per author ("there is no need to change the benchmark.sh")

**Pull request closed without merging**
