### PR TITLE
LRUCacheShard cache line size alignment

### PR DESCRIPTION
**Pull request by grooverdan**
combining #2568 and #2612.

### CODE REVIEW

**Comment by grooverdan** [comment]
mingw32 failure - https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52991

**Comment by IslamAbdelRahman** [comment]
Thanks @grooverdan, How can we suppress the MinGW failure .. we don't want our travis failure to consistently fail

**Comment by grooverdan** [comment]
I tried just adding -mno-ms-bitfields on the mingw32 however this wasn't sufficient https://travis-ci.org/grooverdan/rocksdb/jobs/255882007

So as per next commit just disabling alignment for mingw32

**Comment by grooverdan** [comment]
Thanks for the initial work and merging.

**Comment by yiwu-arbug** [comment]
Seems this still doesn't properly align LRUCacheShard, as shown by running tests with UBSAN: https://gist.github.com/yiwu-arbug/401217b8868be158a545f85220785e17

I guess it is because we allocate `shard_` as an array, which short-circuit the overloaded new operator.

**Pull request closed without merging**
