### PR TITLE
port: updated PhysicalCoreID()

### PR DESCRIPTION
**Pull request by joscollin**
Summary:
Updated PhysicalCoreID() to use sched_getcpu() on x86_64 for glibc >= 2.22.  Added a new
function named GetCPUID() that calls sched_getcpu(), to avoid repeated code. This change is done as per the comments of PR: https://github.com/facebook/rocksdb/pull/2230

Signed-off-by: Jos Collin <jcollin@redhat.com>

### CODE REVIEW

**Comment by ajkr** [comment]
By the way, I profiled this code and it makes GetPhysicalCore() 10x faster, as the comment originally suggested. This is really useful now as I'm working on core-local stats, which will make *a lot* of calls to GetPhysicalCore(). Thanks for your contribution!

**Comment by joscollin** [comment]
@ajkr I'm happy to know that this PR makes performance improvements. 

> can you change it to __GNUC_MINOR__ >= 22? I didn't get why not support 2.22.0 

Sorry, that was a mistake from my side. I meant to include 2.22.0. Thanks for catching it.

> (and also __GNUC_PATCHLEVEL__ seems only defined in glibc 3+)

Are you suggesting me to avoid __GNUC_PATCHLEVEL__ completely ? 

Like this:
```
#if defined(__x86_64__) && (__GNUC__ > 2 || (__GNUC__ == 2 && __GNUC_MINOR__ >= 22))
```

**Comment by ajkr** [comment]
yup your proposed change looks good!

**Comment by joscollin** [comment]
@ajkr Thanks for the approval. I hope we don't have to check for GNUC_PATCHLEVEL for glibc 3+ separately.

Also, I wonder why those functions are not inside a class ? Just like C-Style code ?

**Comment by ajkr** [comment]
shouldn't need to check patch level because everything in 3+ should have the proper support.

not sure why no class. I'd guess because they don't need to own/operate on any data so there's not much benefit to a class (besides namespacing).

**Comment by joscollin** [comment]
@ajkr Could you please merge this ? I have a conflict now.

**Comment by ajkr** [comment]
it was merged here: https://github.com/facebook/rocksdb/commit/a62096696928f0280b9195c36b1a6446311b5e7c

**Comment by joscollin** [comment]
@ajkr Usually, the merges are done to the master branch. In this case, The code in the master branch is different. That's the reason I'm getting a merge conflict.
https://github.com/facebook/rocksdb/blob/master/port/port_posix.cc

Please suggest what should I do to get rid of the merge conflict.

Thanks.

**Comment by scv119** [comment]
hmm seems this broke the mac build:  
```
port/port_posix.cc:142:15: error: use of undeclared identifier 'sched_getcpu'
  int cpuno = sched_getcpu();
```

**Comment by sagar0** [comment]
@scv119 mac build is fixed in #2272 , as we discussed.

**Pull request closed without merging**
