### PR TITLE
Fix unused var warnings in Release mode

### PR DESCRIPTION
**Pull request by yuslepukhin**
MSVC does not support unused attribute at this time. A separate assignment line fixes the issue probably by being counted as usage for MSVC and it no longer complains about unused var.

### CODE REVIEW

**Comment by maysamyabandeh** [comment]
1. Can you provide some context of the problem and how separating declaration and assignment is fixing it?
2. Why is that AppVoyer does not complain about this? https://ci.appveyor.com/project/Facebook/rocksdb/branch/master
If the check is not incorporated into our pre-commit builds it is likely to be repeated again.

**Comment by yuslepukhin** [comment]
@maysamyabandeh 1) In my previous commit I have turned on level 4 MSVC warnings since they helped to detect some real issues and moves MSVC build closer to what is enabled in GCC in terms of warnings.
2) MSVC complains about unused variables in the `release` build in cases where the only use of the var happens to be within the assert. For that reason a) it was not detected in the previous PR and b) this is why AppVeyor does not complain about it.

**Comment by maysamyabandeh** [comment]
Thanks. and how separating declaration and assignment is fixing it? That seems counter-intuitive to me.

**Comment by yuslepukhin** [comment]
@maysamyabandeh I agree. I have not received a good answer to this from the internal folks. It seems to me that a separate assignment line counts as `usage` for MSVC and it no longer complains about unused var.

**Pull request closed without merging**
