### PR TITLE
Schedule individual CF for flush when !atomic_flush

### PR DESCRIPTION
**Pull request by riversand963**
If atomic flush is not enabled, then we should schedule a flush request for
each of the column family.

Test plan
```
$make clean && make -j32 all check`
```

### CODE REVIEW

**Comment by riversand963** [comment]
Close for now. May reopen if necessary.

**Comment by riversand963** [comment]
Re-open because we may need to land this.

**Comment by ajkr** [comment]
do we need it?

**Comment by riversand963** [comment]
On second thought, I think we are better off closing it. Thanks @ajkr for pointing out.

**Pull request closed without merging**
