### PR TITLE
Use official CMake snap on Travis Linux

### PR DESCRIPTION
**Pull request by adamretter**
Switch to using the official CMake snap rather than our own from S3.
See https://gitlab.kitware.com/cmake/cmake/-/issues/20122#note_769266

### CODE REVIEW

**Comment by audiofanatic** [comment]
For now you need to add the —beta flag when installing the CMake snap for non-amd64 architectures.

**Comment by audiofanatic** [comment]
The failure for the travis-ci build looks to be explained by the following comment about how PATH is handled by snapd:

https://forum.snapcraft.io/t/build-service-fails-to-use-cmake-from-build-snap/17973/10

Basically, you need to explicitly _prepend_ `/snap/bin` to your PATH.

**Comment by adamretter** [comment]
Thanks @audiofanatic I have prepended /snap/bin now... let's see what happens now.

**Comment by adamretter** [comment]
@pdillinger So can we merge this one?

**Pull request closed without merging**
