### PR TITLE
Fix HyperClockCache Rollback bug in #10801

### PR DESCRIPTION
**Pull request by pdillinger**
Summary: In #10801 in ClockHandleTable::Evict, we saved a reference to the hash value (`const UniqueId64x2& hashed_key`) instead of saving the hash value itself before marking the handle as empty and thus free for use by other threads. This could lead to Rollback seeing the wrong hash value for updating the `displacements` after an entry is removed.

The fix is (like other places) to copy the hash value before it's released. (We could Rollback while we own the entry, but that creates more dependences between atomic updates, because in that case, based on the code, the Rollback writes would have to happen before or after the entry is released by marking empty. By doing the relaxed Rollback after marking empty, there's more opportunity for re-ordering / ILP.)

Intended follow-up: refactoring for better code sharing in clock_cache.cc

Test Plan: watch for clean crash test, TSAN

### CODE REVIEW

**Comment by siying** [comment]
I don't think I'm knowledge enough to review it, without reading all the code. @anand1976 are you the person who is most familiar with the code except @pdillinger ?

**Comment by siying** [comment]
> Summary: In Evict, we saved a reference to the hash value instead of saving the hash value itself. This fixes by generally doing Rollback as soon as an entry is no longer visible to Lookups, so we don't need to copy the value for later passing to Rollback.
Can you explain "we saved a reference to the hash value instead of saving the hash value itself"? Do you mean std::array<uint64_t, 2> is actually a reference?

**Comment by siying** [comment]
Oh "const UniqueId64x2&" is used in one of the places. Still didn't get why it would cause a data race. Can you explain more in the summary?

**Review by siying — APPROVED** [review]

**Review by anand1976 — APPROVED** [review]
LGTM

**Pull request closed without merging**
