### PR TITLE
JNI transactions  is working.

### PR DESCRIPTION
**Pull request by publicocean0**
hi, 
I merged and fixed compilation problems for extending transations in JNI starting from adamretter code. Actually it seams to work correctly

### CODE REVIEW

**Comment by publicocean0** [comment]
the test is failed for no space in test node : /tmp/rocksdbtest-2000/db_test/000550.sst: No space left on device
terminate called after throwing an instance of 'testing::internal::GoogleTestFailureException'
  what():  db/db_test.cc:5103: Failure

**Comment by yiwu-arbug** [comment]
@adamretter Do you mind reviewing the patch?

@publicocean0 The patch is huge. Any chance to split it into smaller pieces?

**Comment by publicocean0** [comment]
there is few files changed , 99% of patch are new files. 
the most important file changed (you can see the added part at the end of file) is portal.h

**Comment by adamretter** [comment]
@yiwu-arbug @publicocean0 I would rather get my original PR merged first as that was a lot of work. After that we can certainly merge any improvements suggested by @publicocean0. The original PR is here - https://github.com/facebook/rocksdb/pull/1298 I will do the work to make sure it is up-to-date on Sun (2018-01-21) / Mon (2018-01-22)

**Comment by publicocean0** [comment]
For me it is not a problem , but if you compare the adamretter version and mime you can see in few minutes the differences. I used meld tool. In this way you can see i have just fix the problems for making it compilable , 99% of code is the same

**Comment by publicocean0** [comment]
A little additional suggestion saw working on it. 
the api in Rocksdb and TransactionalDB/OptimisticTransactionalDB are a bit different... remove instead delete ,.....,or order of parameters different in api. Maybe for making easy to replace a db implementation with another  it is better to align the api.

**Comment by vjnadimpalli** [comment]
@publicocean0 sorry for not being able to merge this in so far. Thanks for the contribution. I wanted to check with you to see if you are ok to rebase and get all tests to pass so we can merge it in?

**Comment by vjnadimpalli** [comment]
@publicocean0 I don't think I get the context of the change? Would you mind providing some details?

**Comment by adamretter** [comment]
@publicocean0 @vjnadimpalli I am closing this one, as I think the changes came in with other already merged PRs. Please let me know if I missed something.

**Pull request closed without merging**
