### PR TITLE
add StartTrace and EndTrace to stackable_db

### PR DESCRIPTION
**Pull request by nmjnmjnmj**
In addition to trace block cache access, we want to support trace queries on MySQL. To achieve that StartTrace and EndTrace need to be added to the stackable_db.h

### CODE REVIEW

**Review by zhichao-cao — APPROVED** [review]
LGTM, thanks!

**Comment by zhichao-cao** [comment]
Please do "make format" before land it.

**Comment by nmjnmjnmj** [comment]
> Please do "make format" before land it.

let you know that currently "make format" is broken on the CentOS 8  https://www.internalfb.com/intern/qa/68160/clang-format-diffpy-broken-on-centos-8,  I have to manually run the clang-format-diff.py

**Comment by zhichao-cao** [comment]
> > Please do "make format" before land it.
> 
> let you know that currently "make format" is broken on the CentOS 8 https://www.internalfb.com/intern/qa/68160/clang-format-diffpy-broken-on-centos-8, I have to manually run the clang-format-diff.py

Yeah, I had the issue before.... You may need to down load the github clang-format-diff.py to RocksDB directory and re-run make format

**Pull request closed without merging**
