### PR TITLE
Add missing mutable DBOptions to RocksJava

### PR DESCRIPTION
**Pull request by adamretter**
As requested in https://github.com/facebook/rocksdb/issues/6127

### CODE REVIEW

**Comment by gaojieliu** [comment]
@pdillinger 
Any plan to cut a new release?
Currently, this issue has blocked us from upgrading to the latest version of RocksDB.

Thanks

**Comment by gaojieliu** [comment]
@pdillinger 
I saw the latest release [v6.5.3](https://github.com/facebook/rocksdb/releases/tag/v6.5.3) doesn't contain this change.
Could you share the plan to include this change in next release anytime soon?

Thanks for your help!

**Comment by gaojieliu** [comment]
@pdillinger 
I saw this change is available in the latest release: [v6.6.4](https://github.com/facebook/rocksdb/releases/tag/v6.6.4).
Could you share when this will be available in maven repository?

Thanks

**Comment by gaojieliu** [comment]
@pdillinger 
Any update? Is there any way we could get involved in this process to make it faster?

Thanks

**Comment by adamretter** [comment]
@gaojieliu apologies I had not seen that v6.6.4 was released. I will try and get the RocksJava release out for that today.

**Comment by gaojieliu** [comment]
Thank you, @adamretter !

**Comment by gaojieliu** [comment]
@adamretter 
I haven't seen the new release in the maven repo:
https://mvnrepository.com/artifact/org.rocksdb/rocksdbjni
I know you are working on it, and do you know how long it will take to show up in maven repo?

Thanks

**Comment by adamretter** [comment]
@gaojieliu https://search.maven.org/artifact/org.rocksdb/rocksdbjni/6.6.4/jar

**Comment by gaojieliu** [comment]
@adamretter 
Great, thanks a lot for your help!

**Pull request closed without merging**
