### PR TITLE
Improved transactions support in C API

### PR DESCRIPTION
**Pull request by mkosieradzki**
Solves #2632 

Added OptimisticTransactionDB to the C API.
Added missing merge operations to Transaction.
Added missing get_for_update operation to transaction

If required I will create tests for this another day.

### CODE REVIEW

**Comment by yiwu-arbug** [comment]
@mkosieradzki The patch looks good! Do you mind running `make format` once (which runs clang-format) and update the pull request? Thanks!

**Comment by mkosieradzki** [comment]
@yiwu-arbug I have rebased my commit and I have run make format and cleaned-up my commit. There are couple more warnings left, but I think this way looks nicer.

Let me know if you need me to squash my commit or introduce more fixes.

**Comment by aleksuss** [comment]
What is state of this PR ? I need the same functionality and I don't what to do. To wait for merging this PR or create new by myself ?

**Comment by mkosieradzki** [comment]
Still waiting for approval from @yiwu-arbug . I have just merged latests master branch. But I expect appveyor to fail because it is failing on the master branch.

**Comment by yiwu-arbug** [comment]
Sorry for delay. Merging.

**Comment by aleksuss** [comment]
I have one more question. What is the nearest release will be contain this feature ?

**Comment by yiwu-arbug** [comment]
Not sure if @maysamyabandeh is willing to cherry-pick it into 5.8 branch :)

**Comment by maysamyabandeh** [comment]
5.8 is not cut yet due to problems that regression benchmarks indicate. I am thinking 5.8 could be cut from the master whenever the regression problems are resolved.

**Pull request closed without merging**
