### PR TITLE
Use FaultInjectionTestFS in transaction_test, clarify Close() APIs

### PR DESCRIPTION
**Pull request by pdillinger**
Summary: ... instead of race-condition-laden FaultInjectionTestEnv. See https://app.circleci.com/pipelines/github/facebook/rocksdb/27912/workflows/4c63e5a8-597e-439d-8c7e-82308056af02/jobs/609648 and similar PR #11271

Had to fix the semantics of FaultInjectionTestFS Close() operations to allow a non-OK Close() to fulfill the obligation to close before destruction. To me, this is the obvious choice of Close contract, because what is the caller supposed to do if Close() fails and they still have an obligation to successfully close before object destruction? Call Close() in an infinite loop? Leak the object? I have added API comments to the Env and Filesystem Close() functions to clarify the contracts.

Note that `DB::Close()` has one exception to this kind of Close contract, but it is clearly described in API comments and it is really only for catching programming mistakes, not for dealing with exogenous errors.

Test Plan: watch CI

### CODE REVIEW

**Review by jowlyzhang — COMMENTED** [review]
@pdillinger Thanks for the PR to fix flaky tests! Looks like there are some failures related to this change.  Is it because `FaultInjectionTestFS` is missing some mocking capabilities?

**Comment by pdillinger** [comment]
> @pdillinger Thanks for the PR to fix flaky tests! Looks like there are some failures related to this change. Is it because `FaultInjectionTestFS` is missing some mocking capabilities?

I didn't realize I had unit test failures because gtest-parallel has bad UI. This is what my terminal looks like, with no indication of failure despite massive failures:

```
   21966 ms: ./transaction_test DBAsBaseDB/TransactionTest.TwoPhaseDoubleRecoveryTest/4
   22014 ms: ./transaction_test DBAsBaseDB/TransactionTest.TwoPhaseSequenceTest/2
   22407 ms: ./transaction_test StackableDBAsBaseDB/TransactionTest.TwoPhaseOutOfOrderDelete/1
   22974 ms: ./transaction_test StackableDBAsBaseDB/TransactionTest.TwoPhaseDoubleRecoveryTest/0
   24024 ms: ./transaction_test DBAsBaseDB/TransactionStressTest.TwoPhaseLongPrepareTest/0
   24187 ms: ./transaction_test DBAsBaseDB/TransactionTest.TwoPhaseOutOfOrderDelete/2
   24285 ms: ./transaction_test StackableDBAsBaseDB/TransactionTest.TwoPhaseSequenceTest/0
   24329 ms: ./transaction_test DBAsBaseDB/TransactionTest.TwoPhaseOutOfOrderDelete/0
   24837 ms: ./transaction_test StackableDBAsBaseDB/TransactionTest.TwoPhaseSequenceTest/2
   24921 ms: ./transaction_test DBAsBaseDB/TransactionTest.TwoPhaseSequenceTest/4
   24886 ms: ./transaction_test DBAsBaseDB/TransactionTest.TwoPhaseOutOfOrderDelete/5
   24922 ms: ./transaction_test DBAsBaseDB/TransactionTest.TwoPhaseOutOfOrderDelete/6
   24961 ms: ./transaction_test DBAsBaseDB/TransactionTest.TwoPhaseOutOfOrderDelete/4
   25030 ms: ./transaction_test DBAsBaseDB/TransactionTest.TwoPhaseSequenceTest/1
   24986 ms: ./transaction_test StackableDBAsBaseDB/TransactionTest.TwoPhaseSequenceTest/1
   25116 ms: ./transaction_test StackableDBAsBaseDB/TransactionTest.TwoPhaseDoubleRecoveryTest/1
   26056 ms: ./transaction_test DBAsBaseDB/TransactionTest.TwoPhaseOutOfOrderDelete/3
   26592 ms: ./transaction_test DBAsBaseDB/TransactionTest.TwoPhaseSequenceTest/6
   26681 ms: ./transaction_test StackableDBAsBaseDB/TransactionTest.TwoPhaseOutOfOrderDelete/2
   20378 ms: ./transaction_test DBAsBaseDB/TransactionStressTest.TwoPhaseLongPrepareTest/3
   20383 ms: ./transaction_test DBAsBaseDB/TransactionStressTest.TwoPhaseLongPrepareTest/2
   20343 ms: ./transaction_test DBAsBaseDB/TransactionStressTest.TwoPhaseLongPrepareTest/4
   20354 ms: ./transaction_test DBAsBaseDB/TransactionStressTest.TwoPhaseLongPrepareTest/5
   20964 ms: ./transaction_test DBAsBaseDB/TransactionStressTest.TwoPhaseLongPrepareTest/6
$       
```

**Review by jowlyzhang — APPROVED** [review]
Thank you for the PR @pdillinger, LGTM!

**Comment by pdillinger** [comment]
I realize that we don't have any assertions that RocksDB always calls Close() before destroying the file/directory handles, so my claims that it's required could be dubious. Quickly attempting to add such assertions in destructors for e.g. TestFSWritableFile causes test failures that are not easy to track down (testing issue or product issue?). I've added an internal "tech debt" task to look into this.

Thoughts @anand1976 ? The problem with allowing Close() to be skipped is that in general, RocksDB could accidentally miss I/O errors by skipping it. Perhaps we could still strive for imposing the requirement on ourselves even if we decide implementations should allow Close() to be skipped. Though that has the possible problem of RocksDB not exercising a usage pattern that other users of FileSystem might follow (skip Close()) and find is accidentally broken.

**Pull request closed without merging**
