### PR TITLE
Refactor ReadBlockContents()

### PR DESCRIPTION
**Pull request by siying**
Summary: Divide ReadBlockContents() to multiple sub-functions. Maintaining the input and intermediate data in a new class BlockFetcher.
I hope in general it makes the code easier to maintain.
Another motivation to do it is to clearly divide the logic before file reading and after file reading. The refactor will help us evaluate how can we make I/O async in the future.

Test Plan:Pass existing tests

### CODE REVIEW

**Comment by siying** [comment]
I ran a unfavored db_bench benchmark (ramfs, lz4, small blocks) and this PR seems to show about 2% performance regression. Let me see whether I can fix this, but I hope people feel OK about small regression.

**Comment by siying** [comment]
If I force the functions to inline, like this:
```
diff --git a/table/block_fetcher.h b/table/block_fetcher.h
index 7076feb..30d5fe8 100644
--- a/table/block_fetcher.h
+++ b/table/block_fetcher.h
@@ -62,14 +62,14 @@ class BlockFetcher {
   rocksdb::CompressionType compression_type;

   // return true if found
-  bool TryGetUncompressBlockFromPersistentCache();
+  inline bool TryGetUncompressBlockFromPersistentCache();
   // return true if found
-  bool TryGetFromPrefetchBuffer();
-  bool TryGetCompressedBlockFromPersistentCache();
-  void PrepareBufferForBlockFromFile();
+  inline bool TryGetFromPrefetchBuffer();
+  inline bool TryGetCompressedBlockFromPersistentCache();
+  inline void PrepareBufferForBlockFromFile();
   void GetBlockContents();
-  void InsertCompressedBlockToPersistentCacheIfNeeded();
-  void InsertUncompressedBlockToPersistentCacheIfNeeded();
-  void CheckBlockChecksum();
+  inline void InsertCompressedBlockToPersistentCacheIfNeeded();
+  inline void InsertUncompressedBlockToPersistentCacheIfNeeded();
+  inline void CheckBlockChecksum();
 };
 }  // namespace rocksdb
```
There won't be regression shown in the benchmark. But I think it's not a good idea to do so, as it may work for db_bench, but not in users' build. I prefer leaving it as it is and let compilers to determine whether to inline or not.

**Comment by sagar0** [comment]
Do you think the regression is due to creating new objects (BlockFetcher) and additional function calls? 
Either way, the 2% regression might be within a small error margin, and I believe we cannot deterministically say that this is a cause of regression.

**Comment by yuslepukhin** [comment]
There are couple of things here. 1) Splitting is good 2) If you want this code to function both sync and async then heap allocation of the request is not necessary. You can take a look at my PRs where static entry points to the class present both sycn and async interfaces such as RequestGet() and Get(). Get() being sync avoids heap allocation of the context and reduces the overhead.

**Comment by siying** [comment]
@sagar0 no. BlockFetcher for now is only allocated in stack, and as I explained in the earlier comment, the regression mostly comes from function inlining.

**Comment by siying** [comment]
@yuslepukhin I didn't think about that far yet. The only reason I tried this factor is to see how to split up I/O code path.

**Comment by yuslepukhin** [comment]
@siying The experimental coroutines that are are currently implemented with the MS compiler but not standard yet (not in C++17) allow you NOT to split the function and effectively create a callback on the next statement with in the function. I have not figured out how to vacate the parent thread yet so it is not really async at the moment. I will keep you posted.

**Pull request closed without merging**
