### PR TITLE
Bugfix/fix manual flush blocking bug

### LINKED ISSUE #9892: Flush with wait=false is still blocking while there are stopped writes
### Expected behavior
If there are stopped writes, manual flush should return and not block if in the flush options we have wait=false.

### Actual behavior
Manual flush is stuck forever if there are stopped writes

### Steps to reproduce the behavior
Written a test to reproduce the bug in the pull request solving it.

### PR DESCRIPTION
**Pull request by RoeyMaor**
Fix #9892

### CODE REVIEW

**Review by ajkr — APPROVED** [review]
LGTM, thanks! Do you mind adding a line in HISTORY.md under "Bug Fixes" section mentioning this bug fix?

**Comment by RoeyMaor** [comment]
> LGTM, thanks! Do you mind adding a line in HISTORY.md under "Bug Fixes" section mentioning this bug fix?

Sure.

**Comment by riversand963** [comment]
iiuc, I think the last argument of `FlushMemTable()` and `AtomicFlushMemTables()`, i.e. `writes_stopped` can cause confusion. It actually indicates whether this calling thread has joined the single-threaded write thread by calling `EnterUnbatched()`. The change here, when passing `true`, will cause data races between calling thread and other threads which are concurrently writing and hence accessing `ColumnFamilyData`.

**Comment by riversand963** [comment]
Data race caught by TSAN:
```
WARNING: ThreadSanitizer: data race (pid=11319)
  Read of size 8 at 0x7b7400003b10 by thread T47:
    #0 mem internal_repo_rocksdb/repo/db/column_family.h:349 (db_stress+0x9e014c)
    #1 rocksdb::(anonymous namespace)::MemTableInserter::CheckMemtableFull() internal_repo_rocksdb/repo/db/write_batch.cc:2321 (db_stress+0x9e014c)
    #2 rocksdb::(anonymous namespace)::MemTableInserter::DeleteImpl(unsigned int, rocksdb::Slice const&, rocksdb::Slice const&, rocksdb::ValueType, rocksdb::ProtectionInfoKVOS<unsigned long> const*) internal_repo_rocksdb/repo/db/write_batch.cc:1924 (db_stress+0x9e2123)
    #3 rocksdb::(anonymous namespace)::MemTableInserter::DeleteCF(unsigned int, rocksdb::Slice const&) internal_repo_rocksdb/repo/db/write_batch.cc:1973 (db_stress+0x9d9c60)
    #4 rocksdb::WriteBatchInternal::Iterate(rocksdb::WriteBatch const*, rocksdb::WriteBatch::Handler*, unsigned long, unsigned long) internal_repo_rocksdb/repo/db/write_batch.cc:519 (db_stress+0x9cda2d)
    #5 Iterate internal_repo_rocksdb/repo/db/write_batch.cc:449 (db_stress+0x9d901f)
    #6 rocksdb::WriteBatchInternal::InsertInto(rocksdb::WriteThread::WriteGroup&, unsigned long, rocksdb::ColumnFamilyMemTables*, rocksdb::FlushScheduler*, rocksdb::TrimHistoryScheduler*, bool, unsigned long, rocksdb::DB*, bool, bool, bool) internal_repo_rocksdb/repo/db/write_batch.cc:2620 (db_stress+0x9d901f)
    #7 rocksdb::DBImpl::WriteImpl(rocksdb::WriteOptions const&, rocksdb::WriteBatch*, rocksdb::WriteCallback*, unsigned long*, unsigned long, bool, unsigned long*, unsigned long, rocksdb::PreReleaseCallback*) internal_repo_rocksdb/repo/db/db_impl/db_impl_write.cc:477 (db_stress+0x65223c)
    #8 rocksdb::WritePreparedTxn::RollbackInternal() internal_repo_rocksdb/repo/utilities/transactions/write_prepared_txn.cc:419 (db_stress+0xa05df6)
    #9 rocksdb::PessimisticTransaction::Rollback() internal_repo_rocksdb/repo/utilities/transactions/pessimistic_transaction.cc:782 (db_stress+0x848af1)
    #10 rocksdb::StressTest::RollbackTxn(rocksdb::Transaction*) internal_repo_rocksdb/repo/db_stress_tool/db_stress_test_base.cc:638 (db_stress+0x31e02e)
    #11 operator() internal_repo_rocksdb/repo/db_stress_tool/multi_ops_txns_stress.cc:929 (db_stress+0x365a56)
    #12 __invoke_impl<void, (lambda at internal_repo_rocksdb/repo/db_stress_tool/multi_ops_txns_stress.cc:912:23) &> third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/invoke.h:61 (db_stress+0x365a56)
    #13 __invoke_r<void, (lambda at internal_repo_rocksdb/repo/db_stress_tool/multi_ops_txns_stress.cc:912:23) &> third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/invoke.h:111 (db_stress+0x365a56)
    #14 std::_Function_handler<void (), rocksdb::MultiOpsTxnsStressTest::UpdatePrimaryIndexValueTxn(rocksdb::ThreadState*, unsigned int, unsigned int)::$_2>::_M_invoke(std::_Any_data const&) third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/std_function.h:291 (db_stress+0x365a56)
    #15 operator() third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/std_function.h:560 (db_stress+0x35d5a1)
    #16 ~Defer internal_repo_rocksdb/repo/util/defer.h:44 (db_stress+0x35d5a1)
    #17 rocksdb::MultiOpsTxnsStressTest::UpdatePrimaryIndexValueTxn(rocksdb::ThreadState*, unsigned int, unsigned int) internal_repo_rocksdb/repo/db_stress_tool/multi_ops_txns_stress.cc:977 (db_stress+0x35d5a1)
    #18 rocksdb::MultiOpsTxnsStressTest::TestCustomOperations(rocksdb::ThreadState*, std::vector<int, std::allocator<int> > const&) internal_repo_rocksdb/repo/db_stress_tool/multi_ops_txns_stress.cc:519 (db_stress+0x363506)
    #19 rocksdb::StressTest::OperateDb(rocksdb::ThreadState*) internal_repo_rocksdb/repo/db_stress_tool/db_stress_test_base.cc:957 (db_stress+0x320551)
    #20 rocksdb::ThreadBody(void*) internal_repo_rocksdb/repo/db_stress_tool/db_stress_driver.cc:33 (db_stress+0x2f10c7)
    #21 rocksdb::(anonymous namespace)::StartThreadWrapper(void*) internal_repo_rocksdb/repo/env/env_posix.cc:447 (db_stress+0x6b6ead)

  Previous write of size 8 at 0x7b7400003b10 by thread T59 (mutexes: write M437547955033999168):
    #0 SetMemtable internal_repo_rocksdb/repo/db/column_family.h:365 (db_stress+0x65f70c)
    #1 rocksdb::DBImpl::SwitchMemtable(rocksdb::ColumnFamilyData*, rocksdb::DBImpl::WriteContext*) internal_repo_rocksdb/repo/db/db_impl/db_impl_write.cc:2085 (db_stress+0x65f70c)
    #2 rocksdb::DBImpl::FlushMemTable(rocksdb::ColumnFamilyData*, rocksdb::FlushOptions const&, rocksdb::FlushReason, bool) internal_repo_rocksdb/repo/db/db_impl/db_impl_compaction_flush.cc:2017 (db_stress+0x5a4e0b)
    #3 rocksdb::DBImpl::Flush(rocksdb::FlushOptions const&, rocksdb::ColumnFamilyHandle*) internal_repo_rocksdb/repo/db/db_impl/db_impl_compaction_flush.cc:1711 (db_stress+0x5adc56)
    #4 rocksdb::DBImpl::Flush(rocksdb::FlushOptions const&, std::vector<rocksdb::ColumnFamilyHandle*, std::allocator<rocksdb::ColumnFamilyHandle*> > const&) internal_repo_rocksdb/repo/db/db_impl/db_impl_compaction_flush.cc:1726 (db_stress+0x5bbbf3)
    #5 rocksdb::StackableDB::Flush(rocksdb::FlushOptions const&, std::vector<rocksdb::ColumnFamilyHandle*, std::allocator<rocksdb::ColumnFamilyHandle*> > const&) internal_repo_rocksdb/repo/include/rocksdb/utilities/stackable_db.h:349 (db_stress+0x3bd089)
    #6 rocksdb::StressTest::TestFlush(std::vector<int, std::allocator<int> > const&) internal_repo_rocksdb/repo/db_stress_tool/db_stress_test_base.cc:1951 (db_stress+0x314d3a)
    #7 rocksdb::StressTest::OperateDb(rocksdb::ThreadState*) internal_repo_rocksdb/repo/db_stress_tool/db_stress_test_base.cc:778 (db_stress+0x31f178)
    #8 rocksdb::ThreadBody(void*) internal_repo_rocksdb/repo/db_stress_tool/db_stress_driver.cc:33 (db_stress+0x2f10c7)
    #9 rocksdb::(anonymous namespace)::StartThreadWrapper(void*) internal_repo_rocksdb/repo/env/env_posix.cc:447 (db_stress+0x6b6ead)
```

**Pull request closed without merging**
