### PR TITLE
Added support for SstFileManager to RocksJava

### PR DESCRIPTION
**Pull request by adamretter**

### CODE REVIEW

**Comment by sagar0** [comment]
@adamretter sst_file_manager.cc and SstFileManager.java are missing.

**Comment by adamretter** [comment]
@sagar0 Doh! Okay just added them

**Comment by sagar0** [comment]
I added a new section to HISTORY.md recently where all Java change log can go into (#3647). Could you add a line about this change in there?

**Comment by adamretter** [comment]
@sagar0 Done.

**Pull request closed without merging**
