### PR TITLE
C file should not include <cinttypes>, it is a C++ header.

### PR DESCRIPTION
**Pull request by spetrunia**
Include <inttypes.h> instead.

### CODE REVIEW

**Comment by spetrunia** [comment]
Background: 
The issue is caused by a recent patch in RocksDB:
https://github.com/facebook/rocksdb/commit/d68f9f4580f083023f8e20939b2866cac48f9bb6
the patch did a bulk change:
```diff
-#include <inttypes.h>
+#include <cinttypes>
```
and accidentally changed a C file. The patch also removed `define __STDC_FORMAT_MACROS` .  `crc32c_ppc.c` does not use format macros.

As a consequence, MyRocks/MariaDB build fails on PPC now: https://jira.mariadb.org/browse/MDEV-19830

**Comment by riversand963** [comment]
Do we need the `__STDC_FORMAT_MACROS`?

**Comment by siying** [comment]
@riversand963 if it compiles, then we don't need it.

**Comment by miasantreble** [comment]
@spetrunia if this file doesn't use format macros then maybe we can simply remove that line?

**Comment by riversand963** [comment]
> @riversand963 if it compiles, then we don't need it.

According to people's experience with different compilers, e.g. https://stackoverflow.com/questions/14535556/why-doesnt-priu64-work-in-this-code, if `#include <inttypes.h>` is present, we should always use `__STDC_FORMAT_MACROS`.

**Comment by siying** [comment]
@riversand963 I wonder whether __STDC_FORMAT_MACROS  is a C++ thing or also is also applied to C. If it is a C++ thing, then we should not have it at all. The macro has name STD on it, so I suspect that it is a C++ thing.

**Comment by riversand963** [comment]
@siying , SG. Should not be necessary for C.

**Comment by spetrunia** [comment]
> @spetrunia if this file doesn't use format macros then maybe we can simply remove the include?

Actually, seems like yes. I don't have access to a power8 machine, but examining the file manually, it looks like the `#include <stdint.h>` could be removed.

**Comment by miasantreble** [comment]
> Should this be done in the scope of this PR or the current variant is fine too?

I'd prefer removing unnecessary include directives

**Comment by spetrunia** [comment]
@miasantreble, changed the patch to include `stdint.h`. Please review

**Comment by adamretter** [comment]
@siying @gfosco this one is needed in 6.3 branch to be able to do releases for PPC, could you also check that it goes into newer branches too? For now I have manually picked it onto v6.3.6 to be able to build the release.

**Pull request closed without merging**
