### PR TITLE
Remove some components

### PR DESCRIPTION
**Pull request by siying**
Summary: Remove some components that we never heard people using them.

Test Plan: make all check. Watch CIs to pass

### CODE REVIEW

**Comment by ajkr** [comment]
looks good, though I wonder if we should save it for 6.0

**Comment by adamretter** [comment]
@ajkr @gfosco I creates a Milestone for 6.0.0 so that we don't loose track of what is destined for the next major release

**Comment by siying** [comment]
This time CI failures are not related.

**Comment by ajkr** [comment]
To me it's not consistent because we guarantee API compatibility across minor versions, and deleting features is certainly a breaking API change.

**Comment by siying** [comment]
@ajkr did we say we guarantee API compatibility across minor versions? Anyway, I can hold the PR until 6.0.0 is close.

**Comment by ajkr** [comment]
I don't know, maybe I've been the only one saying it. I always thought that our policy was to not break compilation so people can upgrade easily. Otherwise why do we leave behind deprecated options if we're ok with breaking it?

**Comment by adamretter** [comment]
@ajkr @siying @gfosco Just a suggestion - if the policy for version numbering and API changes across RocksDB is not clear, perhaps we could adopt the simple rules set out in [Semver](semver.org)? I have found that to work well in some other projects.

**Comment by siying** [comment]
Based on the conclusion on 6.0 scheduling, I'm going to land this PR.

**Comment by riversand963** [comment]
I like this `+4 -10393`.

**Pull request closed without merging**
