### PR TITLE
ingest sst files into bottommost non-empty level

### PR DESCRIPTION
**Pull request by yihuang**
Closes: #11212

It keeps the meaning of bottommost level to be consistent with bottommost_compression option, which is bottommost non-empty level, rather than simply `num_level-1`.

### CODE REVIEW

**Comment by cbi42** [comment]
There are a few unit tests failing in CI with this change.

**Comment by yihuang** [comment]
> There are a few unit tests failing in CI with this change.

how do I run unit test locally, I tried `make V=1 J=32 check`, but it finish succesfully.

**Comment by cbi42** [comment]
> > There are a few unit tests failing in CI with this change.
> 
> how do I run unit test locally, I tried `make V=1 J=32 check`, but it finish succesfully.

Can you `make clean` and then retry? I just ran tests with your branch and saw a few failures like the following.
Another test is `db_compaction_test`.
```
DEBUG_LEVEL=2 make -j6 external_sst_file_test
./external_sst_file_test

[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from ExternalSSTFileTest
[ RUN      ] ExternalSSTFileTest.PickedLevelDynamic
db/external_sst_file_test.cc:1416: Failure
Expected equality of these values:
  FilesPerLevel()
    Which is: "6"
  "5,0,0,1"
db/external_sst_file_test.cc:1423: Failure
Expected equality of these values:
  FilesPerLevel()
    Which is: "2,0,0,1"
  "1,0,0,2"
db/external_sst_file_test.cc:1431: Failure
Expected equality of these values:
  FilesPerLevel()
    Which is: "2,0,0,2"
  "1,0,0,3"
[  FAILED  ] ExternalSSTFileTest.PickedLevelDynamic (1419 ms)
...
```

**Comment by yihuang** [comment]
@cbi42 unit test fixed.
I must confess I don't fully grasp the all the logic in level style compaction, even don't fully understand if the code change is sound at all, so please review carefully ;D

**Comment by ajkr** [comment]
I do plan to review but haven't gotten to this yet. The CI test runs still show a failure, fyi.

By the way, if you use `level_compaction_dynamic_level_bytes=true`, we fill in non-L0 levels starting from the last `num_levels-1`. Under that config, this behavior seems OK. That's generally a good setting but not true by default as a migration is needed for existing DBs.

**Comment by yihuang** [comment]
> I do plan to review but haven't gotten to this yet. The CI test runs still show a failure, fyi.
> 
> By the way, if you use `level_compaction_dynamic_level_bytes=true`, we fill in non-L0 levels starting from level `num_levels-1`. Under that config, this behavior seems OK. That's generally a good setting but not true by default as a migration is needed for existing DBs.

Yeah, I just read about `level_compaction_dynamic_level_bytes`, that makes much more sense, we can try to just migrate to that.

**Pull request closed without merging**
