### PR TITLE
RemoveEmptyValueCompactionFilter

### PR DESCRIPTION
**Pull request by adamretter**
A general compaction filter that will remove key/value pairs during compaction that have empty-values. Also added support to the Java API for using this.

### CODE REVIEW

**Comment by adamretter** [comment]
Also addresses the issue raised here - https://github.com/facebook/rocksdb/issues/562.

**Comment by fyrz** [comment]
@adamretter can you add a differential ?

**Comment by adamretter** [comment]
@fyrz Sure! The differential is here - https://reviews.facebook.net/D42255

**Comment by guozhangwang** [comment]
Hi, I'm wondering if this feature has already been released in RocksDB? Currently I cannot find it in Java's ColumnFamilyOptions for setting compaction filter.

**Comment by siying** [comment]
It was merged on Aug 4 so it should have been released long ago. Which release version did you check?

**Comment by guozhangwang** [comment]
I'm using 3.10.1.

**Comment by adamretter** [comment]
You can set it by name. I'm on holiday right now so I can remember quite
how the code looks, but I am using it.

On Thursday, 24 December 2015, Guozhang Wang <notifications@github.com>
wrote:

> I'm using 3.10.1.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/rocksdb/pull/654#issuecomment-167019654>.
>


-- 
Adam Retter

skype: adam.retter
tweet: adamretter
http://www.adamretter.org.uk

**Pull request merged**
