### PR TITLE
add write_buffer_manager setter into options and tests in c bindings,

### PR DESCRIPTION
**Pull request by benoitmeriaux**
following https://github.com/facebook/rocksdb/pull/11710
 - add test on wbm c api
- add a setter for WBM in `DBOptions`

### CODE REVIEW

**Comment by ajkr** [comment]
Since there are two (also #11710), I'll take the first one - also it allows constructing WBM without a cache object, which is convenient. But 11710 is missing test cases, so if you want to adapt this PR to add the test case, and any APIs that are missing from 11710, I would be happy to merge this too

**Comment by benoitmeriaux** [comment]
I cannot push on the other fork branch, nor fork again since I already have this fork,
so I guess I have to wait for the other PR to be merged, then adjust my PR to add the test and the wbm setter in the option
unless you know a another option @ajkr ?

**Comment by ajkr** [comment]
> I cannot push on the other fork branch, nor fork again since I already have this fork, so I guess I have to wait for the other PR to be merged, then adjust my PR to add the test and the wbm setter in the option unless you know a another option @ajkr ?

Yes, I think waiting for the other PR to be merged will be the simplest way. Let me try to expedite merging that one. Thanks for your willingness to contribute the test.

**Comment by benoitmeriaux** [comment]
I updated the PR :)

**Review by ajkr — APPROVED** [review]
Thanks!

**Comment by benoitmeriaux** [comment]
@ajkr do you know when the next release is planned ?

**Comment by ajkr** [comment]
This will be in version 8.9, which should be tagged some time in December.

**Pull request closed without merging**
