### PR TITLE
add option of num_probes

### PR DESCRIPTION
**Pull request by chenyou-fdu**
add num_probes options for PlainTableBuilder /  PlainTableReader to avoid hard coded.

### CODE REVIEW

**Comment by chenyou-fdu** [comment]
related issue https://github.com/facebook/rocksdb/issues/5743

**Comment by siying** [comment]
Thank you for your contribution.
I have some concern to this API: it requires users to remember how many probes the database was built using. If they set a wrong value, the wrong query results will be returned. Ideally, the SST file should be self-sufficient enough so that it's hard for users to config it so that the result is wrong.

My suggestion is that when building the SST file, number of probes are written as a property in the property block. When opening the file, the property is retrieved and used to construct the bloom filter.

**Comment by pdillinger** [comment]
The block-based SST format sets num_probes appropriate for bits_per_key. I don't think there's a good reason to do any differently for plain table format. It's hard to imagine wanting a worse FP rate (more I/O) for a tiny improvement in Bloom query speed. As coded here, the behavior is "wrong by default" when setting either bits_per_key or num_probes without also carefully setting the other.

I also don't support extending the plain table SST filter schema without completely replacing the Bloom filter implementation to make it faster and more consistently accurate. https://github.com/facebook/rocksdb/blob/e8263dbdaad0546c54bddd01a8454c2e750a86c2/util/bloom_impl.h#L23

**Comment by chenyou-fdu** [comment]
@siying @pdillinger Thanks for the review.

Now the plain table format is using PlainTableBloomV1

https://github.com/facebook/rocksdb/blob/e8263dbdaad0546c54bddd01a8454c2e750a86c2/table/plain/plain_table_reader.h#L159

So it's better to do a similar way as filter_policy in BlockBasedTableOptions for plain table format once the bloom filter for plain table is all done, right? 

https://github.com/facebook/rocksdb/blob/e8263dbdaad0546c54bddd01a8454c2e750a86c2/include/rocksdb/table.h#L212-L215

https://github.com/facebook/rocksdb/blob/e8263dbdaad0546c54bddd01a8454c2e750a86c2/util/bloom.cc#L328-L334

**Pull request closed without merging**
