### PR TITLE
added --no_value option to ldb scan to dump key only

### PR DESCRIPTION
**Pull request by alexander-fenster**
Adding an option to ldb to make it possible to dump keys only, without values.

### CODE REVIEW

**Comment by igorcanadi** [comment]
Thanks for your contribution @alexander-fenster! Looks like the build throws a warning, check out https://travis-ci.org/facebook/rocksdb/builds/101656838

**Comment by alexander-fenster** [comment]
My bad. Let me fix it

**Comment by bolinfest** [comment]
So this would make it possible to do `ldb --db=DB scan --no_value | wc -l` to get the number of entries, correct?

This would certainly be an improvement over my current approach:

```
ldb --db=DB scan | grep -e '^[0-9a-f]\{40\} : ' | wc -l
```

**Comment by igorcanadi** [comment]
Yup @bolinfest. We just need to wait for @alexander-fenster  to fix the compile warning.

**Comment by alexander-fenster** [comment]
Sorry, totally forgot about it. Just fixed all the warnings.
@bolinfest: you should also use --hex, otherwise, if your keys or values contain '\n', it may not count lines properly.

**Pull request merged**
