### PR TITLE
[C] Add suggest_compact_range() and suggest_compact_range_cf() to C API.

### PR DESCRIPTION
**Pull request by yhchiang-sol**
Summary:
Add suggest_compact_range() and suggest_compact_range_cf() to C API.

Test Plan:
As verifying the result requires SyncPoint, which is not available in the c_test.c,
the test is currently done by invoking the functions and making sure it does not crash.

### CODE REVIEW

**Review by ajkr — APPROVED** [review]
LGTM, thanks!

**Review by ajkr — COMMENTED** [review]
A CI error:
```
db/c.cc:1745:14: error: ‘rocksdb’ has not been declared
 1745 |   Status s = rocksdb::experimental::SuggestCompactRange(
```

There's a `ROCKSDB_NAMESPACE` macro to use instead of `rocksdb`

**Comment by yhchiang-sol** [comment]
* Rebased.
* Replaced the use of namespace `rocksdb` by `ROCKSDB_NAMESPACE`.

**Comment by yhchiang-sol** [comment]
Rebase

**Pull request closed without merging**
