### PR TITLE
Fix RocksJava releases for macOS

### PR DESCRIPTION
**Pull request by adamretter**
Addresses the problems described in https://github.com/facebook/rocksdb/pull/9254#issuecomment-1054598516 and https://github.com/facebook/rocksdb/pull/9254#issuecomment-1059574837 that have blocked a RocksJava release

**NOTE** Also needs to be ported to 6.29.fb branch.

### CODE REVIEW

**Comment by adamretter** [comment]
@pdillinger @jay-zhuang @mrambacher can we get this merged to `main` and `6.29.fb` please?

**Review by pdillinger — APPROVED** [review]
LGTM. I don't have any compatibility / back-port concerns

**Comment by LuciferYang** [comment]
Looks like the problem will be solved soon?

**Comment by pdillinger** [comment]
> @pdillinger Several users have asked where the RocksJava 6.29.3 is (which was not possible due to these issues). Will there be another 6.29.x release? If so this will need to be back-ported there (along with some other fixes).

We can make another 6.29.x to get Java working. What else is needed apart from this commit? (This cherry-picks cleanly.)

**Comment by ajkr** [comment]
> What else is needed apart from this commit? 

I added a bunch of fixes that probably should've been backported already considering 6.29 is still the latest public release. Feel free to drop ones you don't want if any.

**Comment by pdillinger** [comment]
@adamretter Can you confirm that https://github.com/pdillinger/rocksdb/tree/6.29.4_candidate has everything you need? (CI in #9678)

**Comment by adamretter** [comment]
@pdillinger I am afraid that is not correct. It has some changes that were intended for RocksDB 7 that should not have gone into that branch. For example that branch now requires Java 8, but only RocksDB 7 should require Java 8. We are trying to work backwards and figure out what commits need to be removed...

**Comment by pdillinger** [comment]
The only relevant thing since tagging 6.29.3 is your commit.

```
$ git diff --name-only v6.29.3..6.29.4_candidate^^
HISTORY.md
db/db_basic_test.cc
db/db_compaction_test.cc
db/db_flush_test.cc
db/db_impl/db_impl.cc
db/db_impl/db_impl.h
db/db_impl/db_impl_compaction_flush.cc
db/db_impl/db_impl_readonly.cc
db/db_impl/db_impl_secondary.cc
db/db_merge_operand_test.cc
db/version_set.cc
db/version_set.h
table/block_based/block_based_table_reader.cc
util/compression.h
$ git log 6.29.4_candidate^^..6.29.4_candidate
commit 1d6ee8b62590558427e803cbdd4c9c40cb2aeee7 (HEAD -> 6.29.4_candidate, pd/6.29.4_candidate)
Author: Peter Dillinger <peterd@fb.com>
Date:   Tue Mar 8 09:20:33 2022 -0800

    Update version number

commit bd0957cb0fb25b8be460e277ccdc7b14bcaaec93 (6.29.fb)
Author: Adam Retter <adam.retter@googlemail.com>
Date:   Mon Mar 7 10:50:52 2022 -0800

    Fix RocksJava releases for macOS (#9662)
    
    Summary:
    Addresses the problems described in https://github.com/facebook/rocksdb/pull/9254#issuecomment-1054598516 and https://github.com/facebook/rocksdb/pull/9254#issuecomment-1059574837 that have blocked a RocksJava release
    
    **NOTE** Also needs to be ported to 6.29.fb branch.
    
    Pull Request resolved: https://github.com/facebook/rocksdb/pull/9662
    
    Reviewed By: ajkr
    
    Differential Revision: D34689200
    
    Pulled By: pdillinger
    
    fbshipit-source-id: c62fe34c54f05be5a00ee1daec8ec7454baa5eb8
$
```

**Comment by pdillinger** [comment]
Similar story if we go back to freeze on 6.29.0. The only change to build scripts is your change

```
$ git diff --name-only e8f116deabc601a5eae011f2fd8a38d02d87be8d..6.29.4_candidate^^
HISTORY.md
db/db_basic_test.cc
db/db_bloom_filter_test.cc
db/db_compaction_test.cc
db/db_flush_test.cc
db/db_impl/db_impl.cc
db/db_impl/db_impl.h
db/db_impl/db_impl_compaction_flush.cc
db/db_impl/db_impl_debug.cc
db/db_impl/db_impl_files.cc
db/db_impl/db_impl_open.cc
db/db_impl/db_impl_readonly.cc
db/db_impl/db_impl_secondary.cc
db/db_merge_operand_test.cc
db/memtable.cc
db/memtable.h
db/version_set.cc
db/version_set.h
include/rocksdb/advanced_options.h
include/rocksdb/env.h
include/rocksdb/utilities/object_registry.h
include/rocksdb/version.h
table/block_based/block_based_table_reader.cc
table/multiget_context.h
tools/db_crashtest.py
util/compression.h
util/dynamic_bloom.h
utilities/transactions/transaction_test.cc
$
```

**Comment by pdillinger** [comment]
@adamretter Any update?

**Comment by romanblachman** [comment]
Hi team, any updates on 6.29.x RocksDB for Java availability?

**Comment by adamretter** [comment]
Sorry for the delay. I had a 1 week holiday, and then I was unwell for about a week.
I am now back at work.

I understand from @ramvadiv that this has only just yesterday now been merged to 6.29.fb. I will now reattempt the build and figure out what additional fixes (if any) are needed for a 6.29.x release. Once that is complete, I will work to see what if any fixes are needed to get a 7.x.x release out ASAP.

**Comment by pdillinger** [comment]
> I understand from @ramvadiv that this was merged to 6.29.fb yesterday (which we were also waiting on).

Welcome back. This merge was only blocked because you last reported, "I am afraid that is not correct." https://github.com/facebook/rocksdb/pull/9662#issuecomment-1062732766

**Comment by adamretter** [comment]
@pdillinger @ramvadiv I have now managed to get 6.29.4 released to Maven Central. It should appear there within the next 2 hours. I will now try and get version 7.0.0 out

**Comment by adamretter** [comment]
@pdillinger @ramvadiv Version 7.0.3 has now also been released to Maven Central.
I had to rebuild the Windows Server build environment for VS 2019 and updated dependencies. Then I had also to make a small code fix to get it to compile on Windows with Visual Studio 2019 - I will send a separate PR shortly...

**Pull request closed without merging**
