### PR TITLE
Use user_comparator when comparing against iterate_upper_bound.

### LINKED ISSUE #983: custom comparator incompatible with iterate_upper_bound?
While trying to using `ReadOptions::iterate_upper_bound` in combination with a DB that uses a custom comparator (i.e. `ColumnFamilyOptions::comparator`) I discovered https://github.com/facebook/rocksdb/blob/master/db/db_iter.cc#L278:

```
      if (iterate_upper_bound_ != nullptr &&
          ikey.user_key.compare(*iterate_upper_bound_) >= 0) {
        break;
      }
```

`DBIter::FindNextUserEntryInternal` is using `rocksdb::Slice::compare` to compare the user key against the iteration upper bound. That doesn't seem to mesh with the presence of a custom comparator. Is there a reason for this or is it just a bug?

### PR DESCRIPTION
**Pull request by petermattis**
Fixes #983.

### CODE REVIEW

**Comment by igorcanadi** [comment]
Travis build failure looks unrelated.

**Comment by igorcanadi** [comment]
Thanks for the fix!

**Comment by tamird** [comment]
@igorcanadi can this fix be pulled into a release? Looks like 4.3.1 (released 10 days ago) doesn't yet include it.

**Comment by igorcanadi** [comment]
4.3.1 is built on a branch from January. Even though we release frequently (every one month or so), our release process is slow. The reason is that we don't publish the release publicly until we have been running the release internally for couple of weeks. Release 4.5.1 will include it (it's in the pipeline in this branch: https://github.com/facebook/rocksdb/commits/4.5.fb)

**Pull request merged**
