### PR TITLE
Postponing custom checksum support in BackupEngine

### PR DESCRIPTION
**Pull request by pdillinger**
Summary: This change reverts BackupEngine to 6.12 state to accommodate a
higher-priority fix that does not easily merge with this custom checksum
support. We intend to reinstate this support soon, by merging a revert
of this change.

For backupable_db_test, I've removed the tests depending on this
feature.

I've also removed relevant HISTORY.md entry.

Test Plan: unit tests

### CODE REVIEW

**Comment by pdillinger** [comment]
> This change reverts BackupEngine to 6.12 state

except I ran 'make format'. But the GitHub check still doesn't like part of it. :(

**Review by ajkr — APPROVED** [review]
LGTM!

**Review by zhichao-cao — APPROVED** [review]
Thanks!

**Comment by zhichao-cao** [comment]
> > This change reverts BackupEngine to 6.12 state
> 
> except I ran 'make format'. But the GitHub check still doesn't like part of it. :(

I have the similar issue. Maybe we can ignore it for now?

**Pull request closed without merging**
