### PR TITLE
handle error with kSkipAnyCorruptedRecords

### PR DESCRIPTION
**Pull request by cooljiansir**
in kSkipAnyCorruptedRecords mode, continue to replay the log.

### CODE REVIEW

**Comment by yiwu-arbug** [comment]
@cooljiansir Do you mind update kSkipAnyCorruptedRecords test in db/db_wal_test.cc make it also test this case? Thanks.

**Comment by siying** [comment]
@cooljiansir do you plan to address @yiwu-arbug 's comment?

**Comment by maysamyabandeh** [comment]
@siying Do you might have more context on this?
The implementation skips the log after hitting a corruption but continues to next log:
https://github.com/facebook/rocksdb/blob/eb9026f09bfd0582652cffa6a2390e9b55285b7f/db/db_impl/db_impl_open.cc#L946
However, the name kSkipAnyCorruptedRecords suggests that only the records subsequent to the corrupted record in the same log should also be inspected.

**Comment by siying** [comment]
@maysamyabandeh I don't have any context on it...

**Comment by maysamyabandeh** [comment]
I tried with unit test and the it seems that after an injected corruption, the file reader return kEnd so the reads from that file are stopped anyway. One might go deep and update log_reader.cc to return true after a corruption. That however would need more time to be done right. Given that the priority is not high, I don't have free cycles to work on this. If there is no volunteer, perhaps we can update the definition of kSkipAnyCorruptedRecords to clarify that it means skipping the corrupted log rather than corrupted entry.
@yiwu-arbug What do you think?

**Pull request closed without merging**
