### PR TITLE
travis: add Windows cross-compilation

### PR DESCRIPTION
**Pull request by tamird**
- downcase includes for case-sensitive filesystems
- give targets the same name (librocksdb) on all platforms

With this patch it is possible to cross-compile RocksDB for Windows
from a Linux host using mingw.

cc @yuslepukhin @orgads

### CODE REVIEW

**Comment by tamird** [comment]
@yiwu-arbug any comments I can address?

**Comment by yiwu-arbug** [comment]
@yuslepukhin Is this okay to merge? Thanks!

**Comment by tamird** [comment]
Ping.

**Comment by tamird** [comment]
@siying this now successfully cross compiles on Travis. Could you please take a look?

**Comment by tamird** [comment]
Travis failed with something unrelated, I think. Otherwise, this is green (previous iteration failed appveyor, but that's fixed now).

**Comment by adamretter** [comment]
@tamird @siying Unfortunately I think this has broken the Windows build. I opened an issue here - https://github.com/facebook/rocksdb/issues/2293. Using `git bisect` on `CMakeFiles.txt` on Windows 10, I tracked the first bad commit to `fdaefa0` which was from the squash and merge of this PR.

@tamird I would like to get your thoughts on this before I jump in any deeper please...

**Comment by adamretter** [comment]
@tamird Just to follow-up, I believe the issue is specifically here: https://github.com/facebook/rocksdb/pull/2107/files#diff-af3b638bc2a3e6c650974192a53c7291L511

Previously on Windows the static RocksDB lib was named like:

`set(ROCKSDB_STATIC_LIB rocksdblib${ARTIFACT_SUFFIX})`

but you changed that to:

`set(ROCKSDB_STATIC_LIB rocksdb${ARTIFACT_SUFFIX})`

However, elsewhere, in `java/CMakeLists.txt` it still expects `rocksdblib${ARTIFACT_SUFFIX}`, i.e. https://github.com/facebook/rocksdb/blob/master/java/CMakeLists.txt#L202

I will test with changing that to match `set(ROCKSDB_STATIC_LIB rocksdb${ARTIFACT_SUFFIX})` and see if it works...

**Comment by tamird** [comment]
Ah, so sorry about that! Perhaps we should add the Java build to Travis as
well. Thank you for looking into this!

**Comment by adamretter** [comment]
@tamird I made the change and it seems to work, so I have submitted a small PR for that.

I am not quite sure mingw-w64 works as I have never used it. I would like to see rocksjavastatic build on Travis for Windows using mingw-w64 though. Would you be able to send a PR?

**Comment by maysamyabandeh** [comment]
@tamird What does mingw cover that our the appveyor test does not already do? https://github.com/facebook/rocksdb/blob/master/appveyor.yml

**Comment by tamird** [comment]
Cross-compilation.

**Comment by maysamyabandeh** [comment]
Can you explain more? I do not see any related discussion at when this test was added and there is no proper documentation of why it should remain.

**Comment by tamird** [comment]
What would you like me to explain? The test checks that it is possible to compile rocksdb with mingw as that is the toolchain used to cross compile programs from Linux to Windows.

**Comment by maysamyabandeh** [comment]
You mean a source might successfully compile on windows but not by mingw on linux?

**Comment by tamird** [comment]
Yes. One example is pitfall is case sensitivity; this patch downcased
several includes for this reason. I believe this is all documented in the
commit messages.

**Pull request closed without merging**
