### PR TITLE
Add PutEntitiy GetEntitiy, & Iterator::columns into C API

### PR DESCRIPTION
**Pull request by Congyuwang**
Add basic ability to read / write wide columns for C-API.

### CODE REVIEW

**Comment by Congyuwang** [comment]
Related issue https://github.com/facebook/rocksdb/issues/12635

**Comment by fmvin** [comment]
Awaiting this PR as well.

**Comment by Congyuwang** [comment]
Just added PutEntity also for WriteBatch.

**Comment by Congyuwang** [comment]
Someone at Meta have a look at this thing?

**Pull request closed without merging**
