### PR TITLE
Replication-related improvements

### PR DESCRIPTION
**Pull request by mkosieradzki**
Solves #2775 and #2771

### CODE REVIEW

**Comment by yiwu-arbug** [comment]
LGTM. @maysamyabandeh leave to you to approve.

**Comment by maysamyabandeh** [comment]
The consensus is that we do not expose rocksdb's internal sequence numbers as it would make it harder to make future changes without breaking the API.

**Comment by mkosieradzki** [comment]
Thanks for making it clear.

**Comment by gdiazlo** [comment]
The JAVA bindings seems to support this API, isn't it the same for C?

**Pull request closed without merging**
