### PR TITLE
Travis: fail fast on install failures

### PR DESCRIPTION
**Pull request by pdillinger**
Summary: A recent build continued with confusing results after failing
to "snap install cmake" so ensure failures in installs are fatal. Also
upgrade snapd before "snap install" to hopefully avoid this error:

    error: cannot perform the following tasks:
    - Mount snap "cmake" (513) (snap "cmake" assumes unsupported features: command-chain (try to update snapd and refresh the core snap))

Test Plan: watch Travis

### CODE REVIEW

**Comment by pdillinger** [comment]
For reference: https://travis-ci.org/github/facebook/rocksdb/jobs/716643910

**Comment by adamretter** [comment]
@pdillinger I am not sure this will help. If `sudo snap install cmake --beta --classic` exited with a non-zero code I think the build would have stopped, if it exited with a zero code, then I don't think adding `exit $?` will help you, as you will just get the same code... or did I miss something subtle?

**Comment by pdillinger** [comment]
Updated Travis link (I'm getting a bad one from GitHub): https://travis-ci.org/github/facebook/rocksdb/builds/716990002

It looks like two builds are failing the snap install.

The subtle thing is this:

```
$ bash -c 'cat doesnotexist; echo next_step'; echo $?
cat: doesnotexist: No such file or directory
next_step
0
$ bash -c 'cat doesnotexist || exit $?; echo next_step'; echo $?
cat: doesnotexist: No such file or directory
1
$
```

Unless using `set -e` or an operator like && or ||, the return code of a command will be ignored if followed by another command.

**Comment by adamretter** [comment]
> Unless using set -e 

Of course! Apologies, I am so used to always running scripts that include `set -e`

**Comment by pdillinger** [comment]
@adamretter Can you look at fixing the two builds that are completely failing the snap install? Feel free to create your own PR that includes this change.

**Comment by adamretter** [comment]
@pdillinger Yes, but I probably won't get to it until the weekend

**Comment by pdillinger** [comment]
@craigscott-crascit Is there a missing "snap refresh core" step we weren't told about or something? Our linux builds here are failing with

    error: cannot perform the following tasks:
    - Mount snap "cmake" (513) (snap "cmake" assumes unsupported features: command-chain (try to update snapd and refresh the core snap))

as in https://travis-ci.org/github/facebook/rocksdb/jobs/716990011

**Comment by craigscott-crascit** [comment]
> @craigscott-crascit Is there a missing "snap refresh core" step we weren't told about or something? Our linux builds here are failing with
> 
> ```
> error: cannot perform the following tasks:
> - Mount snap "cmake" (513) (snap "cmake" assumes unsupported features: command-chain (try to update snapd and refresh the core snap))
> ```
> 
> as in https://travis-ci.org/github/facebook/rocksdb/jobs/716990011

That's the first I've heard of this problem. After a quick bit of searching, it does seem likely that the core snap is not recent enough and needs to be refreshed. [This issue](https://forum.snapcraft.io/t/better-guidance-for-missing-assumes-features/504/3) seems to describe the problem reasonably well. Based on that, I would expect a `sudo snap refresh core` might fix it, but you'd have to try that and see.

**Comment by pdillinger** [comment]
> [This issue](https://forum.snapcraft.io/t/better-guidance-for-missing-assumes-features/504/3) seems to describe the problem reasonably well. Based on that, I would expect a `sudo snap refresh core` might fix it, but you'd have to try that and see.

I think we have a winner with `sudo apt-get install snapd` to update snapd before running snap. Perhaps this subsumes `snap refresh core`. (?) Thanks.

**Comment by adamretter** [comment]
@pdillinger Another option might be to place `snaps` under addons. I think (but am not certain) that there might then be an update option. The travis syntax for snaps does not have much documentation, but perhaps the following might work:

```
addons:
  snaps:
    update: true
    packages:
      - cmake
         confinement:
           - classic
           - beta
```

**Comment by pdillinger** [comment]
Anything we add to Travis configuration now is better if it's more easily migrated to other CI systems.

**Comment by pdillinger** [comment]
> @pdillinger Okay understood. So the preference is to script things, rather than use the YAML config options?

At least not spend extra time trying to use Travis-specific configs. (Approval?)

**Review by adamretter — APPROVED** [review]

**Pull request closed without merging**
