### PR TITLE
fix code in 5.15.fb Bugfix concurrent list(iterator next) poor performance with java comparator in use by emc wayne gao

### PR DESCRIPTION
**Pull request by gwnet**
Hello Buddy

I found one RocksDBJava will be very poor performance on concurrent list with iterator next. The root cause is that if you use any Java compactor from your own. It will hit the mutex on the JNI code.

I locally fix this with thread local object that hold JNI global reference

### CODE REVIEW

**Comment by sagar0** [comment]
@gwnet Can you give us additional information about the benchmarks that you might have run? It would be great to see some numbers to compare the performance. 

That said, we only accept PRs to be merged into RocksDB master branch, and then cherry-pick any critical fixes into point releases, if necessary.

**Comment by sagar0** [comment]
I believe this is the same as #4342 . Why did you want to create another PR?

**Comment by gwnet** [comment]
> @gwnet Can you give us additional information about the benchmarks that you might have run? It would be great to see some numbers to compare the performance.
> 
> That said, we only accept PRs to be merged into RocksDB master branch, and then cherry-pick any critical fixes into point releases, if necessary.

Hello sagar, 
there is no existing benchmark cover this issue. we have to reproduce this with 128 threads do iterator next with Java comparator. it will be 100 times worse when you do 128 threads iterator next. the root cause is below and it is obvious: 
Many threads blocking at below stack. We can see when native comparator callback into java world. There is one mutex. I read through the code even though there is some compare options but no method to remove this mutex. All the comparator options did not make any difference.
Thread 168 (Thread 0x7fb740ae6700 (LWP 56245)):
#0  0x00007fb78ab8da8c in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007fb78ab887a3 in pthread_mutex_lock () from /lib64/libpthread.so.0
#2  0x00007fb758a13159 in rocksdb::port::Mutex::Lock() () from /tmp/librocksdbjni9154151366633665417.so
#3  0x00007fb758864828 in rocksdb::BaseComparatorJniCallback::Compare(rocksdb::Slice const&, rocksdb::Slice const&) const () from /tmp/librocksdbjni9154151366633665417.so
#4  0x00007fb7589383fd in rocksdb::DBIter::FindNextUserEntryInternal(bool, bool) () from /tmp/librocksdbjni9154151366633665417.so
#5  0x00007fb75893c621 in rocksdb::DBIter::Next() () from /tmp/librocksdbjni9154151366633665417.so
#6  0x00007fb77533ffa8 in ?? ()
#7  0x00000006892859b8 in ?? ()
#8  0x0000000000000000 in ?? ()
=======with comparator, no matter what comparator option you use, list 12K entries will take 4 second that is unbelievable slow
 Wayne rocksdb list time: 4317590454
subMapRet size : 12000


for the master, I tried commit code to master, but master Unit test is broken by some others code, so I cannot commit it to master. Could you please suggest me a solution?

**Comment by gwnet** [comment]
> I believe this is the same as #4342 . Why did you want to create another PR?

hello man, I tried to commit this change to master. but master code UT is broken by someone, even without my code change, the UT check will not pass. so I commit it to this branch. I really appreciate your help me to figure out what to do next

**Pull request closed without merging**
