### PR TITLE
Add iterate_prefix for ReadOption and construct internal iterators lazily 

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**
Summary

- Add iterate_prefix for ReadOption. Iterator created with this option will only retrieve keys have the specifed prefix when prefix_extractor is set.
- When iterate_prefix is set, check bloom filter first and then decide constuct the related internal iterator or not.

Potential use case
- Implement MVCC in user layer, user_key will contains a timestamp suffix in that case. And then use prefix seek to retrieve data.

@yiwu-arbug @siddontang

### CODE REVIEW

**Comment by zhangjinpeng1987** [comment]
@siying PTAL, thx.

**Comment by siying** [comment]
This is the old way of doing prefix iterator and we are moving away from it. This wiki page documented the history: https://github.com/facebook/rocksdb/wiki/Prefix-Seek-API-Changes#api-change-from-28---30
This was deprecated because it was hard to use. The prefix iterating interface we plan to move to is the other direction, which is to make it even more automatic: figuring out whether prefix extractor can be used by looking at seek key and upper bound.

Btw, we have explicit plan of better support user timestamp. Here is a simply interface prototype: https://github.com/facebook/rocksdb/pull/5079

If you are interested, you can join this effort.

**Comment by yiwu-arbug** [comment]
@siying Just adding some context. The main goal of this patch is to improve prefix seek performance. We find that RocksDB init `LevelIterator` for every level, even when the prefix can be filter by prefix bloom, and the iterator init takes some cpu usage. Passing in prefix before seek will allow iterator filter out levels on init. Benchmark on our system (TiKV) shows a 10% improvement of non-exist key lookup. We will share db_bench result later.

**Comment by zhangjinpeng1987** [comment]
Benchmark for seek missing prefix:
```
./db_bench --benchmarks=fillseq,seekrandom,seekrandom --num=10000000 --threads=1 --key_size=32 --value_size=128 --cache_size=13421772800 --bloom_bits=10 --open_files=50000 --db=/data3/jinpeng/db_bench --keys_per_prefix=1 --prefix_size=24 --max_scan_distance=1 --use_iterate_prefix=false --seek_missing_prefix=true
```
use_iterate_prefix=false
```
DB path: [/data3/jinpeng/db_bench]
fillseq      :       2.706 micros/op 369496 ops/sec;   56.4 MB/s
DB path: [/data3/jinpeng/db_bench]
seekrandom   :       3.621 micros/op 276164 ops/sec; (0 of 10000000 found)

DB path: [/data3/jinpeng/db_bench]
seekrandom   :       3.508 micros/op 285049 ops/sec; (0 of 10000000 found)
```

use_iterate_prefix=true
```
DB path: [/data3/jinpeng/db_bench]
fillseq      :       2.675 micros/op 373792 ops/sec;   57.0 MB/s
DB path: [/data3/jinpeng/db_bench]
seekrandom   :       1.671 micros/op 598533 ops/sec; (0 of 10000000 found)

DB path: [/data3/jinpeng/db_bench]
seekrandom   :       1.623 micros/op 615993 ops/sec; (0 of 10000000 found)
```
We can see use iterate_prefix can double the QPS for seek missing prefix.

master seek missing prefix
```
DB path: [/data3/jinpeng/db_bench2]
fillseq      :       2.686 micros/op 372358 ops/sec;   56.8 MB/s
DB path: [/data3/jinpeng/db_bench2]
seekrandom   :       3.572 micros/op 279962 ops/sec; (0 of 10000000 found)

DB path: [/data3/jinpeng/db_bench2]
seekrandom   :       3.506 micros/op 285264 ops/sec; (0 of 10000000 found)
```

**Comment by zhangjinpeng1987** [comment]
Benchmark for one key per prefix
Total keys = 50,000,000
```
./db_bench --benchmarks=fillseq,seekrandom,seekrandom --num=50000000 --threads=1 --key_size=32 --value_size=128 --cache_size=13421772800 --bloom_bits=10 --open_files=50000 --db=/data3/jinpeng/db_bench --keys_per_prefix=1 --prefix_size=24 --max_scan_distance=1 --seek_missing_prefix=false --use_iterate_prefix=false
```
use_iterate_prefix=false
```
DB path: [/data3/jinpeng/db_bench]
fillseq      :       2.675 micros/op 373857 ops/sec;   57.0 MB/s
DB path: [/data3/jinpeng/db_bench]
seekrandom   :       9.480 micros/op 105484 ops/sec; (49999998 of 50000000 found)
DB path: [/data3/jinpeng/db_bench]
seekrandom   :       8.950 micros/op 111733 ops/sec; (49999998 of 50000000 found)
```
use_iterate_prefix=true
```
DB path: [/data3/jinpeng/db_bench]
fillseq      :       2.604 micros/op 384045 ops/sec;   58.6 MB/s
DB path: [/data3/jinpeng/db_bench]
seekrandom   :       6.721 micros/op 148782 ops/sec; (49999998 of 50000000 found)
DB path: [/data3/jinpeng/db_bench]
seekrandom   :       6.560 micros/op 152434 ops/sec; (49999998 of 50000000 found)
```
master
```
DB path: [/data3/jinpeng/db_bench2]
fillseq      :       2.546 micros/op 392770 ops/sec;   59.9 MB/s
DB path: [/data3/jinpeng/db_bench2]
seekrandom   :      10.251 micros/op 97554 ops/sec; (49999998 of 50000000 found)
DB path: [/data3/jinpeng/db_bench2]
seekrandom   :       9.967 micros/op 100335 ops/sec; (49999998 of 50000000 found)
```
There is also 50% improvement for one key per prefix case.

**Comment by siying** [comment]
@yiwu-arbug I've explained that why we are not going this route, and our plan to address the exact problem.

**Comment by siying** [comment]
If you are interested, we can discuss an interface like DB::NewIteratorAndSeek(seek_key), which allows you do the same without creating a potential conflicts between seek key and option.

**Comment by yiwu-arbug** [comment]
@siying thanks! we aware of the user timestamp effort and are exciting about it. But we didn't realize it also address the performance issue we encounter here. IMO its definitely more elegant than a `NewIteratorAndSeek` interface. I think we can discuss more on how we can collaborate on it.

**Comment by zhangjinpeng1987** [comment]
@siying Thanks for your reply. I didn't kown RocksDB adandomed such feature before, sorry about that, but it really helpful for our current transaction model.
By the way, i am very interest with user timestamp feature, it is cool. I will test it with our case as soon as it works.

**Comment by siying** [comment]
I'm going to close the PR for now, since we can't reach an agreement about how to move forward. We can have a separate design discussion in other channels before discussing in this pull request.

**Pull request closed without merging**
