### PR TITLE
Invoke OnTableFileCreated for empty SSTs

### PR DESCRIPTION
**Pull request by ajkr**
The API comment on `OnTableFileCreationStarted` (https://github.com/facebook/rocksdb/blob/b6280d01f9f9c4305c536dfb804775fce3956280/include/rocksdb/listener.h#L331-L333) led users to believe a call to `OnTableFileCreationStarted` will always be matched with a call to `OnTableFileCreated`. However, we were skipping the `OnTableFileCreated` call in one case: no error happens but also no file is generated since there's no data.

This PR adds the call to `OnTableFileCreated` for that case. The filename will be "(nil)" and the size will be zero.

Test Plan:

- Made `db_stress` verify the two functions are called the same number of times when it runs to completion. 
- Ran db_crashtest with 99% deletions, 1% updates, and small number of keys. This ensures empty files are generated often.

```
python tools/db_crashtest.py whitebox --write_buffer_size=131072 --target_file_size_base=131072 --max_bytes_for_level_base=524288 --compression_type=none --max_background_compactions=8 --value_size_mult=33 --ops_per_thread=1000 --max_key=10000 --delpercent=99 --writepercent=1 --iterpercent=0 --readpercent=0 --prefixpercent=0
```

### CODE REVIEW

**Comment by riversand963** [comment]
Currently do we know when a 0-byte SST will be generated?

**Comment by ajkr** [comment]
@riversand963 It looks like when a subcompaction generates no keys at all, then we open a file anyways in case there's range deletions. If there's then no range deletions the file would be empty so we drop it. I can't see other cases, but the empty file handling logic predates range deletion, so other cases may exist...

**Comment by ajkr** [comment]
My comment was specific to compaction. The conditions for flush generating an empty file may be different.

**Comment by riversand963** [comment]
Got it, thanks! I think I once saw an empty SST due to flush, but haven't been able to reproduce.

**Pull request closed without merging**
