### PR TITLE
Disable partitioning for l0

### PR DESCRIPTION
**Pull request by maysamyabandeh**
l0 files are accesses very often and using partitioning on index/filters could result to
i) higher cache misses
ii) contention on lock-based data structures in 2nd level index

This patch disables partitioning for l0 files.

### CODE REVIEW

**Comment by siying** [comment]
Can we still do L0 partitioning in universal compaction? L0 files an be quite large for universal.

**Comment by siying** [comment]
Actually, L0 files can be also be relatively large in leveled compaction after @ajkr 's L0->L0 compaction.

**Comment by maysamyabandeh** [comment]
@siying Thanks for the comment. Yeah Leo and Andrew mentioned the same thing. I am going to disable this optimization for universal compaction.

**Comment by siying** [comment]
I rethink about it. Shouldn't partitioning of L0 files will reduce the contention? Even if we only partition to two blocks, each Get() will at most get one of them, so the contention should be less. Regarding the cache misses. If it happens to get higher cache misses because some index blocks of L0 are evicted, it is because based on LRU, the block is less used. So it may not be a bad idea to evict them.

**Comment by maysamyabandeh** [comment]
1. This change did fix the max latency problem that we observed in linkbench experiments
2. I believe it is not the cache eviction as much as it is the first time loading the partitions into the cache.
3. The partitioned indexes has some maps and sets to remember which partitions they have already loading into the cache. These data structures are currently protected simply by a mutex. When the sizes goes high, the contention of accessing these becomes non-trivial. For example, in an experiment when we increased the number of partitions by 4x, the max latency problem increased by a similar ratio as well. Or when we let the meta index to be evicted from the cache (and hence dont let it have enough time for the map/set size grow large) the max latency problem goes away as well.

**Comment by maysamyabandeh** [comment]
Abandoned in favor of https://github.com/facebook/rocksdb/pull/2661

**Pull request closed without merging**
