### PR TITLE
Add ratio of deletion entries as compaction trigger

### PR DESCRIPTION
**Pull request by cheng-chang**
For a non-zero level, if the level size hasn't exceeded the limit, but there are lots of deletion entries, it should also be a good candidate for compaction. Otherwise, queries for the deleted keys might be slow because they need to go over all the tombstones.

Test Plan:
Added a new unit test `CompactionPickerTest::LevelTriggerDeletion`.
Updated unit tests related to (de)serializing the new option.
Updated unit tests for `SetOptions` to test against the new option.

### CODE REVIEW

**Comment by cheng-chang** [comment]
Another case is that there are a few SST files with high ratio of deletion entries, we may want to prioritize compacting these files. This heuristic can be in another PR.

**Comment by siying** [comment]
I have some questions related to this PR.
It doesn't seem that compaction triggering condition (`CompactionPicker::NeedsCompaction`) is adjusted based on a file with high tombstone ratio. Compaction scores for different levels are not adjusted either. If that is the case, should we just adjust size compensation, just as what we do in `VersionStorageInfo::ComputeCompensatedSizes()`?

Another choice is to put those files in one of the file like e.g. `expired_ttl_files_`. Maybe we should repurpose this queue to serve both of ttl and this use case. In this way, a file with high tombstone ratio is guaranteed to be compacted down and with a high priority.

**Comment by cheng-chang** [comment]
Siying's suggestion makes sense to me, I'll open another PR with a different solution.

**Comment by cheng-chang** [comment]
reopened in https://github.com/facebook/rocksdb/pull/6760

**Pull request closed without merging**
