### PR TITLE
Compatible changes for cmake

### PR DESCRIPTION
**Pull request by merryChris**
`${TESTUTILLIB}` should be linked with targets`${LIBS}`, otherwise it may not find the references. After that, we have to work fine with `${CMAKE_CURRENT_SOURCE_DIR}` in `cmake/modules/ReadVersion.cmake`, while building external projects with `add_subdirectory(/path/to/rocksdb)`.

### CODE REVIEW

**Comment by tchaikov** [comment]
@merryChris again, i recommend put the details in the commit message instead of in the first comment in a PR.

**Comment by merryChris** [comment]
> @merryChris again, i recommend put the details in the commit message instead of in the first comment in a PR.
> 
> we could be more specific than:
> 
> > Compatible changes for cmake.

@tchaikov Done!!! I thought the details is put into commit message with the first comment automatically. Forgive my innocence, and thx for your patience.

**Comment by pdillinger** [comment]
> > @merryChris again, i recommend put the details in the commit message instead of in the first comment in a PR.
> > we could be more specific than:
> > > Compatible changes for cmake.
> 
> @tchaikov Done!!! I thought the details is put into commit message with the first comment automatically. Forgive my innocence, and thx for your patience.

This repository, for better or worse, turns each PR into a single commit in a linear history, using the PR title + first comment as the git commit message.

**Comment by merryChris** [comment]
@pdillinger @tchaikov Got it. I have already done things right just as you say. Here is my git local git log.

image

I've rebase the latest master and `push -f`. Any other changes need do?

**Comment by tchaikov** [comment]
@merryChris thanks for addressing the issues in cmake. i am just not in favor of the title

> Compatible changes for cmake

as neither of the changes are related to compatibility: the first one is to make sure the compiler is able to find the header files offered by `${LIBS}`, the second one helps the parent project including rocksdb to build. but maybe it's good enough, as probably i am interpreting compatibility in a different way.

**Comment by merryChris** [comment]
> @merryChris thanks for addressing the issues in cmake. i am just not in favor of the title
> 
> > Compatible changes for cmake
> 
> as neither of the changes are related to compatibility: the first one is to make sure the compiler is able to find the header files offered by `${LIBS}`, the second one helps the parent project including rocksdb to build. but maybe it's good enough, as probably i am interpreting compatibility in a different way.

@tchaikov Updated again. Nice to meet such strict code review, and thx for your patience. Any defect found, feel free to ping me.

**Comment by merryChris** [comment]
@tchaikov Could you plz have a look at ci appveyor part? Retried but failed several times. thx in advance.

image

**Comment by pdillinger** [comment]
> @tchaikov Could you plz have a look at ci appveyor part? Retried but failed several times. thx in advance.
> 
> image

Unlucky timeout. We should really try to fix that, but I don't know that I have access to its config.

**Comment by pdillinger** [comment]
> Unlucky timeout. We should really try to fix that, but I don't know that I have access to its config.

Now I have powers over AppVeyor. We'll see how that goes. :)

**Comment by merryChris** [comment]
> > Unlucky timeout. We should really try to fix that, but I don't know that I have access to its config.
> 
> Now I have powers over AppVeyor. We'll see how that goes. :)

Thx in advance, and looking forward to your reply.

**Pull request closed without merging**
