### PR TITLE
Add Arm64 builds to Travis

### PR DESCRIPTION
**Pull request by adamretter**
Subsumes https://github.com/facebook/rocksdb/pull/5928

### CODE REVIEW

**Comment by adamretter** [comment]
Hey @HouBingjian @guyuqi @cnqpzhang @wangxiyuan @Zhiwei-Dai, Travis-CI now offers builds on Arm64 based machines.

Good news - I have added this to our `.travis.yml`: https://travis-ci.org/facebook/rocksdb/builds/599829524?utm_source=github_status&utm_medium=notification

We have two test cases which are failing on Arm64: `JOB_NAME=platform_dependent`, and `TEST_GROUP=4`. I don't have a great deal of ARM expertise, would one of or more of you be willing to take a look?

The `TEST_GROUP=1` is also failing, but only due to a lack of Disk Space (10GB) in the ARM64 containers, I have opened an issue with Travis and they will hopefully provide a new image build this coming week that has a larger Disk quota.

**Comment by wangxiyuan** [comment]
@adamretter good news. Looking forward for ARM support.  And @Yikun can help with the ARM problem. some of the errors is included in the issues I created before.

https://github.com/facebook/rocksdb/issues/5736
https://github.com/facebook/rocksdb/issues/5751

If you need arm VM for debugging, please let us know. We can provide for you.

**Comment by Yikun** [comment]
The ``TEST_GROUP=4`` problem looks like due to https://github.com/facebook/rocksdb/issues/5736 .

**Comment by guyuqi** [comment]
`TEST_GROUP=4` : failed in `db_universal_compaction_test`.

I also run the `db_universal_compaction_test` in my local environments and every tests cases in `db_universal_compaction_test` are ok:
```
builder@vm-rocksdb-yq:~/rocksdb$ ./db_universal_compaction_test
[==========] Running 147 tests from 5 test cases.
[----------] Global test environment set-up.
[----------] 5 tests from DBTestUniversalDeleteTrigCompaction
[ RUN      ] DBTestUniversalDeleteTrigCompaction.BasicL0toL1
[       OK ] DBTestUniversalDeleteTrigCompaction.BasicL0toL1 (1190 ms)
[ RUN      ] DBTestUniversalDeleteTrigCompaction.SingleLevel
[       OK ] DBTestUniversalDeleteTrigCompaction.SingleLevel (972 ms)
[ RUN      ] DBTestUniversalDeleteTrigCompaction.MultipleLevels
[       OK ] DBTestUniversalDeleteTrigCompaction.MultipleLevels (2210 ms)
[ RUN      ] DBTestUniversalDeleteTrigCompaction.OverlappingL0
[       OK ] DBTestUniversalDeleteTrigCompaction.OverlappingL0 (1093 ms)
[ RUN      ] DBTestUniversalDeleteTrigCompaction.IngestBehind
[       OK ] DBTestUniversalDeleteTrigCompaction.IngestBehind (984 ms)
[----------] 5 tests from DBTestUniversalDeleteTrigCompaction (6449 ms total)

[----------] 126 tests from UniversalCompactionNumLevels/DBTestUniversalCompaction
DBTestUniversalCompactionParallel/DBTestUniversalCompactionParallel.PickByFileNumberBug/1 (6588 ms)
[----------] 4 tests from DBTestUniversalCompactionParallel/DBTestUniversalCompactionParallel (47709 ms total)
.....................
.................
.............

[----------] 4 tests from DBTestUniversalManualCompactionOutputPathId/DBTestUniversalManualCompactionOutputPathId
[ RUN      ] DBTestUniversalManualCompactionOutputPathId/DBTestUniversalManualCompactionOutputPathId.ManualCompactionOutputPathId/0
[       OK ] DBTestUniversalManualCompactionOutputPathId/DBTestUniversalManualCompactionOutputPathId.ManualCompactionOutputPathId/0 (3238 ms)
[ RUN      ] DBTestUniversalManualCompactionOutputPathId/DBTestUniversalManualCompactionOutputPathId.ManualCompactionOutputPathId/1
[       OK ] DBTestUniversalManualCompactionOutputPathId/DBTestUniversalManualCompactionOutputPathId.ManualCompactionOutputPathId/1 (3038 ms)
[ RUN      ] DBTestUniversalManualCompactionOutputPathId/DBTestUniversalManualCompactionOutputPathId.ManualCompactionOutputPathId/2
[       OK ] DBTestUniversalManualCompactionOutputPathId/DBTestUniversalManualCompactionOutputPathId.ManualCompactionOutputPathId/2 (2828 ms)
[ RUN      ] DBTestUniversalManualCompactionOutputPathId/DBTestUniversalManualCompactionOutputPathId.ManualCompactionOutputPathId/3
[       OK ] DBTestUniversalManualCompactionOutputPathId/DBTestUniversalManualCompactionOutputPathId.ManualCompactionOutputPathId/3 (3184 ms)
[----------] 4 tests from DBTestUniversalManualCompactionOutputPathId/DBTestUniversalManualCompactionOutputPathId (12288 ms total)

[----------] Global test environment tear-down
[==========] 147 tests from 5 test cases ran. (2159491 ms total)
[  PASSED  ] 147 tests.

```


And the `db_properties_test ` are passed which failed in #5736 
```
builder@vm-rocksdb-yq:~/rocksdb$ ./db_properties_test
[==========] Running 21 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 21 tests from DBPropertiesTest
[ RUN      ] DBPropertiesTest.Empty
[       OK ] DBPropertiesTest.Empty (37985 ms)
[ RUN      ] DBPropertiesTest.CurrentVersionNumber
.............
..........
.......
[ RUN      ] DBPropertiesTest.SstFilesSize
[       OK ] DBPropertiesTest.SstFilesSize (951 ms)
[ RUN      ] DBPropertiesTest.MinObsoleteSstNumberToKeep
[       OK ] DBPropertiesTest.MinObsoleteSstNumberToKeep (1329 ms)
[ RUN      ] DBPropertiesTest.BlockCacheProperties
[       OK ] DBPropertiesTest.BlockCacheProperties (1095 ms)
[----------] 21 tests from DBPropertiesTest (359952 ms total)

[----------] Global test environment tear-down
[==========] 21 tests from 1 test case ran. (359952 ms total)
[  PASSED  ] 21 tests.
```


But the `bloom_test ` failed: 
```
builder@vm-rocksdb-yq:~/rocksdb$ ./bloom_test
[==========] Running 11 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 4 tests from BloomTest
[ RUN      ] BloomTest.EmptyFilter
[       OK ] BloomTest.EmptyFilter (0 ms)
[ RUN      ] BloomTest.Small
[       OK ] BloomTest.Small (0 ms)
[ RUN      ] BloomTest.VaryingLengths
False positives:  0.23% @ length =      1 ; bytes =      9
...............
.............
..........
......
....
[ RUN      ] FullBloomTest.RawSchema
[       OK ] FullBloomTest.RawSchema (0 ms)
[ RUN      ] FullBloomTest.CorruptFilters
bloom_test: util/bloom.cc:288: virtual rocksdb::FilterBitsReader* rocksdb::{anonymous}::BloomFilterPolicy::GetFilterBitsReader(const rocksdb::Slice&) const: Assertion `num_probes <= 127' failed.
Aborted (core dumped)
```

**Comment by wangxiyuan** [comment]
`db_properties_test` passed in my last test. I removed it in my issue.
`db_universal_compaction_test` still failed the same as Travis CI shown.

**Comment by adamretter** [comment]
@wangxiyuan I also just rebased to bring in any recent changes.

**Comment by pdillinger** [comment]
Things may have stabilized a bit for release (including #6024). I just did "make check" on master (f32a311) on our ARM64 instance on EC2, and only folly_synchronization_distributed_mutex_test failed consistently. Added PR #6126 for that.

Inconsistent failures:
* I got an intermittent failure in column_family_test that hasn't reproduced.
* I have PR #6215 for DBTestUniversalCompaction

**Comment by wangxiyuan** [comment]
@pdillinger Thanks for your fix. Could you take a look at https://github.com/facebook/rocksdb/issues/5751 ?
It's a failure for `make jtest` on aarch64.

**Comment by adamretter** [comment]
Thanks @pdillinger I have now rebased this on your fixes, let's see how she flies now...

**Comment by adamretter** [comment]
No just a single failure in `c_test::filter`

**Comment by wangxiyuan** [comment]
Closed https://github.com/facebook/rocksdb/issues/5751 it's passed now.

**Comment by wangxiyuan** [comment]
@adamretter Cool, `make jtest` passed on my ubuntu16.04 arm env as well. 

But when I ran `make jtest` on ubuntu18.04, it failed with:
```
java: db/file_indexer.cc:71: void rocksdb::FileIndexer::GetNextLevelIndex(size_t, size_t, int, int, int32_t*, int32_t*) const: Assertion `*left_bound <= *right_bound + 1' failed.
Aborted (core dumped)
Makefile:306: recipe for target 'run_test' failed
make[1]: *** [run_test] Error 134
make[1]: Leaving directory '/opt/rocksdb/java'
Makefile:2029: recipe for target 'jtest' failed
make: *** [jtest] Error 2
```
the java version is the same
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
```
 But the gcc is not (it's 5.4.0 on ubuntu16.04):
```
gcc (Ubuntu/Linaro 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by pdillinger** [comment]
> Now just a single failure in `c_test::filter`

Ah, I know why. Different legacy filter schema on ARM due to cache line size. Will prepare a PR

**Comment by adamretter** [comment]
@wangxiyuan it would probably be useful to examine the stack trace

**Comment by JunHe77** [comment]
I tried TEST_GROUP=platform_dependent on local Arm64 host with Ubuntu-16.04 of different modes (VM, docker, LXD), and passed DBWALTest.TruncateLastLogAfterRecoverWithoutFlush test in all of them.
A simple log is added to db_wal_test.cc to find logfile info, on local Arm platform, it outputed:
`fsize:27 blocks:35992 blocksz: 4096`
But on Travis it outputed:
`fsize:27 blocks:1 blocksz: 512`
Not sure if this is a Travis related issue (I knew little about TravisCI file system). But from what described [here](https://github.com/facebook/rocksdb/blob/master/env/io_posix.cc#L1044-L1059), it might be helpful to check with Travis guys.

**Comment by JunHe77** [comment]
I created a [topic](https://travis-ci.community/t/file-system-used-for-arm64-lxd/7218) in Travis. Welcome to comment. 😃

**Comment by pdillinger** [comment]
Using #6436 instead

**Pull request closed without merging**
