### PR TITLE
DataBlockHashIndex: avoiding expensive iiter->Next when handling hash kNoEntry

### PR DESCRIPTION
**Pull request by fgwu**
Summary:
When returning `kNoEntry` from HashIndex lookup, previously we invalidate the
`biter` by set `current_=restarts_`, so that the search can continue to the next
block in case the search result may reside in the next block.

There is one problem: when we are searching for a missing key, if the search
finds a `kNoEntry` and continue the search to the next block, there is also a
non-trivial possibility that the HashIndex return `kNoEntry` too, and the
expensive index iterator `Next()` will happen several times for nothing.

The solution is that if the hash table returns `kNoEntry`, `SeekForGetImpl()` just search the last restart interval for the key. It will stop at the first key that is large than the seek_key, or to the end of the block, and each case will be handled correctly.

Microbenchmark script:
```
TEST_TMPDIR=/dev/shm ./db_bench --benchmarks=fillseq,readtocache,readmissing \
          --cache_size=20000000000  --use_data_block_hash_index={true|false}
```

`readmissing` performance (lower is better):
```
binary:                      3.6098 micros/op
hash (before applying diff): 4.1048 micros/op
hash (after  applying diff): 3.3502 micros/op
```

### CODE REVIEW

**Comment by fgwu** [comment]
@siying 

> There can still be internal key with this user key, with type 0 but greater than this key.


I didn't quite follow this sentence. Could you help me to understand with an example?

Here by `type | 0` I mean a packed internal key suffix with a supported type `type` and a seqno `0`.

**Comment by siying** [comment]
@fgwu for example, assume the seek key is: "AA | kTypeValue | 300", and there is a key "AA | kTypeDeletion | 0" in the block. In your case type=kTypeValue, so "AA | kTypeDeletion | 0" > "AA | type | 0". A key that should be returned is left out, based on the comment.

**Comment by fgwu** [comment]
@siying 
I think the contract can be modified to be more strict as 
```
// 1) there is no key in this block falling into the range:
//    ["seek_user_key @ type | seqno", "seek_user_key @ kTypeDelete |  0"]
```
where `kTypeDelete | 0` is the largest possible internal key that have a matching user key.

In the example if we are seeking `AA|kValueType|500`,

- in the program, the linear search will stop at `AA|kTypeDelete|0` and check if the user key is matching. Then it find the user key is matching, and the result type is supported (`kTypeDelete`), so eventually the iter is placed at `AA|kTypeDelete|0` and return `true` (instead of `false`).

- in the comment, if the function return true, and the iter is valid, the iter is set as if it has been set by `BinarySeek`.

Another way if reasoning: if the program return `false`, it means the linear search among the user key does not stop at any matching user_key but end up with a large user_key, or equivalently, there is no key exist in `[seek_key, seek_user_key|kValueDelete|0]`. Otherwise, the search will stop and return true.

Did I miss something?

**Comment by siying** [comment]
@fgwu yes, I think that should work.

**Pull request closed without merging**
