### PR TITLE
Add singleDelete to RocksJava

### PR DESCRIPTION
**Pull request by adamretter**
Added `RocksDB#singleDelete` and renamed/deprecated `RocksDB#remove` -> `RocksDB#delete`

### CODE REVIEW

**Comment by adamretter** [comment]
https://reviews.facebook.net/D62043

**Comment by yhchiang** [comment]
Thank you for adding this support!

**Comment by hari-rangarajan** [comment]
@yhchiang 
Is it available in a release yet? 
https://mvnrepository.com/artifact/org.rocksdb/rocksdbjni/4.11.2 is the latest but does not have these new changes.
Thanks!

**Comment by adamretter** [comment]
@hari-rangarajan I think @IslamAbdelRahman told me that it will be in the upcoming 4.13.

**Pull request merged**
