### PR TITLE
[add] C API support set max_background_jobs

### PR DESCRIPTION
**Pull request by DorianZheng**

### CODE REVIEW

**Comment by eostb** [comment]
https://github.com/genghaibo/eos/projects/3#card-11783214

**Comment by maysamyabandeh** [comment]
There seems to be many missing options in C API:
```
$ grep rocksdb_options_set db/c.cc | wc -l
101
```
While I count 132 options: https://pastebin.com/jVWZD4ry
Instead of having a separate PR for each, it is better to tackle them all at once.

@DorianZheng Would you be interested to tackle that?

**Comment by siddontang** [comment]
@maysamyabandeh 

I think this is a huge work for @DorianZheng when adding so many functions at the same time.

Why not file an issue with `help-wanted` label, list all unfinished C APIs and let the community help us? 

/cc @siying

**Comment by maysamyabandeh** [comment]
This patch would only add 2 lines of code. A richer patch take adds more options to C API does not occur as "huge" to me.

**Comment by ajkr** [comment]
I don't see why a user who wants to use one C API needs to implement all the other unimplemented ones.

**Comment by ajkr** [comment]
Oh it's done in #4267.

**Pull request closed without merging**
