### PR TITLE
Add ROCKSDB_DISABLE_* environment variables

### LINKED ISSUE #3036: No way to not use libtbb if it is detected, even if it is only available as a dynamic library
### Expected behavior

RocksDB should be able to build a library that does not use `libtbb` whether or not `libtbb` is available on the build system. This is useful for building static binaries (note that `libtbb-dev` in Ubuntu does not ship a static `libtbb.a`), and for building dynamic binaries intended to be used on systems where `libtbb` will not be available.

### Actual behavior

RocksDB detects that libtbb works here:

https://github.com/facebook/rocksdb/blob/279296f4d834d4cbdc35be28fca5b1eef71693a3/build_tools/build_detect_platform#L306-L315

There is no way to override this check and request that `libtbb` not be used in the build.

This is causing trouble for our downstream project in https://github.com/vgteam/vg/issues/1173 where a user is trying to build a static binary of our tool, which uses RocksDB, on a system where `libtbb`'s headers and dynamic library are installed, but where no `libtbb.a` is available. The only thing I can really tell them is to uninstall `libtbb` from the system, which is hardly an appropriate answer.

### Steps to reproduce the behavior

* Build RocksDB when `libtbb` is installed but `libtbb.a` does not exist.

* See that `PLATFORM_LDFLAGS` in `make_config.mk` contains `-ltbb`.

* Try to link a `-static` RocksDB-using binary, using those flags.

* Observe an error due to a missing `-ltbb`.

### PR DESCRIPTION
**Pull request by adamnovak**
Should fix #3036.

### CODE REVIEW

**Comment by yiwu-arbug** [comment]
@adamnovak Thanks! Mind signing the CLA?

**Comment by adamnovak** [comment]
I'm working on it. I think I have to run it by UC Santa Cruz's IP people.

**Comment by adamnovak** [comment]
OK, I've heard back from the UC Santa Cruz IP people, and they decline to sign the institutional CLA because of "problematic language". I have not inquired as to what language in particular is problematic.

They are, however, willing to "assign" code I have written to me personally. Then I could sign the individual CLA.

If I did that, would Facebook be able to accept the commit? Or will Facebook and UC have to actually get in contact with each other to negotiate a mutually acceptable CLA, even if I personally hold all rights to the changes?

**Comment by ajkr** [comment]
It seems in that case you'd be contributing on behalf of yourself, so individual CLA sounds good.

**Comment by sagar0** [comment]
@adamnovak Could you please sign the CLA so that we can accept this PR.

**Comment by adamnovak** [comment]
Not yet. I'm waiting on my employer to officially transfer to me any
copyright/patent rights that they may hold on my contribution (should it
ever somehow come to be patented...) so that I can sign the individual CLA.
I can follow up with our IP department to see how things are going.

**Comment by adamnovak** [comment]
OK, I've gotten all the IP rights squared away, and I've submitted the individual CLA.

**Comment by adamnovak** [comment]
I've rebased this PR to fix the merge conflicts.

**Pull request closed without merging**
