### PR TITLE
Add instructions for INSTALL_PATH make variable

### PR DESCRIPTION
**Pull request by lucky**

### CODE REVIEW

**Comment by sagar0** [comment]
@lucky Could you please sign the CLA so that we can accept your patch?

**Comment by lucky** [comment]
@sagar0 I'm sorry, I still waiting on legal's decision here. :slightly_frowning_face:

**Comment by miasantreble** [comment]
LGTM
@lucky any updates about the legal decision? 
We can merge this once you sign the CLA, thanks

**Comment by lucky** [comment]
I'm sorry for the wait. I haven't heard anything from legal but I'll ping them again today.

**Comment by miasantreble** [comment]
@lucky any luck with your legal team?

**Comment by lucky** [comment]
No, I've heard nothing. I'll close the pull request for now. If I can get the CLA signed in the future, I will re-open this.

**Pull request closed without merging**
