### PR TITLE
FlushMemTable return ok but memtable does not synchronize flush

### LINKED ISSUE #8046: When I set flush_options.wait = 1, FlushMemTable return ok but memtable does not synchronize flush
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
FlushMemTable return failed 
### Actual behavior
FlushMemTable return ok
### Steps to reproduce the behavior
1、In my environment ：db_options_.paranoid_checks = ture and auto_recovery_ = true
2、One compaction thread encountered a problem of insufficient disk space, so it set SetBGError. The bg_error_ will be set kSoftError.
3、Another compaction thread also encountered a problem of insufficient disk space, so it set SetBGError . The recovery_error will be set.
4、My code set flush_options.wait = 1  then call  DBImpl::Flush .
5、FlushMemTable  return ok but flush memtable thread failed with an insufficient disk space error.

### Where is the bug I guess
image

### PR DESCRIPTION
**Pull request by zhuchong0329**
Fix #8046 : FlushMemTable return ok but memtable does not synchronize flush. The way to fix it is to expose RecoveryError.

### CODE REVIEW

**Review by mrambacher — CHANGES_REQUESTED** [review]
I think this change is going to trigger a lot of failures in the "ASSERT_STATUS_CHECKED" cases.

A better approach may be to leave the code around line 2127 alone and add/copy line 2130-31 to around 2165.

**Comment by zhuchong0329** [comment]
@mrambacher , Thanks for the reminder. I did ignore ROCKSDB_ASSERT_STATUS_CHECKED.

**Comment by ajkr** [comment]
@zhuchong0329 this seems like a useful fix. Do you plan to try making it work with ASSERT_STATUS_CHECKED? I think you can get rid of all the early returns (e.g., L2125) and instead make them set `s` to a non-OK Status. Then add `s.ok()` to all the conditionals/loop conditions to make sure nothing meaningful executes and nothing overwrites `s` for the rest of the function.

**Comment by riversand963** [comment]
What's our plan with this PR? @jay-zhuang

**Review by ajkr — APPROVED** [review]
LGTM too.

**Pull request closed without merging**
