### PR TITLE
[RocksJava] Adjusted RateLimiter to 3.10.0

### PR DESCRIPTION
**Pull request by fyrz**
Summary:
- Deprecated RateLimiterConfig and GenericRateLimiterConfig
- Introduced RateLimiter

It is now possible to use all C++ related methods also in RocksJava.
A noteable method is setBytesPerSecond which can change the allowed
number of bytes per second at runtime.

Test Plan:
make rocksdbjava
make jtest

Reviewers: adamretter, yhchiang, ankgup87

Subscribers: dhruba

Differential Revision: https://reviews.facebook.net/D35715

### CODE REVIEW

**Comment by fyrz** [comment]
@yhchiang i moved that one to 3.11, because of the open issue.

**Comment by fyrz** [comment]
@yhchiang i`ll move that another time to 3.12. I think we should try to get it in 3.12
@adamretter maybe you can support me with the Mac intel.

**Comment by adamretter** [comment]
@fyrz Of course.

**Comment by yhchiang** [comment]
@fryz sure.  Let's try it :)

**Comment by adamretter** [comment]
Superseded by https://github.com/facebook/rocksdb/pull/1368

**Pull request closed without merging**
