### PR TITLE
Split WinEnv into separate classes.

### PR DESCRIPTION
**Pull request by yuslepukhin**
For ease of reuse and customization as a library
  without wrapping.
  WinEnvThreads is a class for replacement.
  WintEnvIO is a class for reuse and behavior override.
  Added private virtual functions for custom override
  of fallocate pread for io classes.

### CODE REVIEW

**Comment by yuslepukhin** [comment]
@siying This succeeds

**Comment by siying** [comment]
@yuslepukhin did any of your teammate review it? If they have, I'll just merge it blindly.

**Comment by yuslepukhin** [comment]
@siying @PraveenSinghRao @SherlockNoMad Yes, there has been an internal review.

**Comment by siying** [comment]
Thanks for your contribution!

**Pull request merged**
