### PR TITLE
Fixed negative numbers comparison in DocumentDB

### PR DESCRIPTION
**Pull request by StanislavGlebik**
Summary: 
Fixed TODO. Added correct serialization
of negative integers.

Test Plan: make all check

Reviewers: igor, sdong

Reviewed By: igor

Subscribers: dhruba, leveldb

Differential Revision: https://reviews.facebook.net/D31065

### CODE REVIEW

**Comment by igorcanadi** [comment]
I hope nobody is actually using this since it's changing disk format. It is tagged experimental in the .h file, though, so shouldn't be a problem.

**Comment by StanislavGlebik** [comment]
Yeap, I've thought about that. Maybe it's worth adding versions.

**Comment by igorcanadi** [comment]
@StanislavGlebik You should have commit access now.

**Comment by StanislavGlebik** [comment]
@igorcanadi Yeap, I have it. Thanks a lot!

**Pull request merged**
