### PR TITLE
Expose GetAllCompressionTypes()

### PR DESCRIPTION
**Pull request by IslamAbdelRahman**
Add a simple function in `include/rocksdb/convenience.h`
That will return `compression_type_string_map` map

### CODE REVIEW

**Comment by IslamAbdelRahman** [comment]
This is needed by https://github.com/facebook/mysql-5.6/pull/446

**Comment by yiwu-arbug** [comment]
Seems we also need to expose CompressionTypeSupported()?

**Comment by IslamAbdelRahman** [comment]
@yiwu-arbug , Yes .. I will create another PR for that
can you approve this one if you dont have more comments ?

**Comment by IslamAbdelRahman** [comment]
please ignore this PR

**Pull request closed without merging**
