### PR TITLE
fix powerpc java static build

### PR DESCRIPTION
**Pull request by ajkr**
added support for C and asm files as required for e612e317409e8a9d74cf05db0bd733403305f459.
 
Test Plan: Adam said build succeeds now.

### CODE REVIEW

**Comment by ajkr** [comment]
@kamasubb - would you be interested in helping review/test this? I don't have the right tools.

**Comment by adamretter** [comment]
@ajkr This fixes the build on PPC64le. Thanks... Although I can't comment on its correctness

**Comment by sagar0** [comment]
I too verified just now that this fixes PPC64le build on 5.9.fb branch. 
However this alone is not sufficient to fix the build break on master for 'make rocksdbjavastatic' target, and #3260 or an equivalent is needed.

**Comment by adamretter** [comment]
Closes https://github.com/facebook/rocksdb/issues/3315

**Pull request closed without merging**
