### PR TITLE
fixup TwoLevelIterator::SeekForPrev

### PR DESCRIPTION
**Pull request by framlog**
A.T. 

I encountered a bug when using `SeekForPrev` to find a target with a prefix which doesn't exist in the given sst file. And in some cases of that, `first_level_iter->Seek(target)` returns invalid iterator, which then makes `TwoLevelIterator::SeekForPrev` return some keys greater than `target`.  Here's the workaround.

btw, I don't know how to re-produce this situation but I encountered many times.

### CODE REVIEW

**Comment by siying** [comment]
Can you explain more about the bug? Or, can you write a unit test which used to fail, and will pass with this change?

**Comment by framlog** [comment]
@siying I added a test case which makes up a sst file to re-produce this. I don't know how to make rocksdb produce these kind of sst files with the test utils.

**Comment by framlog** [comment]
I met this when using 5.7.2 but don't know how to reproduce it without the dataset that I stored when that bug encountered after some tries. Or maybe it's resolved already...

I think it's caused by a sst file which covers the given target but has a hole at the target's prefix. Also, I observed that the `BlockIter::Seek` uses `PrefixSeek` to search the target in the index instead of `BinarySeek`, which then returns `ok = false`, which differs from the result if using `BinarySeek`, to make `TwoLevelIterator::SeekForPrev` return the last available key in the sst file, which's greater than  the given target. And in that case, the max heap in the `MergingIterator` outputs that key firstly, which 's wrong under the semantic of the `SeekForPrev`.

**Comment by framlog** [comment]
Btw,  Can I use `SeekForPrev` when using bloom filters as my table's filter policy? The test that I added fails to find the key when I using that option.

**Comment by siying** [comment]
@framlog by PrefixSeek() do you mean you enabled hash index? With hash index, unless you specify ReadOptions.total_order_seek, you are not only guarantee to show the keys within the prefix, not after.

By the way, later the code is refactored and TwoLevelIterator is not used in the path you mentioned, but customized ones are used.

**Comment by framlog** [comment]
@siying Any feedback?

**Comment by ajkr** [comment]
Can you provide the commit hash on which you're seeing the unit test fail? It is passing for me on RocksDB latest commit (b6280d01f9f9c4305c536dfb804775fce3956280)

**Comment by ajkr** [comment]
Either way you need to set total_order_seek for iterators to see the proper ordering of keys across prefixes.

**Comment by framlog** [comment]
@ajkr yep. It's a misuse of seek and hash index. I think this pr could be closed.

**Pull request closed without merging**
