### PR TITLE
Close the Logger before rolling to next one in AutoRollLogger

### PR DESCRIPTION
**Pull request by akankshamahajan15**
Summary: Close the existing logger first to release the existing
handle before renaming the file using the file system.
Since `AutoRollLogger::Flush` pinned down the `logger_`, `logger_` can't be closed unless its
the last reference otherwise it  gives seg fault during Flush on file
that has been closed.

Test Plan: CircleCI jobs

### CODE REVIEW

**Review by ajkr — APPROVED** [review]
OK with me. Maybe we should include the timestamp suffix for the newly created file so it doesn't have to wait for "LOG" to close/rename until we can recreate it and replace the shared_ptr

**Comment by akankshamahajan15** [comment]
> OK with me. Maybe we should include the timestamp suffix for the newly created file so it doesn't have to wait for "LOG" to close/rename until we can recreate it and replace the shared_ptr

Where to include "timestamp suffix"? I didn't get it completely.

**Comment by ajkr** [comment]
> > OK with me. Maybe we should include the timestamp suffix for the newly created file so it doesn't have to wait for "LOG" to close/rename until we can recreate it and replace the shared_ptr
> 
> Where to include "timestamp suffix"? I didn't get it completely.

Maybe not in this PR. I was just wondering if `Logv()` could be implemented like the following if the name of the current log file were "LOG.\<timestamp\>". The motivation is to reduce how long we hold the lock.

- Fast path (no rotation):
  - Grab lock
  - Check rotation is not needed
  - Release lock
  - Atomic load shared_ptr `logger_`
  - Call `Logv()` on it
- Slow path (rotation):
  - Grab lock
  - Check rotation is needed (store something like `rotating_ = true`)
  - Release lock
  - Call `NewLogger()` with "LOG.\<timestamp\>"
  - Atomic swap the new logger into `logger_`
  - Wait until the old logger's use count reaches one
  - Call `Close()` on the old logger
  - Call `Rename()` on the old logger to "LOG.old.\<timestamp\>"
  - Set `rotating_ = false`
  - Atomic load shared_ptr `logger_`
  - Call `Logv()` on it

**Comment by akankshamahajan15** [comment]
> > > OK with me. Maybe we should include the timestamp suffix for the newly created file so it doesn't have to wait for "LOG" to close/rename until we can recreate it and replace the shared_ptr
> > 
> > 
> > Where to include "timestamp suffix"? I didn't get it completely.
> 
> Maybe not in this PR. I was just wondering if `Logv()` could be implemented like the following if the name of the current log file were "LOG.<timestamp>". The motivation is to reduce how long we hold the lock.
> 
> * Fast path (no rotation):
>   
>   * Grab lock
>   * Check rotation is not needed
>   * Release lock
>   * Atomic load shared_ptr `logger_`
>   * Call `Logv()` on it
> * Slow path (rotation):
>   
>   * Grab lock
>   * Check rotation is needed (store something like `rotating_ = true`)
>   * Release lock
>   * Call `NewLogger()` with "LOG.<timestamp>"
>   * Atomic swap the new logger into `logger_`
>   * Wait until the old logger's use count reaches one
>   * Call `Close()` on the old logger
>   * Call `Rename()` on the old logger to "LOG.old.<timestamp>"
>   * Set `rotating_ = false`
>   * Atomic load shared_ptr `logger_`
>   * Call `Logv()` on it

Ah ok. Sure, I will address in separate PR.

**Pull request closed without merging**
