### PR TITLE
check timestamps pointer for nullptr

### PR DESCRIPTION
**Pull request by hliu18**

### CODE REVIEW

**Comment by hliu18** [comment]
@pdillinger @riversand963 
This is fix for issue #6745.

**Comment by pdillinger** [comment]
Even if this is a suitable fix, we need to understand impact on 6.9 internal release, and add a regression test here if there's a way to cause a crash.

**Comment by hliu18** [comment]
When timestamp feature is not enabled, crash cannot happen. The pointer is only dereferenced when timestamp size from user comparator is greater than 0. Current MultiGet() call with no timestamp maps into MultiGet() call with null timestamp pointer. We would have seen crashes if it can happen,

**Comment by riversand963** [comment]
I believe the multiget timestamp support has at least two other separate issues. When construction `LookupKeys` in the constructor of `MultiGetContext`, timestamp in `ReadOptions` has to be taken into account. Otherwise, wrong result will be returned.
Another issue is some overloaded versions of MultiGet() will sort `KeyContext` objects using custom compare logic. In these logic, we need to compare key without timestamp. This means we cannot call `Comparator::Compare` which assumes that the arguments have timestamps when the feature is enabled.
I have put up another fix in #6748 . In order to make the unit test pass, I have to include the fix in this PR. cc @hliu18 @pdillinger

**Comment by hliu18** [comment]
@riversand963 since your #6748 includes this fix, I'll just abandon this one.

**Pull request closed without merging**
