### PR TITLE
Update IOTrace operations in stackable_db.h

### PR DESCRIPTION
**Pull request by akankshamahajan15**
Summary: Update IOTrace operations in stackabledb.h and also trace few
other IO operations.

Test Plan: make check -j64

Reviewers:

Subscribers:

Tasks:

Tags:

### CODE REVIEW

**Review by anand1976 — APPROVED** [review]
LGTM

**Review by mrambacher — APPROVED** [review]
These changes follow the style of the existing code.  I created #7504 to document some of the issues with that style.

LGTM, with the aforementioned caveat.

**Review by mrambacher — COMMENTED** [review]
Are there any tests to cover this code?

**Comment by akankshamahajan15** [comment]
> Are there any tests to cover this code?

I added tests in io_tracer_test to cover testing of writing records in IOTracer and io_tracer_parser_test to cover writing the records through calling DB::StartIOTracer and then DB::EndIOTracer and parsing those records.

**Pull request closed without merging**
