### PR TITLE
Reordering header inclusion to reduce compile time at least 20% on release target

### PR DESCRIPTION
**Pull request by cngzhnp**
As I see from guideline, developers are trying to follow Google CppGuide which is written in [there](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes). 

However, IMHO this is not a good practice. If you can follow this guide, recurrence of header files is will be more and more. This can cause to increase compile time exponentially. So, in my pull request, I try to follow this [guide](https://stackoverflow.com/a/14243688), release target compilation time is reduced %20 in my machine. 

In my VM Linux machine, master branch was compiled in 11min 32s approximately. With my changes, same target can be compiled at 9min 11s which equals to %20.

Also, if you can follow that one header file per one cpp file, it will be reduced much more than now.

### CODE REVIEW

**Comment by riversand963** [comment]
Thanks @cngzhnp for contributing to RocksDB. Do you plan to continue working on this? If not, I'll close this PR. If yes, there are several concerns. First, all tests are still failing due to compilation errors that must be fixed before we can merge. Second, the benefit of the change is not very clear to me. Before the compilation errors are fixed, it's impossible for us to see it. Third, I would suggest that we break this PR into multiple smaller ones.

**Comment by cngzhnp** [comment]
Hello @riversand963, I was waiting for a reply from someone else on the team. I saw in Travis, a lot of compilation error raise up but I need a feedback from someone else. I'd agree with all concerns about the changes and third one is also OK for me. I can break into small chunks of this PR and lets see what brings to us. So, you can close this one, what is your feeling?

**Comment by cngzhnp** [comment]
My other question, if I will continue to work on this, Google guideline that you follow will be outdated. Does it make things worse? Because, this is not only related with order of include files, also unnecessary re-included user-defined headers, standard headers, missing forward declarations etc. What is your feeling to change them on the code?

**Comment by riversand963** [comment]
@cngzhnp I can imagine it's going to be a huge change in both coding style and binary which can affect many users. Therefore, I am not sure whether it's better or worse at this moment, especially when the claimed benefit of faster compilation has not been proved. Regarding the benefit of faster compilation time, we need to show it on most main-stream compilers on popular OS and architectures. We also need to make sure that the generated binary does not lead to performance regression or test failures. I think we also need to understand why compilation becomes faster with your change to be aware of as many trade-offs as possible.
When all the above are confirmed, we are still faced with one problem. If there is no performance improvement, do other RocksDB users want to move in the same direction with this change?

**Comment by cngzhnp** [comment]
You are right that before fixing all compilation errors, we cannot say that it is beneficial. So, my proposal is leave this PR as it is, until I fix all errors. Afterwards, you can compare results of master and my branch on mainstream OS and architecture, then make your decision. If positive then I can split those changes into small chunks and we can move on, otherwise it will end up like closing PR.

**Pull request closed without merging**
