### PR TITLE
Update the versions of the test dependencies used for RocksJava

### PR DESCRIPTION
**Pull request by adamretter**
Update the versions of the dependencies used for testing RocksJava.

@pdillinger Please can you add the following to your S3 bucket:
1. https://repo1.maven.org/maven2/junit/junit/4.13.1/junit-4.13.1.jar
2. https://repo1.maven.org/maven2/org/hamcrest/hamcrest/2.2/hamcrest-2.2.jar
3. https://repo1.maven.org/maven2/cglib/cglib/3.3.0/cglib-3.3.0.jar
4. https://repo1.maven.org/maven2/org/assertj/assertj-core/2.9.0/assertj-core-2.9.0.jar

Thanks.

### CODE REVIEW

**Comment by pdillinger** [comment]
Facebook-internal notes if someone else helps here: https://fburl.com/wiki/0020nwqh

But I think Adam was granted write permission to the bucket

**Comment by adamretter** [comment]
> But I think Adam was granted write permission to the bucket

I don't have access to internal notes. Which account should I use to access the bucket?

**Comment by adamretter** [comment]
@akankshamahajan15 @jay-zhuang This one is now ready to merge please.

**Review by jay-zhuang — APPROVED** [review]
👍
I uploaded the binaries and tested the build locally, which is able to download the binaries from the S3.

Just wondering if we could cache the dependencies? (or maybe use a JAVA dependency management tool?)

**Pull request closed without merging**
