### PR TITLE
do not call get() in recovery mode

### PR DESCRIPTION
**Pull request by lightmark**
This is a previous fix that has a typo

### CODE REVIEW

**Comment by siying** [comment]
Please work with Islam to make sure it fixes the bug.

**Comment by IslamAbdelRahman** [comment]
LGTM, I checked the tests and they pass with this change

**Comment by IslamAbdelRahman** [comment]
@lightmark, can you please check valgrind failure and verify it's unrelated ?

**Comment by siying** [comment]
The valgrind failure looks unrelated to me. I'm merging it.

**Pull request closed without merging**
