### PR TITLE
upgrade gtest 1.7.0 => 1.8.1 for json result writing

### PR DESCRIPTION
**Pull request by dothebart**

### CODE REVIEW

**Comment by dothebart** [comment]
ok, this has been a more tough one than thought at first sight. All warnings AppVeyor found have been fixed by now.

**Comment by dothebart** [comment]
@siying how do you think about this? can it be merged? Its going to drift again with every test change that is done where MSVC can't determine the types of constants properly.

**Comment by siying** [comment]
Sorry I complete overlooked the PR. If you fix conflicts, I can at least merge what has changed, and then, we can continue working on the rest.

**Comment by dothebart** [comment]
oki, lets see which fine new warnings appveyour brings us ;)

**Comment by dothebart** [comment]
hm, I can't see how the travis compile error relates to this pr?

**Comment by siying** [comment]
@dothebart the master happened to be broken during the time you rebase. Now it should have been fixed. Really sorry for the back-and-force, but do you mind rebasing again a little bit?

**Comment by dothebart** [comment]
@siying all seems well now!

**Pull request closed without merging**
