### PR TITLE
[WIP] Update TARGETS by running script

### PR DESCRIPTION
**Pull request by riversand963**
Run `python buckifier/buckify_rocksdb.py`.

Test plan (on dev server)
```
$python buckifier/buckify_rocksdb.py
$git status
```
Verify `git status` does not show any modification.

### CODE REVIEW

**Comment by riversand963** [comment]
cc @siying and @gfosco

**Comment by siying** [comment]
Looks like someone updated TARGETS without updating the bucketify template: https://github.com/facebook/rocksdb/commit/0d16fad51b5b8ad41ccc70faab11599f7120b093#diff-25ca2925c669fb9025f484ff8f63d455

Running the bucketize script might revert what the commit wanted to do. Is there any problem with the new TARGETS file? if not, we should do the other way around: update the bucketify template.

**Comment by riversand963** [comment]
@siying , there is nothing wrong with the new TARGETS. I am working on a feature which requires to run the buckifier script each time we release to fbcode.

**Comment by riversand963** [comment]
Will submit a PR to update the templates. @siying

**Comment by riversand963** [comment]
Closing due to #5647

**Pull request closed without merging**
