### PR TITLE
Generate pkg-config file via CMake

### LINKED ISSUE #7934: Generate rocksdb.pc (pkg-config) file in CMake
Target `gen-pc` in Makefile generates `rocksdb.pc`.
https://github.com/facebook/rocksdb/blob/21218316dabca5ffd02e5d10793fb1894e3870ae/Makefile#L2097-L2108

Please, add this target in CMakeLists.txt and also add `install` step for this file.

### PR DESCRIPTION
**Pull request by trynity**
Fixes #7934

### CODE REVIEW

**Review by ajkr — APPROVED** [review]
LGTM, thanks! Would you like to import to Phabricator so you can land it?

**Comment by trynity** [comment]
> LGTM, thanks! Would you like to import to Phabricator so you can land it?

Ah, thanks! First time working on a project with this syncing, so was unsure of the flow. Imported!

**Comment by alexreg** [comment]
Glad to see this implemented finally. Will there be a new release soon? I'd like to get this used in the macOS Homebrew formula for rocksdb.

**Comment by ajkr** [comment]
It will be included in RocksDB 7.3, which should be tagged in early June.

**Pull request closed without merging**
