### PR TITLE
cmake: support more compression type

### PR DESCRIPTION
**Pull request by BusyJay**
This pr enables linking all the supported compression libraries via cmake.

### CODE REVIEW

**Comment by BusyJay** [comment]
Fail case is not related to the changes.

**Comment by siying** [comment]
@tamird @tchaikov @benesch @yuslepukhin if you don't have objection to the change, we are going to merge.

**Comment by tamird** [comment]
Looks OK to me.

**Comment by benesch** [comment]
Ditto!

**Comment by tchaikov** [comment]
lgtm.

**Comment by BusyJay** [comment]
@yuslepukhin ping

**Pull request closed without merging**
