### PR TITLE
Fixed get version on windows, moved throwing exceptions into cc file.

### PR DESCRIPTION
**Pull request by topilski**
Fixes for msys2 and mingw, hide exceptions into cpp  file.

### CODE REVIEW

**Comment by yiwu-arbug** [comment]
Any reason to hide exceptions in cc files?

**Comment by topilski** [comment]
Hi @yiwu-arbug , because i linked librocksdb into my project where i didn't use exceptions (-fno-exceptions), and i can't compile it because in headers you throwing exceptions. https://github.com/fastogt/fastonosql/blob/master/src/core/db/rocksdb/db_connection.cpp#L24

**Comment by siying** [comment]
@yiwu-arbug I think it's not a good idea to throw error or call functions like abort() in public header anyway. They'll be compiled when users compile RocksDB, rather than compiling librocksdb, which isn't what we want.

**Comment by siying** [comment]
@yiwu-arbug also we shouldn't use flag ROCKSDB_LITE (and similar flags) in public headers. They are only available when building librocksdb, and is not available when users build their application.

**Comment by siying** [comment]
@topilski can you come up with a better commit name than "Hot fixes"? It provides no information.

**Comment by topilski** [comment]
Hi @siying , fixed thank you for understanding.

**Pull request closed without merging**
