### PR TITLE
[DeleteFilesInRange] Preserve overlapping file endpoint invariant

### PR DESCRIPTION
**Pull request by ajkr**
Fix for #2833.

- In `DeleteFilesInRange`, use `GetCleanInputsWithinInterval` instead of `GetOverlappingInputs` to make sure we get a clean cut set of files to delete.
- In `GetCleanInputsWithinInterval`, support nullptr as `begin_key` or `end_key`.
- In `GetOverlappingInputsRangeBinarySearch`, move the assertion for non-empty range away from `ExtendFileRangeWithinInterval`, which should be allowed to return an empty range (via `end_index < begin_index`).

Test Plan:

- new unit test

### CODE REVIEW

**Comment by zhangjinpeng1987** [comment]
I don't understand how this pr preserve contact between files that contain the same delete range mark?

**Comment by ajkr** [comment]
I think we should patch 5.7+ with this.

**Comment by zhangjinpeng1987** [comment]
@ajkr Can we merge this pr?

**Comment by ajkr** [comment]
Yes, thanks for reminder. Let me know if you need it backported to any branches.

**Comment by zhangjinpeng1987** [comment]
@ajkr We use delete range mix with delete files in range, so we need this pr. Currently we must fork ourself branch to achieve this approach.

**Comment by ajkr** [comment]
But which rocksdb version do you currently use? 5.9.1?

**Comment by zhangjinpeng1987** [comment]
@ajkr Currently we use 5.8.7.

**Comment by ajkr** [comment]
Thanks @zhangjinpeng1987 . In that case I'll add the fix to 5.8 and 5.9 branches.

**Comment by ajkr** [comment]
https://github.com/facebook/rocksdb/releases/tag/rocksdb-5.8.8

**Pull request closed without merging**
