### PR TITLE
dont use vector::at because it performs bound check at runtime

### PR DESCRIPTION
**Pull request by rockeet**
`vector::at` performs bound check at runtime, if out of bound, it will throw.

So it should use `vector::operator[]` instead.

### CODE REVIEW

**Review by riversand963 — CHANGES_REQUESTED** [review]
Maybe I am wrong, but I don't think the bound checking removed will make a huge difference in terms of performance. Do you have performance data about this?
The concern I have about `at()` is that it may throw exceptions, but RocksDB is not exception safe. (though `[]` does not address this concern either).

**Comment by rockeet** [comment]
> Maybe I am wrong, but I don't think the bound checking removed will make a huge difference in terms of performance. Do you have performance data about this? The concern I have about `at()` is that it may throw exceptions, but RocksDB is not exception safe. (though `[]` does not address this concern either).

Yes, the performance gain is very little, the real benefit is `[]` will not throw and it should **assert fail in debug build** if out of bound.

**Comment by riversand963** [comment]
> it should assert fail in debug build if out of bound.

Is this documented somewhere in C++ standard, or is it the implementation of some versions of the STL vector and/or maybe with custom allocator?
I tried `-O0` on a very simple sample code, but cannot hit assertion error due to out of bound access. Even if I did hit assertion, I am still hesitant to rely on some behavior not documented in the standard.

**Comment by rockeet** [comment]
> assert fail in debug build

**assert fail in debug build** is not in C++ standard, as I know MSVC has such assertion, and MSVC is in RocksDB CI.

**Comment by siying** [comment]
It's true that RocksDB isn't compatible with exception, but I don't see accessing array overflow data is better than that either. Since we don't have a consensus here, I'm closing this PR for now. @ltamasi if you think the PR has value, we can reopen it.

**Pull request closed without merging**
