### PR TITLE
Internal API for generating semi-random salt

### PR DESCRIPTION
**Pull request by pdillinger**
Summary: ... so that a non-cryptographic whole file checksum would be highly resistant
to manipulation by a user able to manipulate key-value data (e.g. a user whose data is
stored in RocksDB) and able to predict SST metadata such as DB session id and file
number based on read access to logs or DB files. The adversary would also need to predict
the salt in order to influence the checksum result toward collision with another file's
checksum.

This change is just internal code to support such a future feature. I think this should be a
passive feature, not option-controlled, because you probably won't think about needing it
until you discover you do need it, and it should be low cost, in space (16 bytes per SST
file) and CPU.

Test Plan: Unit tests added to verify at least pseudorandom behavior. (Actually caught a bug in first draft!) The new "stress" style tests run in ~3ms each on my system.

### CODE REVIEW

**Comment by pdillinger** [comment]
Another possibility I'm considering is putting the salt into the checksum function name, so that it works for any kind of file.

**Comment by pdillinger** [comment]
> Another possibility I'm considering is putting the salt into the checksum function name, so that it works for any kind of file.

This makes it difficult to integrate with outside tools that want to simply apply a stock hash function to a file's contents.

**Review by Cyan4973 — APPROVED** [review]
seems like a reasonable approach to salting

**Review by ajkr — APPROVED** [review]
This one LGTM, although I have yet to understand the protection it provides in #9058.

**Pull request closed without merging**
