### PR TITLE
Create a Configurable base class for use in get/set values from properties and INI files

### PR DESCRIPTION
**Pull request by mrambacher**
This change adds a new Configurable class.  A Configurable object can:
- Be populated by ConfigureFromString or ConfigureFromMap
- Have individual fields updated, via ConfigureOption
- Convert itself into a string suitable for storing in initialization files (GetOptionsString)
- Dump its properties to a Logger
- See if it matches another Configurable (Matches)
- Check/Change its settings if they are not proper (SanitizeOptions)
- Verify that it settings are valid (VerifyOptions)
- Return a pointer to the underlying options object (GetOptions)

The Configurable class uses an OptionsTypeMap (map<string, OptionTypeInfo) in order to implement this functionality.  

The code for this class is based on the code for configuring a TableFactory instance.  A follow-on PR will show this code being used by the TableFactory class.

Any class can be a Configurable simply by inheritance.  By registering an OptionsTypeMap with the base implementation, the object will automatically gain the Configurable functionality.  If no map is registered, the class will behave as it does today (the methods will do nothing).

### CODE REVIEW

**Comment by riversand963** [comment]
Thanks @mrambacher. Could you rebase the PR(s) and add me as a reviewer, please? There are multiple of them, and it would be good if I know which one to review. Thanks.

**Comment by mrambacher** [comment]
I do not know how to do either of the things you requested.  

All of my changes are in a single commit, which is the last one in the list.   Somehow when I generated the PR it lists a whole bunch of commits that are not different.  They are caused by my master being slightly different and I cannot figure out how to get rid of them.

And I cannot figure out how to add anyone as a reviewer.  I can see "Reviewers" on the tab, but there is nowhere to click.

Also, there is a related PR https://github.com/facebook/rocksdb/pull/5362, in which I have made the TableFactory class into a Configurable and wrote a ConfigurableDBOptions class (I will do the ColumnFamilyOptions separately as it is a lot more work).  This PR shows where I am trying to take the effort.  The next step is integrating Configurable into the ObjectRegistry to be able to more fully populate the Options on startup from INI files.

**Comment by riversand963** [comment]
If you cannot request review from anybody, sending me a list of PRs will suffice. I mentioned this since I noticed that there seem to be old PRs which we have agreed to close and move to smaller PRs. I just do not want to miss your changes.
I think the other irrelevant commits are there because your branch is lagging behind. If you `git fetch upstream`, then rebase your branch onto the upstream/master, they should be gone after a forced push.

**Comment by mrambacher** [comment]
I rebased and think that removed the additional commits.

I have this, plus three other PRs outstanding for this project:
https://github.com/facebook/rocksdb/pull/5293 Changes the ObjectRegistry to be class-based (instead of template).
- https://github.com/facebook/rocksdb/pull/5497 uses this new Configurable class to configure DBOptions.
- https://github.com/facebook/rocksdb/pull/5362 Shows how this new Configurable class works with TableFactory.  This PR is not intended to be merged

There will likely be 2+ more PRs next week that will be based on these PRs.  I am creating a Customizable class now that uses the Configurable+ObjectRegistry to load objects. I will then also update the ConfigurableTableFactory to show table factories being used that way.  There will also be another round after that allowing for loaded objects (merging DynamicLibrary with Customizable).

Thanks for your help in reviewing these.

**Comment by mrambacher** [comment]
Superceded with #5753

**Pull request closed without merging**
