### PR TITLE
Fix wrong level args

### PR DESCRIPTION
**Pull request by cheng-chang**
The level args should be output level instead of input levels.

Test Plan:
make check

### CODE REVIEW

**Review by ajkr — COMMENTED** [review]
LGTM, thanks. Can we verify bottom level compression now works with universal compaction?

**Review by ajkr — APPROVED** [review]

**Comment by ajkr** [comment]
Sorry I forgot. This should have a release note since it's a user-visible bug. Here's the one I'm including on the 6.12 backport:

```
### Bug fixes
* Fixed a bug in universal compaction to bottom level where the compression settings for the first input level were used rather than the compression settings for the bottom level.
```

**Comment by pdillinger** [comment]
> Sorry I forgot. This should have a release note since it's a user-visible bug. Here's the one I'm including on the 6.12 backport:

Going to add it to master, and 6.13?

**Comment by ajkr** [comment]
@cheng-chang do you have time to fix up the rest of the release notes? Sorry but there are too many investigations I'm involved in lately.

**Pull request closed without merging**
