### PR TITLE
Use BUILD_SHARED_LIBS to set lib type in CMake

### PR DESCRIPTION
**Pull request by mellery451**
Modify CMake file to make use of standard BUILD_SHARED_LIBS option. Remove redundant targets.

FIXES: https://github.com/facebook/rocksdb/issues/4484

### CODE REVIEW

**Comment by sagar0** [comment]
@mellery451 Appveyor build failed. Can you take a look at the windows build errors?

**Comment by mellery451** [comment]
@sagar0 Looks ok now - I had missed the option for XPRESS. Thanks.

**Comment by Sebiee** [comment]
I'm interested in this feature if it get's to an official version.

**Comment by gocarlos** [comment]
@mellery451 still interested in pushing this forward

**Comment by gocarlos** [comment]
depends in this: https://github.com/conan-io/conan-center-index/pull/410

**Comment by Sebiee** [comment]
In the mean time, the same effect was achieved by merged pull-request: https://github.com/facebook/rocksdb/pull/6122.

Just sayin', for the ones that are interested. Waiting for an official version which includes that commit.

**Comment by ltamasi** [comment]
Closing since #6122 is already merged.

**Pull request closed without merging**
