### PR TITLE
Fix bug that BlockBasedTableBuilder don't flush to file when max_dict_bytes>0,max_dict_buffer_bytes=0

### LINKED ISSUE #9296: V6.26.0 SstFileWriter::FileSize() always return 0.
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

SstFileWriter put 40GB data with big value(avg 212KB, max 15MB)
### Expected behavior
SstFileWriter::FileSize() return 40GB
### Actual behavior
SstFileWriter::FileSize() return 0
And allocate 40GB RAM.
image

### Steps to reproduce the behavior
EnvOptions use default
options:
[Version]
  rocksdb_version=6.26.0
  options_file_version=1.1

[DBOptions]
  max_background_flushes=2
  compaction_readahead_size=2097152
  wal_bytes_per_sync=0
  bytes_per_sync=0
  max_open_files=1024
  stats_history_buffer_size=1048576
  stats_dump_period_sec=600
  stats_persist_period_sec=600
  delete_obsolete_files_period_micros=21600000000
  max_total_wal_size=0
  strict_bytes_per_sync=false
  delayed_write_rate=16777216
  avoid_flush_during_shutdown=false
  writable_file_max_buffer_size=1048576
  max_subcompactions=3
  base_background_compactions=-1
  max_background_compactions=5
  max_background_jobs=8
  file_checksum_gen_factory=nullptr
  db_host_id=__hostname__
  bgerror_resume_retry_interval=1000000
  best_efforts_recovery=false
  avoid_unnecessary_blocking_io=false
  two_write_queues=false
  atomic_flush=false
  preserve_deletes=false
  allow_ingest_behind=false
  lowest_used_cache_tier=kNonVolatileBlockTier
  avoid_flush_during_recovery=false
  info_log_level=INFO_LEVEL
  access_hint_on_compaction_start=NORMAL
  max_bgerror_resume_count=2147483647
  write_thread_slow_yield_usec=3
  allow_concurrent_memtable_write=true
  WAL_ttl_seconds=600
  manual_wal_flush=false
  dump_malloc_stats=false
  wal_recovery_mode=kPointInTimeRecovery
  log_file_time_to_roll=0
  enable_write_thread_adaptive_yield=true
  recycle_log_file_num=0
  table_cache_numshardbits=6
  max_file_opening_threads=16
  allow_data_in_errors=false
  use_fsync=false
  unordered_write=false
  fail_if_options_file_error=false
  random_access_max_buffer_size=1048576
  new_table_reader_for_compaction_inputs=true
  skip_checking_sst_file_sizes_on_db_open=false
  skip_stats_update_on_db_open=false
  persist_stats_to_disk=false
  track_and_verify_wals_in_manifest=false
  enable_pipelined_write=false
  flush_verify_memtable_count=true
  log_readahead_size=0
  is_fd_close_on_exec=true
  WAL_size_limit_MB=0
  experimental_mempurge_threshold=0.000000
  write_dbid_to_manifest=false
  use_adaptive_mutex=false
  error_if_exists=false
  write_thread_max_yield_usec=100
  enable_thread_tracking=false
  db_write_buffer_size=0
  create_missing_column_families=false
  paranoid_checks=true
  create_if_missing=true
  wal_filter=nullptr
  max_manifest_file_size=1073741824
  allow_2pc=true
  use_direct_io_for_flush_and_compaction=false
  manifest_preallocation_size=4194304
  use_direct_reads=false
  allow_fallocate=true
  max_write_batch_group_size_bytes=1048576
  keep_log_file_num=1000
  allow_mmap_reads=false
  max_log_file_size=0
  allow_mmap_writes=false
  advise_random_on_open=true

[CFOptions "data"]
  compression_opts={max_dict_buffer_bytes=0;enabled=false;parallel_threads=1;zstd_max_train_bytes=0;strategy=0;max_dict_bytes=0;level=32767;window_bits=-14;}
  bottommost_compression=kZSTD
  enable_blob_garbage_collection=false
  blob_file_size=268435456
  sample_for_compression=0
  periodic_compaction_seconds=2592000
  ttl=2592000
  blob_garbage_collection_age_cutoff=0.250000
  compaction_options_universal={allow_trivial_move=false;incremental=false;stop_style=kCompactionStopStyleTotalSize;compression_size_percent=-1;max_size_amplification_percent=200;max_merge_width=4294967295;min_merge_width=2;size_ratio=1;}
  compression=kSnappyCompression
  max_sequential_skip_in_iterations=8
  max_bytes_for_level_multiplier_additional=1:1:1:1:1:1:1
  max_bytes_for_level_multiplier=10.000000
  max_bytes_for_level_base=1073741824
  memtable_whole_key_filtering=false
  max_successive_merges=0
  inplace_update_num_locks=10000
  arena_block_size=1048576
  target_file_size_multiplier=1
  prefix_extractor=rocksdb.FixedPrefix.16
  max_write_buffer_number=6
  blob_compression_type=kNoCompression
  level0_stop_writes_trigger=40
  level0_slowdown_writes_trigger=10
  compaction_options_fifo={allow_compaction=false;age_for_warm=0;max_table_files_size=1073741824;}
  level0_file_num_compaction_trigger=5
  write_buffer_size=134217728
  memtable_huge_page_size=0
  max_compaction_bytes=3355443200
  min_blob_size=0
  bottommost_compression_opts={max_dict_buffer_bytes=0;enabled=true;parallel_threads=1;zstd_max_train_bytes=262144;strategy=0;max_dict_bytes=16384;level=32767;window_bits=-14;}
  hard_pending_compaction_bytes_limit=274877906944
  target_file_size_base=134217728
  soft_pending_compaction_bytes_limit=68719476736
  enable_blob_files=false
  paranoid_file_checks=false
  check_flush_compaction_key_order=true
  blob_garbage_collection_force_threshold=1.000000
  disable_auto_compactions=false
  memtable_prefix_bloom_size_ratio=0.000000
  report_bg_io_stats=false
  compaction_pri=kMinOverlappingRatio
  compaction_filter_factory=nullptr
  comparator=leveldb.BytewiseComparator
  sst_partitioner_factory=nullptr
  bloom_locality=0
  compaction_style=kCompactionStyleLevel
  min_write_buffer_number_to_merge=2
  max_write_buffer_size_to_maintain=0
  max_write_buffer_number_to_maintain=6
  merge_operator=nullptr
  memtable_factory=SkipListFactory
  memtable_insert_with_hint_prefix_extractor=nullptr
  compression_per_level=kNoCompression:kNoCompression:kLZ4Compression:kLZ4Compression:kLZ4Compression:kLZ4Compression:kLZ4Compression
  num_levels=7
  force_consistency_checks=true
  optimize_filters_for_hits=false
  compaction_filter=SplitCompactionFilter
  level_compaction_dynamic_level_bytes=true
  inplace_update_support=false
  table_factory=BlockBasedTable

### PR DESCRIPTION
**Pull request by lgqss**
Fix #9296
when max_dict_bytes > 0, max_dict_buffer_bytes = 0, target_file_size = 0
v6.8.1 exceeds_buffer_limit=false
v6.26.0 exceeds_buffer_limit=true

### CODE REVIEW

**Comment by riversand963** [comment]
> max_dict_bytes > 0, max_dict_buffer_bytes = 0, target_file_size = 0

This combination seems to suggest that you don't want to limit the amount of memory used by uncompressed blocks.
cc @ajkr can correct me if I miss anything.

**Comment by lgqss** [comment]
> > max_dict_bytes > 0, max_dict_buffer_bytes = 0, target_file_size = 0
> 
> This combination seems to suggest that you don't want to limit the amount of memory used by uncompressed blocks. cc @ajkr can correct me if I miss anything.

It's different from v6.8.1. @ajkr

**Review by ajkr — CHANGES_REQUESTED** [review]
It was an intentional change  in v6.13 and HISTORY.md file noted the change (#7323). This change appears to revert the bug fix so `SstFileWriter` would not use dictionary compression even when enabled.

What is the problem you're trying to solve? Is it that you need `SstFileWriter::FileSize()` to indicate how much data has been written? Or the memory is too much?

If the problem is the memory is too much, I suggest either disabling dictionary compression, or setting max_dict_buffer_bytes to a value that reflects how much memory you're willing to spend. The value zero never intended to mean dictionary compression uses no memory (because that's impossible in our understanding); it was a special value to indicate no limit on the memory.

**Comment by lgqss** [comment]
Thank you for your answer. I'll try to disable dictionary compression.

**Pull request closed without merging**
