### PR TITLE
Update HISTORY.md and version.h for 8.9.fb release

### PR DESCRIPTION
**Pull request by jaykorean**
# Summary

Creating cut for 8.9 release

# Test Plan

CI

### CODE REVIEW

**Comment by jaykorean** [comment]
FYI @adamretter

**Review by ajkr — APPROVED** [review]

**Comment by adamretter** [comment]
@jaykorean Do you want me to start testing 8.9.fb before or after this PR is merged?

**Comment by jaykorean** [comment]
@adamretter Let's do after. Merging this soon.

**Comment by adamretter** [comment]
Thanks @akankshamahajan15 :-) I will commence testing of RocksJava for that now...

**Comment by adamretter** [comment]
@akankshamahajan15 @jaykorean okay I have completed the build and testing of RocksJava in the 8.9.fb branch. All looks good thanks

**Pull request closed without merging**
