### PR TITLE
RFC: Re-establish block cache eviction statistics for filters

### PR DESCRIPTION
**Pull request by pdillinger**
Summary: Some time ago our BLOCK_CACHE_*_BYTES_EVICT statistics were
lost, IIRC to fix memory correctness in case of Cache outliving DB.
However, it is difficult to evaluate the precise memory improvement by
e.g. Ribbon filters without knowing how much block cache memory is used
by filters, which used to be available as
BLOCK_CACHE_FILTER_BYTES_INSERT - BLOCK_CACHE_FILTER_BYTES_EVICT.

This change is intended to solve that problem of measuring filter memory
usage, by populating BLOCK_CACHE_FILTER_BYTES_EVICT again, and to be a
gradual first step of bringing back more eviction statistics.

Why not all eviction statistics now? First, there is some risk of subtle
performance regression, but on the other hand, if we don't need a flag
to turn off eviction statistics specifically, it would be best to avoid
adding such a flag. Gradual re-introduction of eviction statistics I
believe helps us to navigate this safely.

What are the specific risks?

First, ImmutableCFOptions::statistics goes from Statistics* to
shared_ptr<Statistics> (why in a moment). This *should* not be a problem
because ImmutableCFOptions is long-lived and reading a shared_ptr is
(according to my understanding) just as fast as reading a raw pointer
(except double the size to deal with updates - intrusive_ptr might be
nice).

Second, we add shared_ptr<Statistics> to ParsedFullFilterBlock to update
the eviction statistics on destruction. This means the block cache could
hold on to Statistics after a DB is destroyed, which should not be a big
deal because StatisticsImpl only holds on to some memory. This should
only be an issue if someone is repeatedly opening and closing DBs with
fresh Statistics each time, faster than they get evicted from LRUCache.
Copying/destroying the shared_ptr on insertion to/eviction from the block
cache is far from free, but at least for filter blocks, this should be
tolerably rare and generally faster than the other parts of block
loading+insertion (under which we can amortize eviction costs, except in
terms of latency).

Wart: BLOCK_CACHE_FILTER_BYTES_EVICT will not track evictions for
deprectated block-based filter, though BLOCK_CACHE_FILTER_BYTES_INSERT
tracks insertions. It should be extremely rare for a DB to mix the two
kinds of filter blocks.

Re-expansion of eviction stats might move the shared_ptr<Statistics> out
of ParsedFullFilterBlock, which would be fine. When this is done, it
might be worth coupling this with a "type checking" layer to ensure
memory safety even in the case of cache key collision (report
Corruption or quietly fetch the right thing).

This change also improves the precision of tracked memory for filters in
block cache by including the memory for metadata objects.

Test Plan: Updated test DBBlockCacheTest.IndexAndFilterBlocksStats.

TODO benchmark

### CODE REVIEW

**Comment by pdillinger** [comment]
The problem is that the benchmarking shows that simply copying & destroying the shared_ptr<Statistics> into ParsedFullFilterBlock, without recording ticks, slows things down measurably.

Create test db:

    TEST_TMPDIR=/dev/shm ./db_bench -bloom_bits=10 -partition_index_and_filters=1 -value_size=24 -statistics -benchmarks=fillrandom -num=10000000

Benchmark cmd:

    TEST_TMPDIR=/dev/shm ./db_bench -use_existing_db=1 -bloom_bits=10 -partition_index_and_filters=1 -statistics -benchmarks=readrandom -duration=30 -cache_size=3000000 -threads=20 -cache_numshardbits=8

This is a worst case scenario in which we are thrashing on filters.

This PR:
1075928 ops/sec
rocksdb.block.cache.filter.miss COUNT : 11699420
rocksdb.block.cache.filter.hit COUNT : 104903294
rocksdb.block.cache.filter.add COUNT : 11699420
rocksdb.block.cache.filter.bytes.insert COUNT : 49418342272
rocksdb.block.cache.filter.bytes.evict COUNT : 49417501696
This PR minus ticking eviction stats:
1093263 ops/sec
This PR minus setting, destroying (and ticking) shared_ptr<Statistics> in ParsedFullFilterBlock:
1204658 ops/sec
Base revision (without this PR):
1233016 ops/sec

Clearly, most of the loss in speed is due to copying and destroying the shared_ptr<Statistics>. Any thoughts like

a) This should be fine because we shouldn't be thrashing on filters (no noticeable difference in db_bench with sufficient cache size to avoid thrashing)
b) Create an option to enable/disable these eviction statistics
c) Find another solution

?

**Comment by mrambacher** [comment]
> The problem is that the benchmarking shows that simply copying & destroying the shared_ptr into ParsedFullFilterBlock, without recording ticks, slows things down measurably.
> 
> Create test db:
> 
> ```
> TEST_TMPDIR=/dev/shm ./db_bench -bloom_bits=10 -partition_index_and_filters=1 -value_size=24 -statistics -benchmarks=fillrandom -num=10000000
> ```
> 
> Benchmark cmd:
> 
> ```
> TEST_TMPDIR=/dev/shm ./db_bench -use_existing_db=1 -bloom_bits=10 -partition_index_and_filters=1 -statistics -benchmarks=readrandom -duration=30 -cache_size=3000000 -threads=20 -cache_numshardbits=8
> ```
> 
> This is a worst case scenario in which we are thrashing on many small filters.
> 
> This PR:
> 1075928 ops/sec
> rocksdb.block.cache.filter.miss COUNT : 11699420
> rocksdb.block.cache.filter.hit COUNT : 104903294
> rocksdb.block.cache.filter.add COUNT : 11699420
> rocksdb.block.cache.filter.bytes.insert COUNT : 49418342272
> rocksdb.block.cache.filter.bytes.evict COUNT : 49417501696
> This PR minus ticking eviction stats:
> 1093263 ops/sec
> This PR minus setting, destroying (and ticking) shared_ptr in ParsedFullFilterBlock:
> 1204658 ops/sec
> Base revision (without this PR):
> 1233016 ops/sec
> 
> Clearly, most of the loss in speed is due to copying and destroying the shared_ptr. Any thoughts like
> 
> a) This should be fine because we shouldn't be thrashing on filters (no noticeable difference in db_bench with sufficient cache size to avoid thrashing)
> b) Create an option to enable/disable these eviction statistics
> c) Find another solution
> 
> ?

I was looking into something similar with Statistics* and shared_ptr (I thought I sent you a PR but apparently I did not).  There are a handful of values in the ImmutableCFOptions that should be shared_ptr (because that is what they are in ColumnFamilyOptions) or not there at all (because they are DBOptions).  There are some that are also short-cuts (like SystemClock* and FileSystem*).  I view the Statistics* (and Logger*) between those classes (they should not really be there and they change types/shortcuts).

What I thought might be a good plan/compromise was to store the value both ways in the ImmutableCFOptions (std::shared_ptr<Statistics> and Statistics*).  The shared_ptr could be there more as a reference control and rarely (if ever) used (and could even be private).

I will post my PR and add you to it later today and you can see if something like that will help you.  

Note I have not reviewed the rest of your code (but will if you wish) and am just commenting on the shared_ptr issue at this point.

**Comment by pdillinger** [comment]
In case it wasn't clear, ImmutableCFOptions itself is not the problem here, but repeatedly copying and destroying downstream.

I'm thinking about another solution here where Statistics objects are optionally allocated in a pool where they are immortal but reusable upon no more crucial references. This way the only danger of stale Statistics references in Cache is some misplaced ticker ticks. (Non-immortal Statistics would not be allowed in Cache so would no support eviction stats.)

**Comment by ltamasi** [comment]
I think this is a very reasonable direction in general that we can make generic down the road. Some random thoughts:
1) I'm a little bit skeptical about using this to quantify Ribbon's memory savings. I mean it works if all the filter blocks fit in the cache both without and with Ribbon but with production workloads that might not be the case, and it's not obvious to me how it would all shake out. I think we might end up in a situation where we would end up with a higher number of smaller filter blocks getting cached ('hiding' the gains in efficiency).
2) I think we do have to be prepared for some amount of churn in general (since SSTs come and go) but especially when partitioned filters are in use. It would be interesting to see the overhead for a more typical workload as well besides the worst case.
3) Semantically, I don't think filter blocks should co-own the `Statistics` object. That is, if the 'real' owners like the application/DB have released it, there is no point in keeping it alive just so we can emit ticks that no one will look at. Since all we need is a protection against dangling pointers, I think it would be sufficient for `ParsedFullFilterBlock` to hold a `weak_ptr`. (Note: this won't help with the performance in general since there are still atomic refcount operations; we could use it to avoid emitting a tick though if the `Statistics` object is gone.)

**Comment by siying** [comment]
Can block cache own another statistics object just for this counter?

**Comment by pdillinger** [comment]
> Can block cache own another statistics object just for this counter?

Then you don't have per-DB statistics on block cache memory usage when DBs share a block cache. And you'd have to connect up more data pipelines to get your statistics.

Plus there are complications with elaborating the Cache interface.

> I think it would be sufficient for ParsedFullFilterBlock to hold a weak_ptr

I agree that's conceptually better. I could investigate its performance if the performance of this approach is considered "acceptable," which I'm not convinced it really is.

> I'm a little bit skeptical about using this to quantify Ribbon's memory savings

Suppose someone has a non-negligible share of filters not resident. Suppose that the memory savings in block cache is filled by more resident filters (a crazy assumption - more likely similar ratio to block cache as a whole). Either (a) you have saved CPU and I/O with fewer cache misses, which we can look for, or (b) someone could make their block cache smaller with the ribbon savings with no ill effects (caching not helpful beyond some point).

In theory, if the change is good, RocksDB users should be able to see whatever improvement is important to them without these statistics, but that does not seem to be reality. People want to see a live stat that we can point them to.

**Comment by pdillinger** [comment]
> I'm thinking about another solution here where Statistics objects are optionally allocated in a pool where they are immortal but reusable upon no more crucial references. This way the only danger of stale Statistics references in Cache is some misplaced ticker ticks. (Non-immortal Statistics would not be allowed in Cache so would not support eviction stats.)

And I would fix the misplaced ticks problem by storing a "generation id" of the Statistics object so that the stats are only bumped if the object has the same "generation id" upon block cache insertion. Generation id would be incremented when the object goes back into pool for reuse (using custom deleter with shared_ptr).

Any thoughts on this approach @ltamasi @siying ?

**Comment by pdillinger** [comment]
> > I think it would be sufficient for ParsedFullFilterBlock to hold a weak_ptr
> 
> I agree that's conceptually better. I could investigate its performance if the performance of this approach is considered "acceptable," which I'm not convinced it really is.

Though as I suspected:

> If any std::weak_ptr references the control block created by std::make_shared after the lifetime of all shared owners ended, the memory occupied by T persists until all weak owners get destroyed as well, which may be undesirable if sizeof(T) is large.

**Comment by ltamasi** [comment]
> In theory, if the change is good, RocksDB users should be able to see whatever improvement is important to them without these statistics, but that does not seem to be reality. People want to see a live stat that we can point them to.

Right, I get that. My concern (which might be unwarranted) was that this particular metric might be difficult to interpret.

**Comment by ltamasi** [comment]
> > I'm thinking about another solution here where Statistics objects are optionally allocated in a pool where they are immortal but reusable upon no more crucial references. This way the only danger of stale Statistics references in Cache is some misplaced ticker ticks. (Non-immortal Statistics would not be allowed in Cache so would not support eviction stats.)
> 
> And I would fix the misplaced ticks problem by storing a "generation id" of the Statistics object so that the stats are only bumped if the object has the same "generation id" upon block cache insertion. Generation id would be incremented when the object goes back into pool for reuse (using custom deleter with shared_ptr).
> 
> Any thoughts on this approach @ltamasi @siying ?

One potential complication with using an object pool: some applications pass in an instance of a custom statistics class which is publicly derived from `Statistics`.

**Comment by pdillinger** [comment]
> One potential complication with using an object pool: some applications pass in an instance of a custom statistics class which is publicly derived from `Statistics`.

This should not be a problem, because in my implementation-in-progress, the Statistics object has to "opt in" to declaring itself as OK to reference from the block cache.

**Comment by ltamasi** [comment]
> Though as I suspected:
> 
> > If any std::weak_ptr references the control block created by std::make_shared after the lifetime of all shared owners ended, the memory occupied by T persists until all weak owners get destroyed as well, which may be undesirable if sizeof(T) is large.

Sure, that's a known issue. It's no worse than using `shared_ptr` though. There are three possibilities:
1) We use `shared_ptr`. `Statistics` stays alive and the memory does not get reclaimed regardless of whether `make_shared` was used to instantiate the object or not.
2) We use `weak_ptr` and `make_shared`: `Statistics` gets destroyed once all (shared) owners have released it but the memory does not get reclaimed.
3) We use `weak_ptr` and do not use `make_shared`: `Statistics` gets destroyed and the memory gets reclaimed once all (shared) owners have released the object. (Downside is of course that we have separate allocations for the object and the control block.)

P.S. Another point regarding make_shared: it does not support custom deleters. (This concerns the object pool based design.)

**Comment by ltamasi** [comment]
> > One potential complication with using an object pool: some applications pass in an instance of a custom statistics class which is publicly derived from `Statistics`.
> 
> This should not be a problem, because in my implementation-in-progress, the Statistics object has to "opt in" to declaring itself as OK to reference from the block cache.

Hm, when I said "some applications", I really meant "a lot of important applications." :) So this design would only support `rocksdb::Statistics` itself but not derived classes, correct?

**Comment by pdillinger** [comment]
> Hm, when I said "some applications", I really meant "a lot of important applications." :) So this design would only support `rocksdb::Statistics` itself but not derived classes, correct?

The implemented pool would only support StatisticsImpl, but other implementations could implement their own pool based on a new virtual function in Statistics (details to come). It would only be ~20 LoC duplicated to implement another pool for another derived class.

**Comment by siying** [comment]
> > > I'm thinking about another solution here where Statistics objects are optionally allocated in a pool where they are immortal but reusable upon no more crucial references. This way the only danger of stale Statistics references in Cache is some misplaced ticker ticks. (Non-immortal Statistics would not be allowed in Cache so would not support eviction stats.)
> > 
> > 
> > And I would fix the misplaced ticks problem by storing a "generation id" of the Statistics object so that the stats are only bumped if the object has the same "generation id" upon block cache insertion. Generation id would be incremented when the object goes back into pool for reuse (using custom deleter with shared_ptr).
> > Any thoughts on this approach @ltamasi @siying ?
> 
> One potential complication with using an object pool: some applications pass in an instance of a custom statistics class which is publicly derived from `Statistics`.

I'm not sure what the interface would look like if we assume Statistics can be destroyed but still safe to be operate on. If we can come up with a reasonable interface for that, it sounds good.

**Comment by siying** [comment]
Another question asked before but forgot the answer: is the purpose to calculate current cache usage by index and filter? If that is the case, rather than calculating eviction stats, can we just annotate each cache entry and calculate it by go over every entry in the cache? If it is an operation only done very infrequently, the performance overhead might be OK.

**Comment by pdillinger** [comment]
> Another question asked before but forgot the answer: is the purpose to calculate current cache usage by index and filter? If that is the case, rather than calculating eviction stats, can we just annotate each cache entry and calculate it by go over every entry in the cache? If it is an operation only done very infrequently, the performance overhead might be OK.

- You won't get any insight into which DB instances are using how much memory, though that's probably mostly OK.
- The existing API for such an operation, ApplyToAllCacheEntries is dubious for this in a couple of ways:
  - We have to assume values (void*) in the cache adhere to some format that we can check for categorization. It's probably safe to look for specific patterns in first 32 bits for instance, as long as the charge >=4, even if something else is sharing the Cache.
  - Each cache shard is locked during its entire iteration, which essentially blocks all DB operations. This would need to be fixed to yield periodically.
- (Unless I'm missing something) you would need to connect up a new data pipeline to get the data.

I think the last one annoys me the most.

**Comment by siying** [comment]
> > Another question asked before but forgot the answer: is the purpose to calculate current cache usage by index and filter? If that is the case, rather than calculating eviction stats, can we just annotate each cache entry and calculate it by go over every entry in the cache? If it is an operation only done very infrequently, the performance overhead might be OK.
> 
> * You won't get any insight into which DB instances are using how much memory, though that's probably mostly OK.
> * The existing API for such an operation, ApplyToAllCacheEntries is dubious for this in a couple of ways:
>   
>   * We have to assume values (void*) in the cache adhere to some format that we can check for categorization. It's probably safe to look for specific patterns in first 32 bits for instance, as long as the charge >=4, even if something else is sharing the Cache.
>   * Each cache shard is locked during its entire iteration, which essentially blocks all DB operations. This would need to be fixed to yield periodically.
> * (Unless I'm missing something) you would need to connect up a new data pipeline to get the data.
> 
> I think the last one annoys me the most.

The annotation of each block can probably contain a hash to identify DB + type. Let's say, 28-bit for DB name hash and 4 bits for block type.

I think reporting mechanism is indeed a problem, but might be solvable.

**Pull request closed without merging**
