### PR TITLE
Another attempt at adding the Java API and tests to the travis build

### PR DESCRIPTION
**Pull request by adamretter**

### CODE REVIEW

**Comment by igorcanadi** [comment]
Failed :(

**Comment by adamretter** [comment]
@igorcanadi hmm I am pretty sure the make commands are correct. Any idea why this fails?

**Comment by igorcanadi** [comment]
OOM. Let me forward you one e-mail

**Comment by fyrz** [comment]
@adamretter are you still working on that ?

**Comment by adamretter** [comment]
@fyrz Due to the out of memory error, I decided to try and switch us to containerized builds on Travis which offer more memory. My work in progress on a containerized build is https://github.com/facebook/rocksdb/pull/570, but there are still some open issues with Travis there.

**Comment by adamretter** [comment]
However this build does now seem to pass without an out of memory

**Comment by adamretter** [comment]
@igorcanadi The Arcanist diff review is here - https://reviews.facebook.net/D43173

**Pull request merged**
