### PR TITLE
refactor SavePoints

### PR DESCRIPTION
**Pull request by jsteemann**
Savepoints are assumed to be used in a stack-wise fashion (only
the top element should be used), so they were stored by `WriteBatch`
in a member variable `save_points` using an std::stack.

Conceptually this is fine, but the implementation had a few issues:
- the `save_points_` instance variable was a plain pointer to a heap-
  allocated `SavePoints` struct. The destructor of `WriteBatch` simply
  deletes this pointer. However, the copy constructor of WriteBatch
  just copied that pointer, meaning that copying a WriteBatch with
  active savepoints will very likely have crashed before. Now a proper
  copy of the savepoints is made in the copy constructor, and not just
  a copy of the pointer
- `save_points_` was an std::stack, which defaults to `std::deque` for
  the underlying container. A deque is a bit over the top here, as we
  only need access to the most recent savepoint (i.e. stack.top()) but
  never any elements at the front. std::deque is rather expensive to
  initialize in common environments. For example, the STL implementation
  shipped with GNU g++ will perform a heap allocation of more than 500
  bytes to create an empty deque object. Although the `save_points_`
  container is created lazily by RocksDB, moving from a deque to a plain
  `std::vector` is much more memory-efficient. So `save_points_` is now
  a vector.
- `save_points_` was changed from a plain pointer to an `std::unique_ptr`,
  making ownership more explicit.

### CODE REVIEW

**Comment by maysamyabandeh** [comment]
Thanks @jsteemann for the contribution. How about keeping the std::stack interface but set it to use std::vector as its container?

**Comment by jsteemann** [comment]
@maysamyabandeh : ok, I have updated my PR according to your suggestions.

To be honest, I think the best solution would be to use a small autovector to hold the SavePoints.
Right now, creating the first savepoint will cause two dynamic memory allocations, one for the `save_points_` stack container, and one for adding the first member to the stack's underlying container.
The first dynamic memory allocation could be spared if `save_points_` were not a pointer to a container, but the actual container. This would increase the size of `WriteBatch` a bit, but a stack/vector is normally only a few bytes bigger than a pointer. So in reality it shouldn't matter.
The second dynamic memory allocation could be saved if `save_points_` were a stack using an autovector instead of a stack using an std::vector. This would even make the first few savepoints require now dynamic memory allocations.
The solution however requires including autovector.h in the header of write_batch.h, but I think it would be worth it. Should I give it a try?

**Comment by maysamyabandeh** [comment]
Thanks @jsteemann for thorough investigation.
1. We have an internal autovector in util/autovector.h. Can it be used in place of std::vector?
2. WriteBatch is a very general class and I am weary of making changes that might have unexpected side-effects to some users. So perhaps for now we can keep save_points_ a pointer.

**Comment by jsteemann** [comment]
@maysamyabandeh : ok, I have switched the underlying container for the SavePoints stack from `std::vector` to `rocksdb::autovector` now.
This should diminish the cost of creating a savepoint from two heap allocations (one for initial on-heap stack plus one for the std::deque container) to just one heap allocation for the on-heap autovector.
Apart from that, memory usage for the autovector should be a lot lower than the memory usage for the std::deque, which allocates a lot of memory initially.

**Pull request closed without merging**
