### PR TITLE
[codemod] comment unused parameters to turn on -Wunused-parameter flag

### PR DESCRIPTION
**Pull request by Dayvedde**
This PR comments out the rest of the unused arguments which allow us to turn on the -Wunused-parameter flag. This is the second part of a codemod relating to https://github.com/facebook/rocksdb/pull/3557. 

Test Plan: 
```
make -j64 check
make clean && ROCKSDB_NO_FBCODE=1 make check -j64
```

### CODE REVIEW

**Comment by miasantreble** [comment]
Tested under freeBSD: the following files need fix:
env/env_posix.cc (Line 862)
env/io_posix.cc (Line 47, 228, 408, 465, 673, 866, 880)
util/arena.cc (Line 52, 127, 160)

**Comment by miasantreble** [comment]
commit ac7b1fbc2dedff6739962749b05db00bb2ad99ed now builds successfully on FreeBSD

**Comment by Dayvedde** [comment]
Slowly but surely fixing all these errors...

**Comment by Dayvedde** [comment]
Hi @miasantreble, I have fixed all of the errors!

**Pull request closed without merging**
