### PR TITLE
Add private DB::Open() overloads to check potential errors

### PR DESCRIPTION
**Pull request by rockeet**
One of us used DB::Open() with column families, and use `Options` as `DBOptions`, `ColumnFamilyOptions` was set in that `Options`, and the options in `ColumnFamilyDescriptor` was not set, we used several days to find this issue.

With the private `Open`, such errors will be detected earlier.

### CODE REVIEW

**Comment by IslamAbdelRahman** [comment]
Thanks @rockeet,
can we use deleted functions instead of making them private
http://en.cppreference.com/w/cpp/language/function#Deleted_functions

**Comment by rockeet** [comment]
@IslamAbdelRahman  Yes,  we can, deleted functions should be better, thanks!

**Comment by yiwu-arbug** [comment]
There are some test failures. @rockeet do you mind rebase to see if they goes away?

**Comment by lightmark** [comment]
d

**Comment by rockeet** [comment]
class RandomAccessFileReader's move constructor has critical bug: it calls move assignment, this may segfault on member "std::unique_ptr<RandomAccessFile> file_"

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.

**Pull request closed without merging**
