### PR TITLE
Typo fixed in  HISTORY.md

### PR DESCRIPTION
**Pull request by khalid586**
A typo has been fixed.

### CODE REVIEW

**Comment by ajkr** [comment]
Consider picking from our up-for-grabs issues: https://github.com/facebook/rocksdb/issues?q=is%3Aissue+is%3Aopen+label%3Aup-for-grabs

**Comment by khalid586** [comment]
@ajkr Can you review the PR and merge it if it is okay!

**Comment by khalid586** [comment]
@ajkr can you please tell me if the PR is okay or should I close it?

**Comment by ajkr** [comment]
There might be a reviewer willing to take minor typo fix PRs, so you can leave it open if you want to keep trying. But, I am not such a reviewer.

**Pull request closed without merging**
