### PR TITLE
Introduce FAIL_ON_WARNINGS CMake variable (default ON)

### PR DESCRIPTION
**Pull request by vaintroub**
If FAIL_ON_WARNINGS is OFF, compilation will succeed if there were compile
warnings.

### CODE REVIEW

**Comment by yuslepukhin** [comment]
@yiwu-arbug It is OK with me once the builds complete. FYI, I no longer have rights to merge per new FB security policy.

**Comment by yiwu-arbug** [comment]
@yuslepukhin Thank you for review! Will merge.

**Comment by yiwu-arbug** [comment]
@vaintroub Thank you for your contribution.

**Comment by yiwu-arbug** [comment]
@vaintroub Can you rebase the PR so we can merge? Thanks!

**Pull request closed without merging**
