### PR TITLE
Remove TableReader::Prefetch

### PR DESCRIPTION
**Pull request by yiwu-arbug**
Summary:
`TableReader::Prefetch` is an internal API added in https://github.com/facebook/rocksdb/commit/f29b33c73b78310f678831ad2bab3597f4f84788. The API is not used anywhere, and its a pain to maintain the corresponding `TableTest::PrefetchTest`. Remove it.

Test Plan:
`make all check`

Signed-off-by: Yi Wu <yiwu@pingcap.com>

### CODE REVIEW

**Comment by yiwu-arbug** [comment]
Travis failure seems unrelated.

**Comment by siying** [comment]
But the plan has been to eventually expose it through DB::Prefetch(). We just never had the chance to implement it.

**Comment by siying** [comment]
We initially started to think about such an interface because MongoDB has a touch command (https://docs.mongodb.com/manual/reference/command/touch/) and MongoRocks didn't implement it. I think MongoRocks had it implemented using some sort of hack. We realized that it is useful to provide a way for users to warm the cache while they have a cold start. I still believe such a functionality has its use.

**Comment by yiwu-arbug** [comment]
@siying thanks to clarify!

**Pull request closed without merging**
