### PR TITLE
fix batchresult handle leak

### PR DESCRIPTION
**Pull request by min-mwei**
This is related to PR https://github.com/facebook/rocksdb/pull/1642

Sorry about this extra PR, as my workflow was messed up when I checked in another work item by accident.

### CODE REVIEW

**Comment by min-mwei** [comment]
>Also you might like to look at whether the assert (isOwningHandle()); lines in AbstractWriteBatch are >still appropriate.
Thanks for the suggestion. I did just review the code a bit. Just by luck the positive case still work as the constructors are internal. However the negative case would have issue, it won't cause an assert. For example, in theory the WriteBatch got from the BatchResult should not be settable. 

A bigger question is whether to convert the asserts to actual exceptions, which have a bit negative perf impact.

**Comment by adamretter** [comment]
@min-mwei Can you rebase on master so that Travis works again.

Also I think you should remove those asserts, as they now make no sense.

**Comment by min-mwei** [comment]
updated the code changes as requested including the rebase. Let me know if there is any issue as this is my first time to use the Travis. Thanks.

**Comment by adamretter** [comment]
@min-mwei looks good :-)

@IslamAbdelRahman Could you merge this one?

**Pull request closed without merging**
