### PR TITLE
EnvWrapper should provide constructor with file system and sys…

### PR DESCRIPTION
**Pull request by CoderSong2015**
EnvWrapper needs to have the function of being initialized with parameter（env）‘s file system. Otherwise it will call LegacyFileSystemWrapper‘s function（or its father class file system‘s function）instead of the function in your own file system， unless you implement the function which you just need in your own file system in LegacyFileSystemWrapper。

### CODE REVIEW

**Comment by mrambacher** [comment]
There is already a class/method to do something similar to this in NewCompositeEnv.  I agree there might be more function signatures needed here (though I am not sure if/why they need to be public. 

Generally speaking, I think the EnvWrapper should be mostly deprecated/unused as most use cases should implement custom FileSystem or SystemClock.

Does the CompositeEnv/Wrapper code address your issues?  Do we simply need more public APIs for composite wrapping?

**Comment by CoderSong2015** [comment]
> There is already a class/method to do something similar to this in NewCompositeEnv. I agree there might be more function signatures needed here (though I am not sure if/why they need to be public.
> 
> Generally speaking, I think the EnvWrapper should be mostly deprecated/unused as most use cases should implement custom FileSystem or SystemClock.
> 
> Does the CompositeEnv/Wrapper code address your issues? Do we simply need more public APIs for composite wrapping?

In db_test_util.h, the class SpecialEnv inherits EnvWrapper so that it's difficult for us to use the tests without implementing all functions in LegacyFileSystemWrapper. Maybe let SpecialEnv inherits CompositeEnvWrapper is a another choice.（I'm not sure if we should discard EnvWrapper ）

**Comment by mrambacher** [comment]
> 

I'm working on changing SpecialEnv to a SpecialFileSystem.  It will take a few PRs.  I'm not sure what the problem is with the other Env classes are that wouldn't be doing the right thing. If they were wrong, it seems like the tests would already fail...

**Comment by CoderSong2015** [comment]
> > 
> 
> I'm working on changing SpecialEnv to a SpecialFileSystem. It will take a few PRs. I'm not sure what the problem is with the other Env classes are that wouldn't be doing the right thing. If they were wrong, it seems like the tests would already fail...

It seems that now SpecialEnv have itself functions about files. But when you want to call your own file system functions, you will call env_->GetFileSystem() to get the filesystem obj, but here because  SpecialEnv's construction function have no way to pass env's filesystem to EnvWrapper so that you will get the default  LegacyFileSystemWrapper. This is why I add those construction functions.
Maybe you will not have errors until you implement a new file system with some new functions?

**Comment by CoderSong2015** [comment]
@mrambacher Maybe add a function GetFileSystem in SpecialEnv to override the EnvWrappers'  is another alternative way.

**Comment by mrambacher** [comment]
@CoderSong2015 I am not sure I understand what the problem you are trying to solve is and if it is for testing or deployment purposes.  Are you saying you cannot run with a custom file system in a EnvWrapper?  Can you give me a concrete example of what is failing for you?

Generally speaking, with the introduction of the FileSystem and SpecialClock classes, there should be little (if any) need to extend an Env class.  Extensions that currently exist should probably be re-written as FileSystems.  

As for SpecialEnv, I have a PR in the works to turn it into a CompositeEnv with a SpecialFileSystem and EmulatedSystemClock.  I am not sure when I will have a chance to commit it yet.

**Comment by CoderSong2015** [comment]
@mrambacher Thanks for your answer.
I run rocksdb  on a distributed file system so that I must implement my own file system interface. And the tests will fail just because  SpecialEnv will call its own functions about file. 
eg:
In the test DBWALTestWithEnrichedEnv/SkipDeletedWALs
The EnrichedEnv will call DeleteFile to delete wal, it's ok when the env's DeleteFile is same as file system's DeleteFile, but it goes wrong when the env's DeleteFile does different things from file system' DeleteFile. I think your pr about SpecialEnv/SpecialFileSystem could solve the problem. 
Finally, I still recommend adding more function signatures in EnvWrapper, unless the EnvWrapper completely replaced by CompositeEnv.

**Pull request closed without merging**
