### PR TITLE
Support for AIX and Solaris

### PR DESCRIPTION
**Pull request by koldat**
This pull request contains fixes for AIX and Solaris Sparc compilation. It also makes some changes in build to make these configurable.
Issue: #966

### CODE REVIEW

**Comment by adamretter** [comment]
Wow! :-)

I think perhaps though that you did not mean to add ` java/pom.xml`. Also it would be very cool if you could add built instructions for AIX and Sparc to `INSTALL.md`.

**Comment by siying** [comment]
Can you resolve the conflict?

**Comment by siying** [comment]
Thank you for your contribution! I'll be glad to merge it.

**Comment by koldat** [comment]
I haave added instructions for build and resolved conflict in Makefile.

**Comment by koldat** [comment]
@adamretter regarding pom.xml. It is hard to answer all reasons, but let me try it. I was expecting some push back :-)
We are trying to build JNI for all platform on our build systems. I know that one can try to leverage Dockers, Vagrant, etc. The problem is that it is not possible to cover everything. We have to support AIX6, 7, different flavors of Linuxes, Solaris (Sparc), Windows. It is much easier to prepare build machines and connect it to different Jenkins jobs. We are also able to easily debug when the problem happens.
Because of that I created deploy pom artifact for each platform that is executed there. Maybe you will ask why not just classifier sent by command line. It is because of flexibility. Different build systems have different ways how to configure Maven and you are not pushing anyone to use hardcoded repositories, hosts, etc. Maven is prepared for that and you can use setting.xml together with profiles to use what you need without putting any information into build scripts (makefiles and poms)..
Final pom in root simply downloads all artifacts from platform builds and creates final jar file containing all JNIs. It is also easy to do release builds. In our case just one job in Jenkins, that does the everything.
I am OK if you will want to delete poms. We can keep these in our master branch. Or we can come up with some solution that work for everyone.

**Comment by ayappanec** [comment]
@koldat I am able to build rocksdb in AIX 6.1 (oslevel -s => 6100-09-05-1524 and bos.adt.base 6.1.9.200) with your aix_support_master. I used only AIX Toolbox rpms. Below are the parameters used.

export PORTABLE=1
export CC=gcc
export AR="ar -X64"
export EXTRA_ARFLAGS=-X64
export EXTRA_CFLAGS=-maix64
export EXTRA_CXXFLAGS=-maix64
export PLATFORM_LDFLAGS="-static-libstdc++ -static-libgcc"
export SNAPPY_DOWNLOAD_BASE="-k https://github.com/google/snappy/releases/download"
export LZ4_DOWNLOAD_BASE="-k https://github.com/lz4/lz4/archive"
export JAVA_HOME=/usr/java8_64
export PATH=/opt/freeware/bin:$PATH

It's actually a straight shot for me. No issues at all .
But while running the "make jtest", it fails with the below error 
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.lang.J9VMInternals.ensureError(J9VMInternals.java:141)
        at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:130)
        at org.rocksdb.RocksMemoryResource.<clinit>(RocksMemoryResource.java:16)
        at org.rocksdb.BackupableDBOptionsTest.<clinit>(BackupableDBOptionsTest.java:23)
        at java.lang.Class.forNameImpl(Native Method)
        at java.lang.Class.forName(Class.java:278)
        at org.rocksdb.test.RocksJunitRunner.main(RocksJunitRunner.java:58)
Caused by: java.lang.RuntimeException: librocksdbjni-aix64.so was not found inside JAR.
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJarToTemp(NativeLibraryLoader.java:110)
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
        at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
        at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
        at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)

We are actually creating librocksdbjni-aix.so so perhaps we can remove the "64" field from Environment.java
"  } else if (isAix() && is64Bit()) {
return String.format("%sjni-aix64", name);"

And also recommend you to update the readmd about the perlz site rpms and downgrading bos.adt.base stuffs. Because we in IBM recommend customers to use AIX Toolbox rather than third party sites.

**Comment by adamretter** [comment]
@koldat So I think there are a couple comments on the `pom.xml` that I have:

1) I don't think these will work for anyone else buy you. If I run `mvn` on them, it expects me to have already built all the binary native components and placed them appropriately. Certainly platforms like Windows, AIX and Sparc are not available to everyone.

2) the `java/pom.xml` uses the dependency plugin to aggregate the native libraries, however I cannot see how the pom files in `java/deploy` are included. There is no parent or module relationship between `java/pom.xml` and `java/deploy/pom.xml`, so I can only assume there is a manual process of steps to run between these. It seems that `java/pom.xml` will fail for those that do not have the native libraries for all platforms (e.g. also Windows, AIX, Sparc etc).

I think the pom.xml's that you have added are specific to your build process. I would love to see improvements in our support for Maven, but I think it needs to be a more general solution that works for all users.

Apologies if I have made any false assumptions or misunderstood something. Please feel free to correct me :-)

**Comment by siying** [comment]
@adamretter @koldat this commit touches lots of files and is easy to cause conflict. Is there a way to hold the controversy part for now (say, remove the pom related changes) to get it in first, and continue the discussion in a follow-up PR? I'm worried that there will be endless conflicts going forward.

**Comment by adamretter** [comment]
@siying Yes, I think if we just drop the `pom.xml` files all should be good. I think @koldat said that he would be happy for those to live in his own SCM for the time being anyway.

**Comment by koldat** [comment]
I have removed all new pom files.

**Comment by koldat** [comment]
@ayappanec I updated install.md with using AIX toolbox instead of opensource site.

**Comment by koldat** [comment]
@siying I did another master merge and solved conflicts so you should be prepared for accepting request

**Comment by ayappanec** [comment]
@koldat Thanks for the update

**Comment by koldat** [comment]
I have pushed one more fix for chroot in AIX. It fixes env and backupable DB tests

**Comment by koldat** [comment]
@siying is any additional changes needed? Or it is ready to be merged?

**Comment by ayappanec** [comment]
@koldat Two more changes will help better. 

1) JNI library name in aix according to Makefile is "librocksdbjni-aix.so" But in Environment.java it is checking for "librocksdbjni-aix64.so". So there is a conflict. I think we can remove the "64" .

2) In Makefile, we can add ROCKSDB_JAR field for AIX OS also (but without the "ARCH" value)

**Comment by siying** [comment]
@koldat we have some problem with our internal system so that I'm not able to import it this our internal CI. While we are working with the team owning the system to resolve the problem, it may be helpful if you try to recreate a new PR with the same change.

**Comment by siying** [comment]
@koldat another thing needs to change is to add the new flag you added to build_tools/fbcode_config.sh and build_tools/fbcode_config4.8.1.sh. This is FB internal thing, so if you don't want to add it there, it is fine. I'll add it shortly after your change is merged.

**Comment by siying** [comment]
@koldat can you rebase your fork branch that sent the PR to latest master?

**Comment by koldat** [comment]
@ayappanec we are not using this makefile build system for Java. I have reverted poms, because we have to discuss it more with @adamretter. I am not able to test it properly now. Can you please do PR?

**Comment by koldat** [comment]
@siying I am not sure what to do now. I did merge with latest master. What do you mean by rebasing the branch? What is expected output?
We did not changed build_tools/fbcode_config.sh, please go ahead and do changes that are required.
Do you still need to create new PR or problems were solved?

**Comment by ayappanec** [comment]
@koldat Okay fine. I will wait for this PR to be successfully merged first.

**Comment by koldat** [comment]
@siying I tried to rebase, but a lot of conflicts were there thus I did "git merge --squash aix_support_master" to create new branch that is rebased, but squashed.

We can close this one and continue in #2194

**Comment by koldat** [comment]
Change was pulled. See #2194

**Pull request closed without merging**
