### PR TITLE
Option string/map/file can set env from object registry

### PR DESCRIPTION
**Pull request by ajkr**
- By providing the "env" field in any text-based options (i.e., string, map, or file), we can use `NewCustomObject` to deserialize the text value into an actual `Env` object.
- Currently factory functions for `Env` registered with object registry should only return pointer to static `Env` objects. That's because `DBOptions::env` is a raw pointer so we cannot easily delegate cleanup.
- Note I did not add `env` to `db_option_type_info`. It wasn't needed for (de)serialization, and I believe we don't want to do verification on `env`, even by checking name. That's because the user should be able to copy their DB from Linux to Windows, change envs, and not see an option verification error.

Test Plan:
- updated unit test to cover deserializing a custom env from string
- manually verified downgrade compatibility. User needs to provide ignore_unknown_options for it to work. Somebody remind ZippyDB :).

### CODE REVIEW

**Comment by ajkr** [comment]
Hm I realized after removing `env` from `db_option_type_info` that it does not record the `Name()` in OPTIONS file anymore. To me that is fine, what do you think? In that case we don't need to add the `Name()` method to `Env`.

Alternatively we can add it to `db_option_type_info`, but then we have to pick an option for verification. We don't want any verification IMO, so that way is a bit confusing too.

**Comment by siying** [comment]
Then can we still load Env when reading from option files?

**Comment by siying** [comment]
I mean is loading customized Env when reading from option files still supported?

**Comment by ajkr** [comment]
> I mean is loading customized Env when reading from option files still supported?

Sorry for the delay. I tried it out just now and verified it is still supported. I just manually edited an OPTIONS file to add an `env=x` field, registered an `Env` with name `x`, and verified the `Env` used was instantiated using the factory function I registered.

The limitation right now though is we don't write the `Env` name when generating an OPTIONS file. So, if someone uses `LoadLatestOptions()` to let RocksDB use the OPTIONS file generated by a previous run, it will not find an env option to deserialize. Probably that's ok because that use case wasn't supported before this PR either.

**Comment by siying** [comment]
If Env name is never written to option file, then the PR is good to me. We can add the env separately.

**Comment by ajkr** [comment]
> If Env name is never written to option file, then the PR is good to me. We can add the env separately.

Right, it is never written.

**Pull request closed without merging**
