### PR TITLE
[WIP] Record stack traces for hanging/slow tests in CircleCI

### PR DESCRIPTION
**Pull request by ajkr**
This PR adds a wrapper script, "tools/run_with_pstack.sh", that prints a test's stack traces using `pstack` after a test runs for two minutes. It changes the Makefile to support running test binaries with a driver program, and changes CircleCI config to use "tools/run_with_pstack.sh" as the driver in many of its test runs.

A parallel test's stack traces go to the log file ("t/log-run-*") and can be found in the CircleCI test artifacts upload upon failure. A non-parallel test's stack traces go directly to the console.

### CODE REVIEW

**Comment by ajkr** [comment]
hm it's printing a lot of output that it doesn't print locally. Need to figure that out still.

```
circleci 2363025 2238525  0 17:35 pts/0    00:00:00 sleep 60
circleci 2363026 1984742  0 17:35 pts/0    00:00:00 sleep 60
circleci 2363027 1984787  0 17:35 pts/0    00:00:00 sleep 60
circleci 2363028 1984806  0 17:35 pts/0    00:00:00 sleep 60
circleci 2363029 1984870  0 17:35 pts/0    00:00:00 sleep 60
circleci 2363030 1984871  0 17:35 pts/0    00:00:00 sleep 60
circleci 2363031 2304788  0 17:35 pts/0    00:00:00 sleep 60
```

**Comment by pdillinger** [comment]
If something does hang and this wrapper prints something every minute, the job will run for hours before being killed instead of 10 minutes with no output. See also https://github.com/facebook/rocksdb/blob/main/build_tools/gnu_parallel#L1892

**Comment by ajkr** [comment]
> hm it's printing a lot of output that it doesn't print locally. Need to figure that out still.

Fixed.

> If something does hang and this wrapper prints something every minute, the job will run for hours before being killed instead of 10 minutes with no output. See also https://github.com/facebook/rocksdb/blob/main/build_tools/gnu_parallel#L1892

Fixed by removing the loop, and changing the threshold to two minutes.

**Comment by pdillinger** [comment]
This is pretty ugly. What about something that runs in process and registers a TestEventListener with gtest and if no updates are received on the listener for some period (such as 8 minutes) then it prints that it is aborting due to timeout and kills itself, and the stack trace handler should kick in to provide a stack trace.

**Comment by ajkr** [comment]
> What about something that runs in process and registers a TestEventListener with gtest and if no updates are received on the listener for some period (such as 8 minutes) then it prints that it is aborting due to timeout and kills itself, and the stack trace handler should kick in to provide a stack trace

Yes it can work for the gtest-based tests, which I guess is enough.

**Pull request closed without merging**
