### PR TITLE
Download bzip2 packages from Internet Archive (#4306)

### PR DESCRIPTION
**Pull request by RandyAbernethy**
Summary:
Since bzip.org is no longer maintained, download the bzip2 packages from a snapshot taken by the internet archive until we figure
out a more credible source.

>> We need this fix to build RocksJava from source for Rocksandra which is dependent on RocksDB v5.14.3

### CODE REVIEW

**Comment by RandyAbernethy** [comment]
CLA signed, can we unblock this?

**Comment by sagar0** [comment]
@RandyAbernethy -- Thanks for your contribution. But we typically don't accept backports to very old branches. Would it be possible to make this change directly in your/your org's fork?

**Comment by sagar0** [comment]
I know that Instagram's main Rocksandra repository already picked up this particular fix in their fork. Are you using an older version of it by any chance? 
@wpc @DikangGu

**Comment by RandyAbernethy** [comment]
@sagar0 The Rocksandra build grabs 5.14 from maven central (or maybe their internal Artifactory/Nexus). We need this patch to build 5.14 from source. (it is a cherry picked patch from Rocksdb master 6 days after the 5.14 final commit)

**Comment by RandyAbernethy** [comment]
@sagar0 We are working from the Rocksandra master HEAD. This is a pretty trivial patch and 5.14.fb will not build without it.

**Comment by siying** [comment]
If 5.15.fb already has it, I'm OK backporting it too. But I'm surprised that Rocksandra head is still on 5.14.fb, which may be something can be easily fixed.

**Comment by RandyAbernethy** [comment]
Great, can we merge? LMK if there's anything else I can do to push this through.

**Comment by sagar0** [comment]
We checked with the Rocksandra team, and they mentioned that the RocksDB branch they us is here: https://github.com/DikangGu/rocksdb/commits/ig_stable , and it already has this bzip fix. I believe you too should be using that branch as it might have some additional fixes to improve Rocksandra's performance instead of directly using RocksDB's 5.14.fb.
@wpc , @DikangGu , @cooldoger  please correct me if I am wrong.

**Comment by RandyAbernethy** [comment]
@DikangGu to confirm, do you want folks in the community working to adopt Rocksandra to use the authoritative RocksDB repo (here) or https://github.com/DikangGu/rocksdb/commits/ig_stable ?

If the later, I'll close this pull.

**Comment by siying** [comment]
I can merge it anyway. Not a big deal. I am not sure we will release a new Java 5.14.x release though. So the best chance to resolve the problem is to work with @wpc , @DikangGu , @cooldoger

**Comment by RandyAbernethy** [comment]
Great, worst case, the patch keeps the branch build-able.

**Comment by RandyAbernethy** [comment]
Thanks all.

**Pull request merged**
