### PR TITLE
Fix db_stress failure in async_io in FilePrefetchBuffer

### PR DESCRIPTION
**Pull request by akankshamahajan15**
Summary: Fix db_stress failure in async_io in FilePrefetchBuffer. 

From the logs, assertion was caused when
- prev_offset_ = offset but somehow prev_len != 0 and explicit_prefetch_submitted_ = true. That scenario is when we send async request to prefetch buffer during seek but in second seek that data is found in cache. prev_offset_ and prev_len_ get updated but we were not setting explicit_prefetch_submitted_ = false because of which buffers were getting out of sync.
It's possible a read by another thread might have loaded the block into the cache in the meantime.

Particular assertion example:
```
prev_offset: 0, prev_len_: 8097 , offset: 0, length: 8097, actual_length: 8097 , actual_offset: 0 , 
curr_: 0, bufs_[curr_].offset_: 4096 ,bufs_[curr_].CurrentSize(): 48541 , async_len_to_read: 278528, bufs_[curr_].async_in_progress_: false  
second: 1, bufs_[second].offset_: 282624 ,bufs_[second].CurrentSize(): 0, async_len_to_read: 262144 ,bufs_[second].async_in_progress_: true , 
explicit_prefetch_submitted_: true , copy_to_third_buffer: false
```
As we can see curr_ was expected to read 278528 but it read 48541. Also buffers are out of sync.
Also `explicit_prefetch_submitted_` is set true but prev_len not 0.

Test Plan: 
- Ran db_bench for regression to make sure there is no regression;
- Ran db_stress failing without this fix,
- Ran build-linux-mini-crashtest 7- 8 times locally + CircleCI

Reviewers:

Subscribers:

Tasks:

Tags:

### CODE REVIEW

**Comment by akankshamahajan15** [comment]
I am not able to figure out what causes it to call `TryReadFromCacheAsync` with prev_len_ > 0 and `explicit_prefetch_submitted_` true. If explicit_prefetch_submitted_ is true then  prev_len_ should always be 0. Only case where it is not is if found in the cache during reseek.  I tried to add logs but its kind of spamming the terminal. 
So basically i found the root cause but not able to find what exactly is causing it.

**Comment by anand1976** [comment]
@akankshamahajan15 Can you explain the problem a bit more in the description? What was the sequence of events that caused the db_stress failure?

**Comment by anand1976** [comment]
> I am not able to figure out what causes it to call `TryReadFromCacheAsync` with prev_len_ > 0 and `explicit_prefetch_submitted_` true. If explicit_prefetch_submitted_ is true then prev_len_ should always be 0. Only case where it is not is if found in the cache during reseek. I tried to add logs but its kind of spamming the terminal. So basically i found the root cause but not able to find what exactly is causing it.

Oh interesting. Its possible a read by another thread might have loaded the block into the cache in the meantime. In that case, will the reseek update prev_len_ and prev_offset_ but explicit_prefetch_submitted_ will remain true?

**Comment by akankshamahajan15** [comment]
> > I am not able to figure out what causes it to call `TryReadFromCacheAsync` with prev_len_ > 0 and `explicit_prefetch_submitted_` true. If explicit_prefetch_submitted_ is true then prev_len_ should always be 0. Only case where it is not is if found in the cache during reseek. I tried to add logs but its kind of spamming the terminal. So basically i found the root cause but not able to find what exactly is causing it.
> 
> Oh interesting. Its possible a read by another thread might have loaded the block into the cache in the meantime. In that case, will the reseek update prev_len_ and prev_offset_ but explicit_prefetch_submitted_ will remain true?

Oh. I didn't know another thread could load the block but that seems like the only case. Yes we don't set  explicit_prefetch_submitted_ = false in that case. Let me set it to false and see if that works.

**Review by anand1976 — APPROVED** [review]
LGTM

**Pull request closed without merging**
