### PR TITLE
Add getters to the C API for env, universal compaction options and fifo compaction options

### PR DESCRIPTION
**Pull request by stanislav-tkach**

### CODE REVIEW

**Comment by stanislav-tkach** [comment]
I have tried to figure out the reason of CircleCi failures, but I was able to find only the following in the logs:
```
[ RUN      ] DBWriteTestInstance/DBWriteTest.WriteThreadHangOnWriteStall/2
db_write_test: db/write_thread.cc:441: size_t rocksdb::WriteThread::EnterAsBatchGroupLeader(rocksdb::WriteThread::Writer *, rocksdb::WriteThread::WriteGroup *): Assertion `w->link_newer' failed.
Received signal 6 (Aborted)
#0   /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38) [0x14e6a839e438] ??	??:0	
#1   /lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x14e6a83a003a] ??	??:0	
#2   /lib/x86_64-linux-gnu/libc.so.6(+0x2dbe7) [0x14e6a8396be7] ??	??:0	
#3   /lib/x86_64-linux-gnu/libc.so.6(+0x2dc92) [0x14e6a8396c92] ??	??:0	
#4   ./db_write_test() [0xb13d59] rocksdb::WriteThread::EnterAsBatchGroupLeader(rocksdb::WriteThread::Writer*, rocksdb::WriteThread::WriteGroup*)	/home/circleci/project/db/write_thread.cc:461	
#5   ./db_write_test() [0x896935] rocksdb::DBImpl::PipelinedWriteImpl(rocksdb::WriteOptions const&, rocksdb::WriteBatch*, rocksdb::WriteCallback*, unsigned long*, unsigned long, bool, unsigned long*)	/home/circleci/project/db/db_impl/db_impl_write.cc:?	
#6   ./db_write_test() [0x888ee7] rocksdb::DBImpl::WriteImpl(rocksdb::WriteOptions const&, rocksdb::WriteBatch*, rocksdb::WriteCallback*, unsigned long*, unsigned long, bool, unsigned long*, unsigned long, rocksdb::PreReleaseCallback*)	/home/circleci/project/db/db_impl/db_impl_write.cc:151	
#7   ./db_write_test() [0x887fea] rocksdb::DBImpl::Write(rocksdb::WriteOptions const&, rocksdb::WriteBatch*)	/home/circleci/project/db/db_impl/db_impl_write.cc:53	
#8   ./db_write_test() [0x885d95] ~Status	/home/circleci/project/./include/rocksdb/status.h:46	
#9   ./db_write_test() [0x8854ae] rocksdb::DBImpl::Put(rocksdb::WriteOptions const&, rocksdb::ColumnFamilyHandle*, rocksdb::Slice const&, rocksdb::Slice const&)	/home/circleci/project/db/db_impl/db_impl_write.cc:23	
#10  ./db_write_test() [0x7773e0] rocksdb::DB::Put(rocksdb::WriteOptions const&, rocksdb::Slice const&, rocksdb::Slice const&)	/home/circleci/project/./include/rocksdb/db.h:326	
#11  ./db_write_test() [0x58f685] ~Status	/home/circleci/project/./include/rocksdb/status.h:46	
#12  /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb8c80) [0x14e6a8d0ac80] ??	??:0	
#13  /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x14e6a982e6ba] ??	??:0	
#14  /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x14e6a84704dd] ??	??:0	
```
As far as I can see, it is unrelated to my changes. Am I missing something or should these failures be ignored?

**Comment by pdillinger** [comment]
> As far as I can see, it is unrelated to my changes. Am I missing something or should these failures be ignored?

This should be fixed in 53089038def1a5ffa05afb27beaa63ed64dff764. Ignorable since I believe your PR is based before that commit.

**Comment by pdillinger** [comment]
There's now a conflict. Merge or rebase and I can approve.

**Comment by stanislav-tkach** [comment]
Done.

**Review by pdillinger — APPROVED** [review]
👍

**Pull request closed without merging**
