### PR TITLE
Remove previously deprecated Java where RocksDB also removed it, or where no direct equivalent existed.

### PR DESCRIPTION
**Pull request by alanpaxton**
For RocksDB v7 major release. Remove previously deprecated Java API methods and associated tests
- where equivalent/alternative functionality exists and is already tested AND
- where the core RocksDB function/feature has also been removed
- OR the functionality exists only in Java so the previous deprecation only affected Java methods

RETAIN deprecated Java which reflects functionality which is deprecated by, but also still supported by, the core of RocksDB.

### CODE REVIEW

**Comment by alanpaxton** [comment]
The intent of the PR is to restrict removals per the @jay-zhuang comment from a previous PR.

Here is list of options/api we removed, I think the java API is already updated:

max_mem_compaction_level
soft_rate_limit
hard_rate_limit
rate_limit_delay_max_milliseconds
purge_redundant_kvs_while_flush
base_background_compactions
skip_log_error_on_recovery
preserve_deletes
iter_start_seqnum
table_cache_remove_scan_count_limit
new_table_reader_for_compaction_inputs
Remove deprecated overloads of DB::AddFile()
Remove DB::CompactRange() marked as DEPRECATED_FUNC
Some other deprecated APIs may not be able to remove in this release.

**Review by adamretter — APPROVED** [review]
LGTM thanks Alan

**Review by jay-zhuang — APPROVED** [review]
LGTM. thanks for removing the deprecated functions.

**Review by ajkr — APPROVED** [review]
LGTM!

**Pull request closed without merging**
