### PR TITLE
Update CircleCI MacOS Xcode version to 11.3.0

### PR DESCRIPTION
**Pull request by jay-zhuang**
To fix CircleCI pyenv installation failure.

### CODE REVIEW

**Review by ajkr — APPROVED** [review]
LGTM, I prefer this solution over #8255.

**Comment by jay-zhuang** [comment]
> LGTM, I prefer this solution over #8255.

If needed, we can setup a nightly build with older xcode. cc. @adamretter

**Comment by ajkr** [comment]
I liked picking an xcode 11.3 version because it works on macOS 10.14 (according to https://xcodereleases.com/). And according to wikipedia, macOS 10.14 is still supported by Apple and can't be upgraded to 10.15 on all hardware.

**Comment by jay-zhuang** [comment]
> I liked picking an xcode 11.3 version because it works on macOS 10.14 (according to [xcodereleases.com](https://xcodereleases.com/)). And according to wikipedia, macOS 10.14 is still supported by Apple and can't be upgraded to 10.15 on all hardware.

Sounds good, another reason is: 12.4 image only has jdk 11, instead of 8 which I think we need to support.

**Pull request closed without merging**
