### PR TITLE
add DB LOG file parser

### PR DESCRIPTION
**Pull request by aginika**
Adding LOG parser and modify some logging parts to make it easier to parse.

Mainly parse below 5 types:
- CompactionEvent
- FlushEvent
- StatisticsEvent(from DB Stats)
- OptionsEvent(Once, at the begging of LOG)
- Delete Event

I wonder where I should put parse_db_log.\* , so I temporarily put these files in utilities/parse_db_log.

### CODE REVIEW

**Comment by igorcanadi** [comment]
Nice job! Can you move parse_db_log.* to tools/ directory? Also, can you run `make format` on the commit?

**Comment by aginika** [comment]
@igorcanadi Thank you! I updated and run `make format`

**Comment by igorcanadi** [comment]
Hm. Are you sure you ran `make format`? I still see rows of 80+ characters and missing empty spaces after `if`...

**Comment by facebook-github-bot-5** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Pull request closed without merging**
