### PR TITLE
ARM64 commits to 5.18.3 to create 5.18.4

### PR DESCRIPTION
**Pull request by adamretter**
In response to https://github.com/facebook/rocksdb/issues/6188

As requested by @siying

### CODE REVIEW

**Comment by jiameixie** [comment]
@adamretter 
Thanks for your efforts to release 5.18.4.
How can we get RocksDB JNI-5.18.4 from Maven central? Thx!

**Comment by adamretter** [comment]
@jiameixe I think there is an issue still on Arm that I made @siying aware of. I was waiting to hear from him on that. After that, once FB tag the release I can get it up onto Maven Central

**Comment by siying** [comment]
@adamretter I can confirm that it is a bug somewhere, but not related to ARM. It's just somehow got triggered because the ARM environment. But it's bug is in core RocksDB, which we need to spend time to figure out. But the release should be good to go.

**Comment by adamretter** [comment]
@siying okie dokie. Can you create the v5.18.4 tag please? I don't have permission :-(

**Comment by jiameixie** [comment]
@adamretter @siying Have v5.18.4 been released? I couldn't find it.

**Comment by guyuqi** [comment]
Hi @siying, could you please help to create the v5.18.4 tag?  Thank you very much!

**Comment by siying** [comment]
One thing I am worried is that if I tagged it, will it become "Latest Release" in github?

**Comment by guyuqi** [comment]
Hi @siying,  could you kindly try to do :
1. click into the tag -> 
2. click the 'Edit tag' button -> 
3. add a value for the 'Release title' field. 
It may convert the tag to a release and moved the 'Latest Release' badge to the correct release.
Thanks a lot !   :-)

**Comment by siying** [comment]
OK. Now I tagged it.

**Comment by adamretter** [comment]
@siying I am not sure what happened but the tag looks wrong :-/

If you compare:

1. the branch https://github.com/facebook/rocksdb/commits/5.18.fb
2. the tag https://github.com/facebook/rocksdb/commits/v5.18.4

You will see that the branch has the correct ARM64 commits at its head, but the tag does not. Instead the tag has an additional commit which hasn't come from the branch

Also the file `include/rocksdb/version.h` in the `5.18.fb` branch seems to have not been updated.
Whilst the same file in the `v5.18.4` tag is very out of date (`5.8.8`), and seems to imply that that tag was taken from the wrong base.

@siying could you take a look please?

**Comment by adamretter** [comment]
@siying could you take a look please?

**Comment by pdillinger** [comment]
@adamretter Should be fixed now. https://github.com/facebook/rocksdb/releases/tag/v5.18.4 Read the note about updated tags.

**Comment by jiameixie** [comment]
@pdillinger @adamretter @siying  Has it been published  to maven central?  I can't find this in https://mvnrepository.com/artifact/org.rocksdb/rocksdbjni.

**Comment by adamretter** [comment]
@jiameixie I am waiting on this one at the moment - https://github.com/facebook/rocksdb/pull/6497

**Comment by adamretter** [comment]
@jiameixie I just released 5.18.4 to Maven Central (it might take up to 2 hours to appear)

**Comment by jiameixie** [comment]
@adamretter That's great! Thanks for your effort.

**Comment by Yikun** [comment]
Cool, greate works, and I will also bring this rocksdbjni version to Apache Storm community (Bump the rocksdb from 5.18.3 to 5.18.4) [1]. : ) 

And looks like the v5.18.4 is still on the road, it doesn't appear in [2] yet.

[1] https://issues.apache.org/jira/browse/STORM-3599
[2] https://mvnrepository.com/artifact/org.rocksdb/rocksdbjni

**Comment by adamretter** [comment]
@yikun mvnrepository is only an aggregator. Take a look in Maven Central which is cannonical for RocksJava

**Pull request merged**
