### PR TITLE
WIP: Fix mingw build for 6.2.x

### PR DESCRIPTION
**Pull request by Ericson2314**
Not sure what master needs.

### CODE REVIEW

**Comment by siying** [comment]
We don't usually release in such an old version, so I encourage you to fix master. Since we don't have a CI for MingW, we rely on community to maintain these platforms. It's likely that it has been broken for a while, so you welcome to send PR to fix master. If it doesn't break other supported platforms, we can just merge it. If needed, we can backport to the latest release branch if it doesn't introduce any conflict. 6.2 is too much behind for a hotfix.

**Comment by siying** [comment]
Wait, Travis has a cmake-mingw flavor and this PR seems to have broken it. I'm confused then. If cmake-mingw has been passing, what the PR fixes?

**Comment by Ericson2314** [comment]
OK That is weird. My best guess is https://github.com/facebook/rocksdb/blob/master/.travis.yml#L115 that it works because our are testing with the posix emulation toolchain, which perhaps `gettimeofday` and `localtime_r`.

**Comment by siying** [comment]
@Ericson2314 anyway, please send PR to master and make sure Travis is green.

**Comment by Ericson2314** [comment]
@siying will do, but I also need to find another CPP variable so that I don't trigger this stuff with posix threads.

**Comment by Ericson2314** [comment]
OK I can't add a job in my PR branch, so I'll just drop that. I think win32 wouldn't actually pass because missing thread stuff; I am actually using https://github.com/lhmouse/mcfgthread which is adds threading support without the full posix emulation (so it is more like win32).

**Comment by Ericson2314** [comment]
So I keep on hitting https://github.com/google/benchmark/issues/127, but `CHECK_SYMBOL_EXISTS` is supposed to work for macros (https://cmake.org/cmake/help/v3.0/module/CheckSymbolExists.html).

**Comment by Ericson2314** [comment]
Ah I was hitting https://sourceforge.net/p/mingw-w64/bugs/817/, and on master `POSIX_C_SOURCE` was defined for mingw, which helps with my mingw version too.

I'm going to close this, and make a much smaller version for master. (Need to keep this inert as NixOS, my distro, will fetch patches from the PR.)

**Comment by Ericson2314** [comment]
See #6075 and 6076

**Pull request closed without merging**
