### PR TITLE
Add BlockBasedTableOptions::index_shortening

### PR DESCRIPTION
**Pull request by al13n321**
Introduce BlockBasedTableOptions::index_shortening to give users control on which key shortening techniques to be used in building index blocks. Before this patch, both separators and successor keys where shortened in indexes. With this patch, the default is set to kShortenSeparators to only shorten the separators. Since each index block has many separators and only one successor (last key), the change should not have negative impact on index block size. However it should prevent many unnecessary block loads where due to approximation introduced by shorted successor, seek would land us to the previous block and then fix it by moving to the next one.

### CODE REVIEW

**Comment by maysamyabandeh** [comment]
@al13n321 Thanks for you contribution. Could you please update the PR with a self-sufficient description that explains the problem and the solution taken in the patch?

**Comment by al13n321** [comment]
Updated.

**Comment by maysamyabandeh** [comment]
There seems to be some test failures on Phabricator:
```
[ RUN      ] DBBlockCacheTest.IndexAndFilterBlocksStats
internal_repo_rocksdb/repo/db/db_block_cache_test.cc:379: Failure
      Expected: TestGetTickerCount(options, BLOCK_CACHE_INDEX_BYTES_EVICT)
      Which is: 315
To be equal to: index_bytes_insert
      Which is: 157

**Comment by al13n321** [comment]
Fixed.

**Comment by maysamyabandeh** [comment]
I wonder if we should update `ColumnFamilyOptions::OldDefaults` to restore the old behavior?

**Comment by maysamyabandeh** [comment]
> I wonder if we should update `ColumnFamilyOptions::OldDefaults` to restore the old behavior?

Never mind. `OldDefaults` works only for db and cf options.

**Pull request closed without merging**
