### PR TITLE
Fix the overflow bug in AwaitState

### PR DESCRIPTION
**Pull request by maysamyabandeh**
https://github.com/facebook/rocksdb/issues/2559 reports an overflow in AwaitState. @nbronson has debugged the issue and presented the fix, which is applied to this patch. Moreover this patch adds more comments to clarify the logic in AwaitState.

I tried with both 16 and 64 threads on update benchmark. The fix lowers cpu usage by 1.6 but also lowers the throughput by 1.6 and 2% respectively. Apparently the bug had favored using the spinning more often.

Benchmarks:
TEST_TMPDIR=/dev/shm/tmpdb time ./db_bench --benchmarks="fillrandom" --threads=16 --num=2000000
TEST_TMPDIR=/dev/shm/tmpdb time ./db_bench --use_existing_db=1 --benchmarks="updaterandom[X3]" --threads=16 --num=2000000
TEST_TMPDIR=/dev/shm/tmpdb time ./db_bench --use_existing_db=1 --benchmarks="updaterandom[X3]" --threads=64 --num=200000

Results
$ cat update-16t-bug.txt | tail -4
updaterandom [AVG    3 runs] : 234117 ops/sec;   51.8 MB/sec
updaterandom [MEDIAN 3 runs] : 233581 ops/sec;   51.7 MB/sec
3896.42user 1539.12system 6:50.61elapsed 1323%CPU (0avgtext+0avgdata 331308maxresident)k
0inputs+0outputs (0major+1281001minor)pagefaults 0swaps
$ cat update-16t-fixed.txt | tail -4
updaterandom [AVG    3 runs] : 230364 ops/sec;   51.0 MB/sec
updaterandom [MEDIAN 3 runs] : 226169 ops/sec;   50.0 MB/sec
3865.46user 1568.32system 6:57.63elapsed 1301%CPU (0avgtext+0avgdata 315012maxresident)k
0inputs+0outputs (0major+1342568minor)pagefaults 0swaps

$ cat update-64t-bug.txt | tail -4
updaterandom [AVG    3 runs] : 261878 ops/sec;   57.9 MB/sec
updaterandom [MEDIAN 3 runs] : 262859 ops/sec;   58.2 MB/sec
926.27user 578.06system 2:27.46elapsed 1020%CPU (0avgtext+0avgdata 475480maxresident)k
0inputs+0outputs (0major+1058728minor)pagefaults 0swaps
$ cat update-64t-fixed.txt | tail -4
updaterandom [AVG    3 runs] : 256699 ops/sec;   56.8 MB/sec
updaterandom [MEDIAN 3 runs] : 256380 ops/sec;   56.7 MB/sec
933.47user 575.37system 2:30.41elapsed 1003%CPU (0avgtext+0avgdata 482340maxresident)k
0inputs+0outputs (0major+1078557minor)pagefaults 0swaps

### CODE REVIEW

**Comment by grooverdan** [comment]
Thanks for fixing this.

**Comment by maysamyabandeh** [comment]
I increased the reinforcement value by 8x and the throughput with 16t increased by 53% (compared to the buggy case) and with 64t by 1%.

@nbronson 131072 would also satisfy the condition for not overflowing uint32_t. What was the rationale behind choosing a lower value of 16384?

The change:
```
-    v = v - (v / 1024) + (would_spin_again ? 1 : -1) * 16384;
+    v = v - (v / 1024) + (would_spin_again ? 1 : -1) * 131072;
```
Results:
 cat update-16t-bug.txt | tail -4
updaterandom [AVG    3 runs] : 234117 ops/sec;   51.8 MB/sec
updaterandom [MEDIAN 3 runs] : 233581 ops/sec;   51.7 MB/sec
3896.42user 1539.12system 6:50.61elapsed 1323%CPU (0avgtext+0avgdata 331308maxresident)k
0inputs+0outputs (0major+1281001minor)pagefaults 0swaps
$ cat update-16t-fixed-8x.txt | tail -4
updaterandom [AVG    3 runs] : 359744 ops/sec;   79.6 MB/sec
updaterandom [MEDIAN 3 runs] : 364989 ops/sec;   80.8 MB/sec
3359.89user 1047.51system 4:27.31elapsed 1648%CPU (0avgtext+0avgdata 377084maxresident)k
0inputs+0outputs (0major+890940minor)pagefaults 0swaps

$ cat update-64t-bug.txt | tail -4
updaterandom [AVG    3 runs] : 261878 ops/sec;   57.9 MB/sec
updaterandom [MEDIAN 3 runs] : 262859 ops/sec;   58.2 MB/sec
926.27user 578.06system 2:27.46elapsed 1020%CPU (0avgtext+0avgdata 475480maxresident)k
0inputs+0outputs (0major+1058728minor)pagefaults 0swaps
$ cat update-16t-fixed-8x.txt | tail -4
updaterandom [AVG    3 runs] : 359744 ops/sec;   79.6 MB/sec
updaterandom [MEDIAN 3 runs] : 364989 ops/sec;   80.8 MB/sec
3359.89user 1047.51system 4:27.31elapsed 1648%CPU (0avgtext+0avgdata 377084maxresident)k
0inputs+0outputs (0major+890940minor)pagefaults 0swaps

**Comment by nbronson** [comment]
I tested this diff using db_bench with and without concurrent memtable writes, with a fairly long sequence of txns (to trigger overflow). Perf was neutral or slightly better in all of my tests, and the context switching behavior was substantially improved. Thanks!

I used something like:

    #!/bin/bash
    
    TEST_TMPDIR=$HOME/tmp/rocksdb_bench/$(basename $PWD)
    rm -rf "$TEST_TMPDIR"/dbbench
    export TEST_TMPDIR
    
    /usr/bin/time -o /dev/stdout \
      -f 'vol=%w  invol=%c  elapsed=%E  inputs=%I  outputs=%O  cpu=%P' \
      ./db_bench \
       --benchmarks=fillrandom \
       --threads=16 \
       --batch_size=1 \
       --memtablerep=skip_list \
       --prefix_size=0 \
       --value_size=100 \
       --num=6250000 \
       --level0_slowdown_writes_trigger=9999 \
       --level0_stop_writes_trigger=9999 \
       --disable_auto_compactions \
       --max_write_buffer_number=4 \
       --max_background_flushes=4 \
       --stats_interval=$OPS \
       --write_buffer_size=1600000000 \
       --block_size=16384 \
       --disable_wal \
       --enable_write_thread_adaptive_yield \
       --allow_concurrent_memtable_write=false

**Comment by nbronson** [comment]
@maysamyabandeh I chose 16K because it seemed large enough that it could be decayed in integral 0.1% chunks with reasonable accuracy. I think we could actually use a delta as large as 2^20 without overflow, since that would balance addition and decay at +/-2^30. I doubt it would matter much.

Have you run UBSAN with the fix applied to verify that there is no overflow?

**Comment by maysamyabandeh** [comment]
@nbronson Thanks for verifying the patch.
1. The benchmark results I pasted above suggested that using 131072 in place of 16384 would offer 50% higher throughput with 16 threads. So if I was wondering if update the patch to use 131072 instead?
2. The bug is not deterministic otherwise it would have shown up in our continuous UBSAN test runs. The math makes sense to me now and I think the bug is fixed by this patch.

**Comment by nbronson** [comment]
I'm very skeptical that 128K versus 16K would yield a 50% higher
throughput, but I don't see any reason why we shouldn't use a larger value
here.

**Comment by maysamyabandeh** [comment]
Cool. Do you think you can give it a try with your benchmark settings? That would give more confidence about the change.

**Comment by nbronson** [comment]
For my benchmark settings adding 16K versus 128K makes no difference.

**Comment by maysamyabandeh** [comment]
Ok. It might be neutral change or it also might give better throughput in some corner cases. I applied the change. Will watch the daily benchmarks closely.

**Pull request closed without merging**
