### PR TITLE
Add Wingify to USERS.md

### PR DESCRIPTION
**Pull request by ankneo**
VWO, the flagship product of Wingify, uses RocksDB to populate the list of URLs where clients can run A/B test campaigns. It is also used to provide a way for the clients to see if VWO's Smart Code is installed on a specific URL of their account.

### CODE REVIEW

**Comment by dhruba** [comment]
Hi Ankit, thanks for the patch. Can you pl sign the CLA at  https://code.facebook.com/cla  so that I can merge your patch?

**Comment by ankneo** [comment]
Hi @dhruba, I have signed the CLA.

**Comment by igorcanadi** [comment]
> This branch has conflicts that must be resolved

Can you please resolve the conflicts?

**Comment by ankneo** [comment]
@igorcanadi Seems to be a build failure [here](https://travis-ci.org/facebook/rocksdb/jobs/103160689) which does not seem to be related to the change done by me in USERS.md

*/bin/sh: line 1: 12526 Segmentation fault: 11  ./$t*
*make: *** [check] Error 1*

**Comment by igorcanadi** [comment]
@ankneo don't worry about the build failure. The problem is with merge conflicts because of https://github.com/facebook/rocksdb/commit/2e9fae3f2a00e38dfef58f7778d5321d5bd07bfd

**Pull request closed without merging**
