### PR TITLE
CMake: compile with -O2

### PR DESCRIPTION
**Pull request by tamird**
Seems pretty important.

### CODE REVIEW

**Comment by siying** [comment]
I'm curious why not -O3

**Comment by tamird** [comment]
Just following the Makefile, but I believe O3 can sometimes produce worse code than O2.

**Comment by siying** [comment]
@tamird we are keeping Makefile to O2 because it has always been there so there is a risk of regression in some use case. Starting from scratch, it may be a good idea to start from O3 in the begining. I'm merging this O2 change anyway. Feel free to change it to O3 if you think it is a better choice.

**Comment by tamird** [comment]
Will do! Thanks.

**Comment by tamird** [comment]
Sorry, to clarify, I'll send another PR for O3 if it turns out to be useful.

**Comment by tamird** [comment]
Could you merge this? Thanks!

**Comment by yiwu-arbug** [comment]
Do you mind rebase onto latest master?

**Comment by tamird** [comment]
Done.

**Pull request closed without merging**
