### PR TITLE
fixes 1228: rockdbjni loadLibraryFromJarToTemp fails when file is already present

### PR DESCRIPTION
**Pull request by clumsy**
overriding existing library in tmp folder

### CODE REVIEW

**Comment by adamretter** [comment]
@clumsy This doesn't build. Please see the output from Travis-CI https://travis-ci.org/facebook/rocksdb/jobs/146554616

Looks like you are missing an import in your Test class

**Comment by adamretter** [comment]
https://github.com/facebook/rocksdb/issues/1228

**Comment by clumsy** [comment]
My bad, did not amend my last commit locally.

**Comment by adamretter** [comment]
@clumsy Okay can you squash into one commit

**Comment by clumsy** [comment]
Done!

**Comment by adamretter** [comment]
LGTM :-)

**Pull request merged**
