### PR TITLE
Upgrade Appveyor to VS2017

### PR DESCRIPTION
**Pull request by gfosco**
Per some discussions, this will switch our Appveyor testing to use Visual Studio 2017.

### CODE REVIEW

**Comment by gfosco** [comment]
Ah, I thought #3434 landed, this will have to wait.

**Comment by siying** [comment]
Any idea why appveyor failed?

**Comment by yuslepukhin** [comment]
@siying This is due to the internal compiler bug I reported but promised to be fixed in 15.6. I reopened it.
https://github.com/facebook/rocksdb/issues/2816

**Comment by yuslepukhin** [comment]
VS 2017 would work if we made the build un-optimized.

**Comment by gfosco** [comment]
Also #3425 should've landed first..  This builds locally, will keep checking.

**Comment by gfosco** [comment]
Looks like this might be the issue, MS says it's fixed in a future release: https://developercommunity.visualstudio.com/content/problem/182074/internal-compiler-error-in-msvc-2017-155.html

**Comment by gfosco** [comment]
The error said to simplify the area where the compiler failed... Moving that std::to_string method outside the UserCollectedProperties declaration fixed it. 😄

**Comment by siying** [comment]
@gfosco cool! It's debatable whether the area is simplified though:)

**Pull request closed without merging**
