### PR TITLE
Update RocksDBCommonHelper to use escapeshellarg

### PR DESCRIPTION
**Pull request by FBNeal**
Most of the data used here in shell commands is not generated directly from user input but some data (ie: from environment variables) may have been external influenced. It is a good practice to escape this data before using it in a shell command.

### CODE REVIEW

**Comment by yiwu-arbug** [comment]
@FBNeal is this PR ready to land?

**Comment by FBNeal** [comment]
@yiwu-arbug: I believe so, yeah. Not sure what the process is here.

**Comment by yiwu-arbug** [comment]
Looks like importing to phabricator somehow failed (see the error message on https://phabricator.intern.facebook.com/D4800264). Will investigate whether it is related to the change.

**Comment by FBNeal** [comment]
Need to redo this.

**Pull request closed without merging**
