### PR TITLE
set snappy compression only when supported

### PR DESCRIPTION
**Pull request by miasantreble**
Right now `OptimizeLevelStyleCompaction` may set compression type to Snappy even when Snappy is not supported, this may cause errors like "no snappy compression support" 
Fixes https://github.com/facebook/rocksdb/issues/4283

### CODE REVIEW

**Comment by miasantreble** [comment]
ping @siying

**Comment by miasantreble** [comment]
@ajkr I talked to @siying and his main concern is that it's possible that zstd is available on the machine where the file is created but not on the machine where it's read (for example, the file may be copied over network). In that case the file will be unreadable.

**Comment by ajkr** [comment]
I don't quite understand since snappy (or any implicitly chosen compression library) would have the same problem. By that logic I'd expect us to default to no compression.

**Comment by miasantreble** [comment]
@ajkr PTAL

**Comment by siying** [comment]
ready to merge?

**Comment by ajkr** [comment]
can we land it? I am happy with the current code as long as we document the change to default compression type.

**Comment by riversand963** [comment]
@ajkr agree. We should at least mention this change in HISTORY.md.

**Comment by siying** [comment]
either land or abandon?

**Pull request closed without merging**
