### PR TITLE
Revert open logic changes in #9634

### PR DESCRIPTION
**Pull request by ajkr**
Left HISTORY.md and unit tests.
Added a new unit test to repro the corruption scenario that this PR fixes, and HISTORY.md line for that.

### CODE REVIEW

**Review by riversand963 — COMMENTED** [review]
hmm, the test failures are legit.
In #9634, some unit tests were updated because we wanted to avoid creating new MANIFEST before recovery succeeds. This requires us not to create the stats_history cf before syncing the new WAL. It also requires us not to create missing column families before that.
I wonder whether it's easier just to revert #9634, and use the new unit test in the follow-up PR.

**Comment by ajkr** [comment]
Tried reverting stats_history_test.

> I wonder whether it's easier just to revert https://github.com/facebook/rocksdb/pull/9634, and use the new unit test in the follow-up PR.

It's already released, this is a bug fix now.

**Review by riversand963 — APPROVED** [review]
A Java test needs to be fixed as well. Otherwise LGTM. Thanks @ajkr

**Comment by ajkr** [comment]
Thanks for the review!

**Comment by ajkr** [comment]
Will fix build-linux-clang10-clang-analyze later so we can close the SEV sooner

**Pull request closed without merging**
