### PR TITLE
Perform java static checks in CI 

### PR DESCRIPTION
**Pull request by alanpaxton**
Integrate pmd on the Java API to catch and report common Java coding problems; fix or suppress a basic set of PMD checks.

Link pmd into java build / CI

Add a pmd dependency to maven
Add a jpmd target to Makefile which runs pmd
Add a workflow to Circle CI which runs pmd
Configure an initial default pmd for CI

Repair lots of very simple PMD reports generated when we apply pmd-rules.xml

Repair or exception for PMD rules in the CloseResource category, which finds unclosed AutoCloseable resources.
We special-case the configuration of CloseResource and use the // NOPMD comment in source the avoid reports where we are the API creating an AutoCloseable, and therefore returning an unclosed resource is correct behaviour.

### CODE REVIEW

**Review by adamretter — APPROVED** [review]
LGTM. Thanks @alanpaxton

**Comment by anand1976** [comment]
@alanpaxton Please rebase

**Comment by alanpaxton** [comment]
@anand1976 @adamretter rebased and once again ready for review/import.

**Comment by adamretter** [comment]
@anand1976 rebased and once again ready for review/import.

**Comment by alanpaxton** [comment]
@anand1976 I have rebased this again. It is once again ready for review/import.

**Review by jowlyzhang — APPROVED** [review]
Thank you for the improvement! LGTM, would you mind rebasing and kick off the tests again, thanks!

**Comment by alanpaxton** [comment]
> Thank you for the improvement! LGTM, would you mind rebasing and kick off the tests again, thanks!

We are finally up to date with rebase again now @jowlyzhang - would be great if you were able to import

**Comment by jowlyzhang** [comment]
> > Thank you for the improvement! LGTM, would you mind rebasing and kick off the tests again, thanks!
> 
> We are finally up to date with rebase again now @jowlyzhang - would be great if you were able to import

Sorry for the delay, it's now imported.

**Pull request closed without merging**
