### PR TITLE
Fix regression - 100% CPU - Regression for Windows 7

### LINKED ISSUE #5552: 100% CPU - Regression for Window 7 in WinEnvIO::NowMicros()
### Expected behavior
NowMicros() function should return time from Unix epoch, but is returning high resolution counter that has no defined start and should be used for measuring time only. This function is used in RepeatableThread::wait. Thread than calculates wait_until thus conditional variable can do TimedWait.

But CondVar::TimedWait is using time in Unix epoch again thus issue.

```
uint64_t WinEnvIO::NowMicros() {
....
  return duration_cast<microseconds>(
      high_resolution_clock::now().time_since_epoch()).count();
But should be:
  return duration_cast<microseconds>(system_clock::now().time_since_epoch()).count();
```

Regression in https://github.com/facebook/rocksdb/commit/88d85b6820453fc6d83ee699e33013eb6810472f

### Actual behavior
RocksDB RepeatableThread is taking 100% CPU on Windows 7.

### Steps to reproduce the behavior
Run RocksDB on Windows 7.

After I have reverted that line, library works as usual. Let me know if you agree and I can create pull request.

### PR DESCRIPTION
**Pull request by koldat**
Fixes #5552

### CODE REVIEW

**Comment by siying** [comment]
CC @burtonli

**Comment by siying** [comment]
As we are waiting for people who are expert on Windows for comment, can you explain why this line caused performance regression?

**Comment by koldat** [comment]
I have described in issue.

Problem is windows 7. These does. Not have that api thus fallback to high resolution timer. But that is implemented (at least on windows 7) as performance counter without defined start.

Then this "random" number is passed to condition variable that expects Unix microsends time to calculate sleep required. Thus result is always negative, clamped to zero thus never waits thus 100% Cpu.

That function would not work even on Linux. It is simply wrong. High performance clock does not guarantee Unix timestamp I think. At least on widows not.

**Comment by koldat** [comment]
See https://stackoverflow.com/questions/13263277/difference-between-stdsystem-clock-and-stdsteady-clock

**Comment by siying** [comment]
This is odd as Env::NowNanos() is supposed to be high-resolute timestamp but might not represent physical time, while NowMicros() can be low-resolute ones but has to represent physical time. I think we should merge it. If inside RocksDB the timestamp somewhere is used incorrectly, we should try to fix them instead.

**Comment by koldat** [comment]
You are right. That is what I meant,  nowMicros was broken because of that line. I have tested on many systems so it is safe and works perfect like before.

**Comment by adamretter** [comment]
@koldat @siying do you know which release version this went into?

**Pull request closed without merging**
