### PR TITLE
Fix rocksdb::Status::getState

### PR DESCRIPTION
**Pull request by adamretter**
This fixes the Java API for Status#getState use in Native code and also simplifies the implementation of rocksdb::Status::getState.
Closes https://github.com/facebook/rocksdb/issues/1688

### CODE REVIEW

**Comment by yiwu-arbug** [comment]
@adamretter Some of the tests a failing in travis. Do you mind take a look?

**Comment by yiwu-arbug** [comment]
Is it safe the change the existing behavior where Status::GetStatus() returns "size + msg + sub_msg"? cc @siying @IslamAbdelRahman

**Comment by adamretter** [comment]
@yiwu-arbug I did not see it being used within the Rocks project anywhere apart from the one place I fixed it ;-)

**Comment by yiwu-arbug** [comment]
@adamretter Okay. Mind running `make format`? Thanks.

**Comment by adamretter** [comment]
@yiwu-arbug I made the formatting changes. I am not certain if there is still a problem with the build or not, I can't seem to reproduce (macOS Sierra) but I think Travis had an issue still... any ideas?

**Comment by yiwu-arbug** [comment]
The tailing iterator test is broken for a while. I'm merging the change.

**Pull request closed without merging**
