### PR TITLE
Fix compilation on Apple Silicon

### PR DESCRIPTION
**Pull request by adamretter**
Closes - https://github.com/facebook/rocksdb/issues/7710

I tested this on an Apple DTK (Developer Transition Kit) with an Apple A12Z Bionic CPU and macOS Big Sur (11.0.1).

Previously the arm64 specific CRC optimisations were limited to Linux only OS... Well now Apple Silicon is also arm64 but runs macOS ;-)

### CODE REVIEW

**Comment by jurmous** [comment]
@adamretter I looked into the branch with my M1 machine. It compiled ok. I ran `make check` and it failed with the following output: 

```
Computers / CPU cores / Max jobs to run
1:local / 8 / 8

Computer:jobs running/jobs completed/%of started jobs/Average seconds to complete
ETA: 1371s Left: 4389 AVG: 0.31s  local:8/162/100%/0.3s /bin/bash: line 1: 41486 Abort trap: 6           ./listener_test >&t/log-listener_test
ETA: 0s Left: 0 AVG: 0.41s  local:0/4551/100%/0.4s      
Seq	Host	Starttime	JobRuntime	Send	Receive	Exitval	Signal	Command
76	:	1606654824.876	     0.005	0	0	1	0	./block_cache_trace_analyzer_test >& t/log-block_cache_trace_analyzer_test
154	:	1606654844.230	     0.027	0	0	1	0	./io_tracer_parser_test >& t/log-io_tracer_parser_test
158	:	1606654844.668	     4.640	0	0	134	0	./listener_test >& t/log-listener_test
206	:	1606654857.916	     0.005	0	0	1	0	./trace_analyzer_test >& t/log-trace_analyzer_test
make[1]: *** [check_0] Error 1
make: *** [check] Error 2
```

The ones with Exit val 1 did fail because they could not find gflags. 
```
Please install gflags to run trace_analyzer test
```
I tried to install it with ```make install``` and ```brew install gflags``` but it did not pick it up. But could also be that I did something wrong.


The actual failing test was outputting this:
```
[==========] Running 14 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 14 tests from EventListenerTest
[ RUN      ] EventListenerTest.OnSingleDBCompactionTest
[       OK ] EventListenerTest.OnSingleDBCompactionTest (38 ms)
[ RUN      ] EventListenerTest.OnSingleDBFlushTest
[       OK ] EventListenerTest.OnSingleDBFlushTest (44 ms)
[ RUN      ] EventListenerTest.MultiCF
[       OK ] EventListenerTest.MultiCF (37 ms)
[ RUN      ] EventListenerTest.MultiDBMultiListeners
[       OK ] EventListenerTest.MultiDBMultiListeners (107 ms)
[ RUN      ] EventListenerTest.DisableBGCompaction
[       OK ] EventListenerTest.DisableBGCompaction (121 ms)
[ RUN      ] EventListenerTest.CompactionReasonLevel
[       OK ] EventListenerTest.CompactionReasonLevel (37 ms)
[ RUN      ] EventListenerTest.CompactionReasonUniversal
[       OK ] EventListenerTest.CompactionReasonUniversal (65 ms)
[ RUN      ] EventListenerTest.CompactionReasonFIFO
[       OK ] EventListenerTest.CompactionReasonFIFO (18 ms)
[ RUN      ] EventListenerTest.TableFileCreationListenersTest
[       OK ] EventListenerTest.TableFileCreationListenersTest (2025 ms)
[ RUN      ] EventListenerTest.MemTableSealedListenerTest
[       OK ] EventListenerTest.MemTableSealedListenerTest (14 ms)
[ RUN      ] EventListenerTest.ColumnFamilyHandleDeletionStartedListenerTest
[       OK ] EventListenerTest.ColumnFamilyHandleDeletionStartedListenerTest (14 ms)
[ RUN      ] EventListenerTest.BackgroundErrorListenerFailedFlushTest
[       OK ] EventListenerTest.BackgroundErrorListenerFailedFlushTest (1023 ms)
[ RUN      ] EventListenerTest.BackgroundErrorListenerFailedCompactionTest
[       OK ] EventListenerTest.BackgroundErrorListenerFailedCompactionTest (1019 ms)
[ RUN      ] EventListenerTest.OnFileOperationTest
db/listener_test.cc:1058: Failure
Expected: (info.duration.count()) > (0), actual: 0 vs 0
libc++abi.dylib: terminating with uncaught exception of type testing::internal::GoogleTestFailureException: db/listener_test.cc:1058: Failure
Expected: (info.duration.count()) > (0), actual: 0 vs 0
```

If you have any further questions you are always welcome to ask!

**Comment by adamretter** [comment]
@jurmous Excellent thanks for testing. Looks good. I think we can get this merged first, and then address any failing tests.

**Comment by hayesgm** [comment]
Are there steps here to get this merged to master? Is there an area to focus on we can help with?

**Review by pdillinger — APPROVED** [review]
👍

**Comment by pdillinger** [comment]
FB infra was choking on this diff. Hopefully works with a merge.

**Comment by uptycs-rmack** [comment]
I've been working on getting osquery building natively for M1 and I had it all working until I upgraded RocksDB from 5.18.3 to 6.14.5. I ended up making the same fixes to get everything to compile however I'm getting osquery immediately killed (maybe at static init time?). lldb dies too if I try to debug it so I can't pinpoint exactly what's dying. Rolling back to 5.18.3 and everything works great. Just flagging this in case once this is merged you start to get other reports of apps linked to RocksDB hard crashing at startup.

**Pull request closed without merging**
