### PR TITLE
Increase Trash/DB size ratio in DBSSTTest.RateLimitedWALDelete

### PR DESCRIPTION
**Pull request by anand1976**
By increasing the ratio, we ensure that all files go through background deletion and eliminate flakiness due to timing of deletions.

Test plan:
make check
~/src/gtest-parallel/gtest-parallel ./db_sst_test --gtest_filter=DBSSTTest.RateLimitedWALDelete --repeat=10000

### CODE REVIEW

**Comment by riversand963** [comment]
Thanks @anand1976 for fixing. Can you include test plan as well?

**Comment by riversand963** [comment]
Does this fix the flakiness deterministically?

**Comment by anand1976** [comment]
I believe so. I could repro it with 1000 iterations.

**Comment by riversand963** [comment]
My question is, can we be sure that increasing the value from 2.1 to 3.1 can fix the problem deterministically? I am looking at https://github.com/facebook/rocksdb/blob/master/util/delete_scheduler.cc#L60. I wonder this fix can ensure the evaluation of the boolean expression is deterministic.

**Comment by anand1976** [comment]
I see. Maybe I can disable compression to inflate the DB size, so even after compacting the entire DB the trash size (which includes WALs) will be ~2x the DB size? Does that address your concern?

**Pull request closed without merging**
