### PR TITLE
Added CPU prefetch for skiplist

### PR DESCRIPTION
**Pull request by aclamk**
This change causes following changes result of test: 
./db_bench --writes 10000000 --benchmarks="fillrandom" --compression_type none
from
fillrandom   :       3.177 micros/op 314804 ops/sec;   34.8 MB/s
to
fillrandom   :       2.777 micros/op 360087 ops/sec;   39.8 MB/s

### CODE REVIEW

**Comment by sagar0** [comment]
Hi @aclamk -- Thanks for contributing to RocksDB. Could you please sign the CLA? 
Also, both Travis and Appveyor builds are failing. Could you please take a look at those too? Thanks.

**Comment by siying** [comment]
CC @nbronson

**Comment by yiwu-arbug** [comment]
Our regression test shows 2-3% reduction in deleterandom latency and neutral on other benchmarks.

**Comment by sagar0** [comment]
Another point to note: Regression tests show similar % *increase* in deleterandom ops/sec though.

**Pull request closed without merging**
