### PR TITLE
Add oldest snapshot sequence property

### PR DESCRIPTION
**Pull request by Connor1996**
Add oldest snapshot sequence property, so we can use `db.GetProperty("rocksdb.oldest-snapshot-sequence")` to get the sequence number of the oldest snapshot.

### CODE REVIEW

**Comment by maysamyabandeh** [comment]
@yiwu-arbug  A PR with no description?

**Comment by yiwu-arbug** [comment]
@Connor1996 update description?

**Comment by Connor1996** [comment]
@maysamyabandeh @yiwu-arbug updated.

**Comment by yiwu-arbug** [comment]
Use case: when we want to drop a region in tikv (think of it as a shard) through `DeleteFilesInRange`, we want to make sure the the oldest snapshot is newer than the timestamp when we drop the region logically, thus we need the API.

**Comment by maysamyabandeh** [comment]
@Connor1996 could you do a rebase?

**Comment by Connor1996** [comment]
@maysamyabandeh Done

**Pull request closed without merging**
