### PR TITLE
Source files dependencies detection for RocksDB plugins.

### PR DESCRIPTION
**Pull request by MaisenbacherD**
Summary: Otherwise a rebuild is not done if a RocksDB plugin header file is
changed.

Test Plan: Build RocksDB with a plugin.
Change a header file of the RocksDB plugin and rebuild.

Signed-off-by: Dennis Maisenbacher <dennis.maisenbacher@wdc.com>

### CODE REVIEW

**Comment by MaisenbacherD** [comment]
CLA was submitted.

**Comment by yhr** [comment]
@ajkr : could you have a look at this? Cheers!

**Review by ajkr — APPROVED** [review]
LGTM, thanks!

**Comment by ajkr** [comment]
Do you mind double checking the CLA is signed or try doing it again if it's not too much trouble? Sorry but the automation still thinks it's unsigned.

**Comment by MatiasBjorling** [comment]
Hi ajkr, I'll resend the approval e-mail to cla@fb.com

**Pull request closed without merging**
