### PR TITLE
Nullable objects wrap unregistered non-nullable objects

### PR DESCRIPTION
**Pull request by justinxu9905**
Summary
Fixing this issue #12029. 
Error with user defined TTL objects happens because unregistered user operator will bring not-found error which will break preparation of the nullable outer merge operator. So for example, user merge operator will be detected as null and report an error when opening a DB with TTL. 

Test Plan
unit test for unregistered user operator wrapped within TTLMergeOperator

### CODE REVIEW

**Review by ajkr — CHANGES_REQUESTED** [review]
I think the reason `user_operator` is nullified when attempting to serialize options is because it's unregistered, not because there is any duplication or overwriting involved in calling `DBWithTTLImpl::RegisterTtlClasses()`.

The outcome of #12044, in my opinion, should nullify `merge_operator` when it's a `TtlMergeOperator` wrapping an unserializable `user_operator`. This PR achieves that.

However, it should not prevent serializing a `TtlMergeOperator` as the `merge_operator` when the `user_operator` it wraps is registered and/or serializable. I think this PR prevents such serialization because it incorrectly unregisters `TtlMergeOperator`.

**Comment by justinxu9905** [comment]
> I think the reason `user_operator` is nullified when attempting to serialize options is because it's unregistered, not because there is any duplication or overwriting involved in calling `DBWithTTLImpl::RegisterTtlClasses()`.
> 
> The outcome of #12044, in my opinion, should nullify `merge_operator` when it's a `TtlMergeOperator` wrapping an unserializable `user_operator`. This PR achieves that.
> 
> However, it should not prevent serializing a `TtlMergeOperator` as the `merge_operator` when the `user_operator` it wraps is registered and/or serializable. I think this PR prevents such serialization because it incorrectly unregisters `TtlMergeOperator`.

Are we expecting `merge_operator` to be null as well when `user_operator` is null (because it is unregistered) and to be valid when `user_operator` is not null? 
And does it apply to other objects? like should the outer nullable object be null when any of its inner objects are null whether they are nullable or not.

**Comment by ajkr** [comment]
> Are we expecting merge_operator to be nullified when user_operator is null (because it is unregistered) and to be valid when user_operator is not null? And does it apply to other options? like should the outer nullable option be nullified when any of its non-nullable inner options are null.


Yes to both sounds ideal.

I made a little bit of progress in reporting the inner null object. Not sure if `Status::InvalidArgument` is the right way to report it, or if we should use something else.

```
diff --git a/options/options_helper.cc b/options/options_helper.cc
index 0c76d0315..38f7d4641 100644
--- a/options/options_helper.cc
+++ b/options/options_helper.cc
@@ -898,7 +898,14 @@ Status OptionTypeInfo::Parse(const ConfigOptions& config_options,
       ConfigOptions copy = config_options;
       copy.invoke_prepare_options = false;
       void* opt_addr = GetOffset(opt_ptr);
-      return parse_func_(copy, opt_name, opt_value, opt_addr);
+      Status s = parse_func_(copy, opt_name, opt_value, opt_addr);
+      if (s.ok()) {
+        Configurable* config = AsRawPointer<Configurable>(opt_ptr);
+        if (!CanBeNull() && config == nullptr) {
+          s = Status::InvalidArgument("Error parsing", opt_name);
+        }
+      }
+      return s;
     } else if (ParseOptionHelper(GetOffset(opt_ptr), type_, opt_value)) {
       return Status::OK();
     } else if (IsConfigurable()) {
```

But I didn't figure out how to nullify the outer option object. Feel free to change/incorporate this code if it's useful

**Comment by mrambacher** [comment]
@ajkr Can you tell me what your goal is for the inner and outer objects and where you hope to test for this behavior?  I am pretty sure this is likely a pretty simple change I can help with but I am not sure what your requirements are.

**Comment by justinxu9905** [comment]
> > Are we expecting merge_operator to be nullified when user_operator is null (because it is unregistered) and to be valid when user_operator is not null? And does it apply to other options? like should the outer nullable option be nullified when any of its non-nullable inner options are null.
> 
> Yes to both sounds ideal.
> 
> I made a little bit of progress in reporting the inner null object. Not sure if `Status::InvalidArgument` is the right way to report it, or if we should use something else.
> 
> ```
> diff --git a/options/options_helper.cc b/options/options_helper.cc
> index 0c76d0315..38f7d4641 100644
> --- a/options/options_helper.cc
> +++ b/options/options_helper.cc
> @@ -898,7 +898,14 @@ Status OptionTypeInfo::Parse(const ConfigOptions& config_options,
>        ConfigOptions copy = config_options;
>        copy.invoke_prepare_options = false;
>        void* opt_addr = GetOffset(opt_ptr);
> -      return parse_func_(copy, opt_name, opt_value, opt_addr);
> +      Status s = parse_func_(copy, opt_name, opt_value, opt_addr);
> +      if (s.ok()) {
> +        Configurable* config = AsRawPointer<Configurable>(opt_ptr);
> +        if (!CanBeNull() && config == nullptr) {
> +          s = Status::InvalidArgument("Error parsing", opt_name);
> +        }
> +      }
> +      return s;
>      } else if (ParseOptionHelper(GetOffset(opt_ptr), type_, opt_value)) {
>        return Status::OK();
>      } else if (IsConfigurable()) {
> ```
> 
> But I didn't figure out how to nullify the outer option object. Feel free to change/incorporate this code if it's useful

I think reporting inner null object as an error will still break `DB::Open`. 
Should we still use unregistered merge operator and just work around the serialization with null `user_operator`? Or nullify `merge operator` option?

**Comment by ajkr** [comment]
> Can you tell me what your goal is for the inner and outer objects and where you hope to test for this behavior? I am pretty sure this is likely a pretty simple change I can help with but I am not sure what your requirements are.

The issue we ran into happened when releasing #11800, we found there was one user of `DBWithTTL` who did not register their merge operator, and the DB failed to open as a result. That scenario is reproduced in the test case in #12029. Originally I was thinking we could solve it by nullifying the `merge_operator` as it is nullable, but let me try the patches you provided first.

**Pull request closed without merging**
