### PR TITLE
Restore Regex support for ObjectLibrary::Register, rename new APIs to allow old one to be deprecated in the future

### PR DESCRIPTION
**Pull request by mrambacher**
In order to support old-style regex function registration, restored the original "Register<T>(string, Factory)" method using regular expressions.  The PatternEntry methods were left in place but renamed to AddFactory.  The goal is to allow for the deprecation of the original regex Registry method in an upcoming release.

Added modes to the PatternEntry kMatchZeroOrMore and kMatchAtLeastOne to match * or +, respectively (kMatchAtLeastOne was the original behavior).

### CODE REVIEW

**Review by pdillinger — CHANGES_REQUESTED** [review]
Summarizing direct chat: I think partial regex support is more confusing. I don't think it's a problem to force the small-ish number of users of this API to change, but I think we need to be deliberate about moving away from regexes by ensuring old code using the regex does not compile any longer after the change.

I'm requesting we drop this PR and revert #9264 . Yes, that re-opens #9225 but I think that's best for long term public API cleanliness.

**Review by pdillinger — CHANGES_REQUESTED** [review]
(From direct chat) Waiting on updates to code comments and PR title and description for full review

**Comment by ajkr** [comment]
> Yes, that re-opens #9225 but I think that's best for long term public API cleanliness.

Could #9225 alternatively be resolved by dropping gcc 4.8 support (last discussed in https://www.facebook.com/groups/rocksdb.dev/posts/4044087892356361)?

**Comment by mrambacher** [comment]
> > Yes, that re-opens #9225 but I think that's best for long term public API cleanliness.
> 
> Could #9225 alternatively be resolved by dropping gcc 4.8 support (last discussed in https://www.facebook.com/groups/rocksdb.dev/posts/4044087892356361)?
> 
> edit: Also we can mitigate #9225 in the meantime by using simpler regexes. I know they don't work properly on gcc 4.8, but at least it prevents users who aren't trying to use ObjectRegistry from getting these errors.

The changes proposed in this PR restore the original regex code when using the "ObjectLibrary::Register" API but replace all internal RocksDB code with ObjectLibrary::AddFactory.  If using the old Register API (as existing applications may do), you would be subject the the regex "bugs" but nothing internal to RocksDB uses it.  This proposal allows applications a chance to migrate their code to the new API over time.

**Review by pdillinger — CHANGES_REQUESTED** [review]
Otherwise LGTM.

@ajkr I think Regexes are such a usability and performance hazard for things like this (deceptively simple but actually error-prone), I'm willing to take on some API complexity to get rid of them, even without the gcc 4.8 issue.

**Comment by ajkr** [comment]
> I think Regexes are such a usability and performance hazard for things like this (deceptively simple but actually error-prone)

Maybe, I don't know about usability problems as I still can't imagine needing to register something more complicated than "hdfs://.*". Nor can I imagine that creating option objects could be a heavy CPU user.

> I'm willing to take on some API complexity to get rid of them, even without the gcc 4.8 issue.

OK, but hopefully it is the minimum API complexity needed to support the use cases.

**Comment by pdillinger** [comment]
> > I think Regexes are such a usability and performance hazard for things like this (deceptively simple but actually error-prone)
> 
> Maybe, I don't know about usability problems as I still can't imagine needing to register something more complicated than "hdfs://.*".

I would also prefer a more standardized design with prescribed separator (e.g. "://") and separate validation from matching (e.g. not using /[0-9]+/ vs. /.*/ to pick between factories), but I'm not familiar with all the downstream consequences and no one has implemented it this way, even after discussing with @mrambacher 

> Nor can I imagine that creating option objects could be a heavy CPU user.

Performance blow up here is probably a low risk, but it is a well-documented risk that would be hard to defend perpetuating.

I'm more worried about things like "r.c.s" matching "rocks" or "rocks.*" matching "rockset:". A random reference I found related to buggy regex usage: https://wangpeipei90.github.io/papers/msr2020_preprint.pdf

> OK, but hopefully it is the minimum API complexity needed to support the use cases.

I don't think it is (see above) but I'd prefer to "hold the line" on existing weirdness and awkwardness than to leave it an open "Wild West" of regex matching. (By "existing weirdness and awkwardness" I mean the implicit cognitive complexity in distinguishing between regexes already used, and adding new ones that can be trusted to "play nice" with others.)

> It already sounds like we're making users migrate APIs

AFAIK, more minimization would require deeper migration (change config strings), rather than just (for cases we're aware of) cosmetic update of registration. IMHO it's better to do this now than to wait and see how bad the regex situation gets as more features move to a plugin or extension model vs. builtin.

Honestly I wouldn't object to keeping just the regexes if we had prescribed forms for them (in comments). Right now it's "do whatever you want." Prescribed forms would at least leave a cleaner path open for moving away from regexes by providing a drop-in alternative to those following the prescribed forms.

> based on speculative concerns (besides gcc 4.8 which is solvable differently), which is questionable enough.

This is what we do (or strive to do). As critical infrastructure, we try to avoid problems before they break something. There is always uncertainty.

**Comment by mrambacher** [comment]
> > > I think Regexes are such a usability and performance hazard for things like this (deceptively simple but actually error-prone)
> > 
> > 
> > Maybe, I don't know about usability problems as I still can't imagine needing to register something more complicated than "hdfs://.*".
> 
> I would also prefer a more standardized design with prescribed separator (e.g. "://") and separate validation from matching (e.g. not using /[0-9]+/ vs. /.*/ to pick between factories), but I'm not familiar with all the downstream consequences and no one has implemented it this way, even after discussing with @mrambacher

In the "core" codebase (I do not know what is going on inside of Facebook registrations or external users/plugins), the most common pattern is name://.*, where we match name:// followed by zero or more characters.  There are some uses (like SliceTransform, MemTableRepFactory) that expect name:[0-9]+, where it is a string followed by one or more numbers.  There are also cases that match either multiple names (MergeOperators, MemTableRepFactory) and cases that match either a "name" or name://.* (MemTableRepFactory), though these could be handled by registering two factories if necessary.

I attempted to minimize the number of APIs and cases we match.  I attempted to write test cases to cover all of the pattern match cases as well.

> I don't think it is (see above) but I'd prefer to "hold the line" on existing weirdness and awkwardness than to leave it an open "Wild West" of regex matching. (By "existing weirdness and awkwardness" I mean the implicit cognitive complexity in distinguishing between regexes already used, and adding new ones that can be trusted to "play nice" with others.)

I think the new API helps "hold the line" by eliminating the "Wild West" of regex and limiting the matches to specific cases.

I also think the "Wild West" of regex can lead to writing bad expressions that accidentally match.  For example, one could write a regex "foo.* (a better pattern would be foo://.*) and get it to match anything that starts with "foo" (foo:// and foobar://).  Since the only enforcement is better documentation, there is little RocksDB can do to eliminate these accidental matches.

**Review by pdillinger — APPROVED** [review]
Thanks for the updates

Still open to discussion from @ajkr but landing this PR as-is does fix a broken internal test

**Pull request closed without merging**
