### PR TITLE
Fix build jemalloc api

### PR DESCRIPTION
**Pull request by hliu18**
There is a compile error on Windows with MSVC in malloc_stats.cc where malloc_stats_print is referenced. The compiler only knows je_malloc_stats_print from jemalloc.h. Adding JEMALLOC_NO_RENAME replaces malloc_stats_print with je_malloc_stats_print.

### CODE REVIEW

**Comment by maysamyabandeh** [comment]
The appveyor tests already compile with Visual Studio 2017. What is the MSVS version that has compile issue?

**Comment by hliu18** [comment]
I ran into the issue on VS 2015.

**Comment by maysamyabandeh** [comment]
We might add VS2015 to our build process (https://github.com/facebook/rocksdb/pull/5446) Lets fix any 2015-related issue that shows up in the same pull request (https://github.com/facebook/rocksdb/pull/5446).

**Comment by hliu18** [comment]
Sounds good.

**Comment by hliu18** [comment]
I see the same issue when try to build on VS2017. It's not specific to VS2015. Can we move this PR forward by itself?

**Pull request closed without merging**
