### PR TITLE
Add Solana's RocksDB use case in USERS.md

### PR DESCRIPTION
**Pull request by yhchiang-sol**
Add Solana's RocksDB use case in USERS.md.

Solana is a fast, secure, scalable, and decentralized blockchain.  It uses RocksDB as the underlying storage for its ledger store.

github: https://github.com/solana-labs/solana

### CODE REVIEW

**Review by mrambacher — APPROVED** [review]
LGTM.  Welcome to the community!

**Comment by yhchiang-sol** [comment]
> Btw, some unrelated tests show failure in this PR. Is there any suggested way to retry or we should simply rebase?

I noticed there is a rerun button for each failure, but it seems that I don't have permission to issue re-run.

**Comment by mrambacher** [comment]
> > LGTM. Welcome to the community!
> > Thank you!  I used to be in the RocksDB community in the past as @yhchiang.
> 
> Btw, some unrelated tests show failure in this PR. Is there any suggested way to retry or we should simply rebase?

Please re-base and if the tests still fail, I will manually run them.  The failure appears to be from an old version of main.

**Comment by yhchiang-sol** [comment]
> Please re-base and if the tests still fail, I will manually run them. The failure appears to be from an old version of main.

Thank you!  I also noticed that (as I tried to rebase to master but I later found it's 'main' instead in this repo :p).

**Comment by yhchiang-sol** [comment]
Looks like I need a maintainer to approve running workflows as I am a first-time contributor with this account.

@mrambacher: do you mind giving it a quick look or approval?

**Comment by riversand963** [comment]
Can you re-import this? Thanks @mrambacher

**Comment by yhchiang-sol** [comment]
Move the Solana use case right before "others" section.

**Pull request closed without merging**
