### PR TITLE
Implement `PerfContex#toString` for the Java API

### PR DESCRIPTION
**Pull request by aivinog1**
I've implemented `PerfContext#toString` for the Java API.
See: https://groups.google.com/g/rocksdb/c/qbY_gNhbyAg

### CODE REVIEW

**Comment by adamretter** [comment]
Thanks @aivinog1 I have appended a commit which also incorporates the changes suggested by @rhubner here: https://github.com/facebook/rocksdb/pull/12433

This PR now incorporates and supersedes https://github.com/facebook/rocksdb/pull/12433

**Review by adamretter — APPROVED** [review]
LGTM. Thanks @aivinog1 and @rhubner

**Comment by aivinog1** [comment]
Hello @adamretter 👋 

First of all thank you for your review and fixes, but I have a question: should I merge/rebase main branch into my branch to unblock the PR to be able to merge it?

**Comment by adamretter** [comment]
@aivinog1 Might be helpful to do so

**Comment by aivinog1** [comment]
> @aivinog1 Might be helpful to rebase

Thank you, done

**Review by cbi42 — APPROVED** [review]

**Pull request closed without merging**
