### PR TITLE
ignore -Wunused-parameter.

### PR DESCRIPTION
**Pull request by ldesegur**
Added a void cast for unused function parameter to fix TARGET_OS=IOS make static_lib build.

### CODE REVIEW

**Comment by miasantreble** [comment]
@ldesegur I under your recent commit 6e61d8d is intended to expose more API for Rocksdb_lite, but that seems irrelevant to the title of this PR. When the PR is merged, all commits will be squashed into a single commit which contains only your PR title and summary. Do you mind separating the second commit into a new PR and submit it for review?

**Comment by miasantreble** [comment]
ah, I see you already made another PR https://github.com/facebook/rocksdb/pull/4030, so you can revert the last commit and good to go

**Comment by siying** [comment]
@ldelgadoj we can merge it if a simple rebase is done and only leaves the change in db_impl.cc. Are you still willing to help?

**Comment by riversand963** [comment]
Fixed by #7866

**Comment by justlorenzo2u** [comment]
> @ldesegur I under your recent commit [6e61d8d](https://github.com/facebook/rocksdb/commit/6e61d8da3a5b861e69c59895304cce03b32a1d63) is intended to expose more API for Rocksdb_lite, but that seems irrelevant to the title of this PR. When the PR is merged, all commits will be squashed into a single commit which contains only your PR title and summary. Do you mind separating the second commit into a new PR and submit it for review?

Squsshing is a bad practice. It essentially means from the committer: "trust me, nothing to worrry"

**Pull request closed without merging**
