### PR TITLE
Fix a bug in GetOverlappingInputsRangeBinarySearch

### PR DESCRIPTION
**Pull request by riversand963**
As title.

Test Plan:
```
$make clean && COMPILE_WITH_ASAN=1 make -j32 all && sleep 1 && make check
```

### CODE REVIEW

**Comment by siying** [comment]
Can you explain the impact of the bug in the title, and when it was introduced? If it is something already released, also mention it in HISTORY.md.

**Comment by riversand963** [comment]
@siying @ajkr This is the fix mentioned in #5215 
Now I kind of suspect I fixed some dead code...I may be totally wrong, so please let me know.
If you look at `CompactionPicker::CompactRange`. It calls `VersionStorageInfo::GetOverlappingInputs(begin, end)` first. If there is no overlapping file, it should return immediately. Only when there is an overlap will execution continue. Later it calls `ExpandInputsToCleanCut` which calls `GetOverlappingInputs` with key range that at least include `[begin, end]`. It seems certain that we will find file(s) overlapping. Therefore the line I changed will never be reached.

**Comment by siying** [comment]
I know it's the fix mentioned in #5215 but still HISTORY.md should provide a better description.

If it is a dead code, it shouldn't be there and add an assert.

**Comment by riversand963** [comment]
@siying I should not have used the term 'dead code'. If you pass different arguments to `GetOverlappingInputs` it is possible to hit this line. Therefore, I don't think we can put an `assert`.

**Comment by siying** [comment]
@riversand963 just update HISTORY.md to be specific about what the bug is, how it can be triggered and what's the impact.

**Pull request closed without merging**
