### PR TITLE
Include more information in file lock failure

### PR DESCRIPTION
**Pull request by siying**
Summary:
When users fail to open a DB with file lock failure, it is sometimes hard for users to debug. We now include the time the lock is acquired and the thread ID that acquired the lock, to help users debug problems like this. Default Env's thread ID is used.

Since type of lockedFiles is changed, rename it to follow naming convention too.

Test Plan: Add a unit test and improve an existing test to validate the case.

### CODE REVIEW

**Comment by siying** [comment]
@anand1976 do you know whether we have a function to return thread name? I can't find one and it feels a non-trivial task to implement a portable implementation. Maybe we can leave it as a follow up.

**Comment by anand1976** [comment]
@siying I don't know of a portable way. There's ```pthread_getname_np```, but its not portable. We call ```pthread_setname_np``` in other places in the code conditionally.

**Comment by siying** [comment]
@anand1976 yes we can do that too. If we don't know the thread name, ignore it. Maybe we can make a bootcamp task for it.

**Comment by siying** [comment]
The failures are not related.

**Pull request closed without merging**
