### PR TITLE
properly set C[XX]FLAGS during CMake configure-time checks

### PR DESCRIPTION
**Pull request by benesch**
Some compilers require `-std=c++11` for the `cstdint` header to be available. We already have logic to add `-std=c++11` to `CXXFLAGS` when the compiler is not MSVC; simply reorder CMakeLists.txt so that logic happens before the calls to `CHECK_CXX_SOURCE_COMPILES`.

Additionally add a missing `set(CMAKE_REQUIRED_FLAGS, ...)` before a call to `CHECK_C_SOURCE_COMPILES`.

### CODE REVIEW

**Comment by siying** [comment]
I hope the community can review it, as we don't use cmake. CC @tamird @muffins @yuslepukhin

**Comment by IslamAbdelRahman** [comment]
@benesch, can you rebase please ?

**Comment by benesch** [comment]
You bet—done!

**Comment by benesch** [comment]
Ok, rebased! Travis failure looks spurious: the agent in question ran out of disk space.

**Comment by benesch** [comment]
Sorry for the notification spam, but looks like this passes CI!

**Pull request closed without merging**
