### PR TITLE
Added placeholders for MADV defines

### PR DESCRIPTION
**Pull request by kwek20**
Cross compiling rocksdb with rust bindings to android leads to an error since 7.4.0 (Incusion of madvise)
This is due to missing placeholders for non-linux platforms. 

This PR adds the missing placeholders.

See https://github.com/rust-rocksdb/rust-rocksdb/issues/697 for the specific error thrown.

I have just completed the CLA :)

### CODE REVIEW

**Review by ajkr — APPROVED** [review]
LGTM

**Comment by kwek20** [comment]
What about the build error/timeout @ajkr

**Comment by ajkr** [comment]
It looks unrelated. I will rerun it.

**Comment by kwek20** [comment]
LGT @ajkr. Whats your sprint size like for a new release? So i can give an ETA to my team

**Comment by ajkr** [comment]
This should appear in the 7.9 release, which will likely be tagged around the beginning of December.

**Pull request closed without merging**
