### PR TITLE
Failed tests must be rerun with concurrency 1

### PR DESCRIPTION
**Pull request by yuslepukhin**

### CODE REVIEW

**Comment by yuslepukhin** [comment]
Somehow we hit the limit of 40 minutes again on the CI build

**Comment by siying** [comment]
@yuslepukhin we use premiere account now so there shouldn't be a limit of 40 minutes. Can you point me which run was killed after 40 minutes?

**Comment by yuslepukhin** [comment]
@siying This PR build looks like was killed https://ci.appveyor.com/project/Facebook/rocksdb/build/1.0.171

**Comment by siying** [comment]
@yuslepukhin let me figure it out.

**Comment by siying** [comment]
@yuslepukhin sorry I misunderstood it. Based on http://www.appveyor.com/pricing all plans have a limit of 40 minutes:( So if parallel testing doesn't work, we'll need to reduce more tests to make the 40 minutes budget.

**Comment by yuslepukhin** [comment]
@siying Travis failure is unrelated. I have not changed any code.

**Comment by yuslepukhin** [comment]
@siying But I do need to re-work the script

**Pull request merged**
