### PR TITLE
DeleteFilesInRange: support include_end

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**
Fix this [issue](https://github.com/facebook/rocksdb/issues/2837).

### CODE REVIEW

**Comment by ajkr** [comment]
unfortunately, it's still this test failing in travis: https://travis-ci.org/facebook/rocksdb/jobs/274870792

**Comment by zhangjinpeng1987** [comment]
I don't know where the problem is, when I run this test in my machine again and again, it never fail.

**Comment by ajkr** [comment]
Yeah, it also passed every time on my machine :/.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If you'd like this to be re-opened, please just comment here and we'll open it back up.

**Pull request closed without merging**
