### PR TITLE
[Win Bugfix] Import library for DLL (i.e. rocksdb-shared.lib) requires ARCHIVE DESTINATION.

### PR DESCRIPTION
**Pull request by xkszltl**
`rocksdb-shared.lib` is missing while `rocksdb.lib` and `rocksdb-shared.dll` are installed correctly.
Add `ARCHIVE DESTINATION` to fix this issue.

Refer to CMake doc for more details: [
https://cmake.org/cmake/help/v3.13/command/install.html#installing-targets](https://cmake.org/cmake/help/v3.13/command/install.html#installing-targets)
> ARCHIVE
> Static libraries are treated as ARCHIVE targets, except those marked with the FRAMEWORK property on macOS (see FRAMEWORK below.) For DLL platforms (all Windows-based systems including Cygwin), the DLL import library is treated as an ARCHIVE target.

### CODE REVIEW

**Comment by adamretter** [comment]
I am not sure that I understand the purpose of this. I thought that on Windows a `.lib` file indicated a statically linked library and a `.dll` indicated a dynamically linked library?

**Comment by xkszltl** [comment]
Not exactly.
Unlike `.so`, you cannot link against a `.dll` directly. You'll need to have something called "import lib", which is a static library (auto-generated by compiler) containing function calls like `LoadLibrary` and `GetProcAddress` to load dll and exec its functions.

**Comment by xkszltl** [comment]
Usually import lib is a tiny static library because it doesn't has any "actual" code.
For my build, with LTCG (link-time code gen, the VS version of LTO), `rocksdb.lib` is almost 1 GB, `rocksdb-shared.lib` is 202 KB and `rocksdb-shared.dll` is about 8 MB.

**Comment by xkszltl** [comment]
Before this PR, `rocksdb-shared.lib` was already built, but someone forget to set its installation path.

**Pull request closed without merging**
