### PR TITLE
Add check to cmake to see if we need to link against -latomic

### PR DESCRIPTION
**Pull request by mrambacher**
For some compilers/environments (e.g. Clang, riscv64), we need to link against -latomic.  Check if this is a requirement and add the library to the third-party libs if it is.

### CODE REVIEW

**Comment by mrambacher** [comment]
This should fix #7051 and #6995.

**Comment by grooverdan** [comment]
Thanks for writing this.

This starts ok, however the logic of failure to compile and `-latomic` is the solution is a little weak.

```
set(ATOMIC_TEST_PROGRAM ".....")
CHECK_CXX_SOURCE_COMPILES(${ATOMIC_TEST_PROGRAM}  BUILTIN_ATOMIC)
if (NOT BUILTIN_ATOMIC)
   set(CMAKE_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRARIES} atomic)
   CHECK_CXX_SOURCE_COMPILES(${ATOMIC_TEST_PROGRAM} WITH_ATOMIC_LIB)
   if(NOT WITH_ATOMIC_LIB)
      message(FATAL ...
   endif()
endif()
```

Is unconditionally clearing `CMAKE_REQUIRED_FLAGS` right, or should there be a save/restore?

**Comment by mrambacher** [comment]
> Thanks for writing this.
> 
> This starts ok, however the logic of failure to compile and `-latomic` is the solution is a little weak.

I am not sure what you mean by a "little weak".  There is a "CheckAtomic.cmake" that can be found as part of clang but my lack of knowledge of cmake and how to find this file stymied me but this solution is very similar to what they do (they do a better job of checking if the atomic library is present).  

> ```
> set(ATOMIC_TEST_PROGRAM ".....")
> CHECK_CXX_SOURCE_COMPILES(${ATOMIC_TEST_PROGRAM}  BUILTIN_ATOMIC)
> if (NOT BUILTIN_ATOMIC)
>    set(CMAKE_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRARIES} atomic)
>    CHECK_CXX_SOURCE_COMPILES(${ATOMIC_TEST_PROGRAM} WITH_ATOMIC_LIB)
>    if(NOT WITH_ATOMIC_LIB)
>       message(FATAL ...
>    endif()
> endif()
> ```
> 
> Is unconditionally clearing `CMAKE_REQUIRED_FLAGS` right, or should there be a save/restore?

I did not add the clearing of CMAKE_REQUIRED_FLAGS, only moved it.  If it should be a save/restore, that is fine.

**Review by pdillinger — APPROVED** [review]
¯\\_(ツ)_/¯ seems fine

I wish we would unify detection of stuff like this between the cmake and Makefile builds, but that's on the wishlist.

**Comment by mrambacher** [comment]
> ¯\_(ツ)_/¯ seems fine
> 
> I wish we would unify detection of stuff like this between the cmake and Makefile builds, but that's on the wishlist.

Thanks for the review!  I fully agree that it would be nice if we could unify the cmake and make systems.  Trying to keep the two systems in sync is problematic and error prone to say the least.

**Comment by alexfanqi** [comment]
Hi,
Sorry for replying to this closed issue. But the cpp code piece used in this pr for testing libatomic seems not adequate. 

I tested  with gcc 11.2 and on Sifive Unmatched (riscv64). The code piece passed without linker error and I still get ```undefined reference to `__atomic_compare_exchange_1'``` later in compiling the whole program.

This snippet from WebKit will work. 
https://github.com/WebKit/WebKit/blob/87d88025bf5a3089e68b4466a12dd1cb2584d557/Source/cmake/WebKitCompilerFlags.cmake#L282

original
```
unmatch2 /tmp # cat test.cpp 
#include <atomic>
std::atomic<uint64_t> x(0);
int main() {
uint64_t i = x.load(std::memory_order_relaxed);
bool b = x.is_lock_free();
return 0;
}
unmatch2 /tmp # gcc -Wall test.cpp 
test.cpp: In function ‘int main()’:
test.cpp:4:10: warning: unused variable ‘i’ [-Wunused-variable]
    4 | uint64_t i = x.load(std::memory_order_relaxed);
      |          ^
test.cpp:5:6: warning: unused variable ‘b’ [-Wunused-variable]
    5 | bool b = x.is_lock_free();
      |      ^
"
```

new from Webkit
```
unmatch2 /tmp # cat test2.cpp 
#include <atomic>
int main() {
std::atomic<bool> y (false);
std::atomic<uint64_t> x (0);
bool expected = true;
bool j = y.compare_exchange_weak(expected,false);
x++;
return 0;
}
unmatch2 /tmp # gcc test2.cpp 
/usr/lib/gcc/riscv64-unknown-linux-gnu/11.2.0/../../../../riscv64-unknown-linux-gnu/bin/ld: /tmp/.private/root/cc45pcng.o: in function `.L0 ':
test2.cpp:(.text._ZNSt6atomicIbE21compare_exchange_weakERbbSt12memory_order[_ZNSt6atomicIbE21compare_exchange_weakERbbSt12memory_order]+0xb2): undefined reference to `__atomic_compare_exchange_1'
collect2: error: ld returned 1 exit status
unmatch2 /tmp # 

```

gcc -v
```
Using built-in specs.
COLLECT_GCC=gcc    
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/riscv64-unknown-linux-gnu/11.2.0/lto-wrapper
Target: riscv64-unknown-linux-gnu     
Configured with: /var/tmp/portage/sys-devel/gcc-11.2.0/work/gcc-11.2.0/configure --host=riscv64-unknown-linux-gnu --
build=riscv64-unknown-linux-gnu --prefix=/usr --bindir=/usr/riscv64-unknown-linux-gnu/gcc-bin/11.2.0 --includedir=/u
sr/lib/gcc/riscv64-unknown-linux-gnu/11.2.0/include --datadir=/usr/share/gcc-data/riscv64-unknown-linux-gnu/11.2.0 -
-mandir=/usr/share/gcc-data/riscv64-unknown-linux-gnu/11.2.0/man --infodir=/usr/share/gcc-data/riscv64-unknown-linux
-gnu/11.2.0/info --with-gxx-include-dir=/usr/lib/gcc/riscv64-unknown-linux-gnu/11.2.0/include/g++-v11 --with-python-
dir=/share/gcc-data/riscv64-unknown-linux-gnu/11.2.0/python --enable-languages=c,c++,fortran --enable-obsolete --ena
ble-secureplt --disable-werror --with-system-zlib --enable-nls --without-included-gettext --disable-libunwind-except
ions --enable-checking=release --with-bugurl=https://bugs.gentoo.org/ --with-pkgversion='Gentoo 11.2.0 p1' --disable
-esp --enable-libstdcxx-time --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --dis
able-multilib --disable-fixed-point --with-abi=lp64d --enable-libgomp --disable-libssp --disable-libada --disable-sy
stemtap --disable-valgrind-annotations --disable-vtable-verify --disable-libvtv --withou
t-zstd --enable-lto --withou
t-isl --disable-libsanitizer --enable-default-pie --enable-default-ssp
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.2.0 (Gentoo 11.2.0 p1) 

```

**Pull request closed without merging**
