### PR TITLE
Makefile compile with -O3 with non-debug build

### PR DESCRIPTION
**Pull request by yiwu-arbug**
Summary:
Makefile compile with -O3 with non-debug build

Test Plan:
  make release -j64

### CODE REVIEW

**Comment by yiwu-arbug** [comment]
Let's discuss this on tomorrow's team meeting.

**Comment by IslamAbdelRahman** [comment]
LGTM, can you please include the size of the lib with -O2 and with -O3

**Comment by yiwu-arbug** [comment]
Will do. And I shall make lite build use -O2.

**Comment by siying** [comment]
@lightmark can you look at the failed gcc481 tests in gcc? It's still saying:

 RUN      ] EnvPosixTest.PositionedAppend
util/env_test.cc:701: Failure
env_->NewWritableFile(ift.name() + "/f", &writable_file, options)
IO error: /var/tmp/rocksdb.eVAHEs/f: Direct I/O not supported in RocksDB lite

**Comment by siying** [comment]
Shouls LITE build use -Os?

**Comment by yiwu-arbug** [comment]
I think so. Will update this patch later.

**Comment by siying** [comment]
Are we going to commit it?

**Comment by yiwu-arbug** [comment]
will do with the following change:
1. lite build use -Os
2. debug build use -O0
3. release buidl use -O3

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.

**Pull request closed without merging**
