### PR TITLE
Test range deletion block outlives table reader

### PR DESCRIPTION
**Pull request by ajkr**
This test ensures RangeDelAggregator can still access blocks even if it outlives the table readers that created them (detailed description in comments).

I plan to optimize away the extra cache lookup we currently do in BlockBasedTable::NewRangeTombstoneIterator(), as it is ~5% CPU in my random read benchmark in a database with 1k tombstones. This test will help make sure nothing breaks in the process.

### CODE REVIEW

**Comment by ajkr** [comment]
ping, it's just a test case (although admittedly a complex one :) )

**Comment by Wanning930** [comment]
太棒啦！

**Comment by ajkr** [comment]
ping, usually my test cases end up blindly accepted, so no point taking a month for that.

**Comment by ajkr** [comment]
Thank you!! :)

**Pull request closed without merging**
