### PR TITLE
Have Cache use Status::MemoryLimit

### PR DESCRIPTION
**Pull request by pdillinger**
Summary: I noticed it would clean up some things to have Cache::Insert()
return our MemoryLimit Status instead of Incomplete for the case in
which the capacity limit is reached. I suspect this fixes some existing but
unknown bugs where this Incomplete could be confused with other uses
of Incomplete, especially no_io cases. This is the most suspicious case I
noticed, but was not able to reproduce a bug, in part because the existing
code is not covered by unit tests (FIXME added): https://github.com/facebook/rocksdb/blob/57adbf0e9187331cb39bf5cdb5f5d67faeee5f63/table/get_context.cc#L397

I audited all the existing uses of IsIncomplete and updated those that
seemed relevant.

HISTORY updated with a clear warning to users of strict_capacity_limit=true
to update uses of `IsIncomplete()`

Test Plan: updated unit tests

### CODE REVIEW

**Review by hx235 — COMMENTED** [review]
Can we split "prototype stress test support" into another PR? The reason is that while changes related to "Have Cache use Status::MemoryLimit" LGTM, I hesitate to accept this PR cuz the idea behind stress test is not clear to me yet (most likely due to it's still in prototyping stage).


Also, strictly speaking, this PR breaks API compatibility and I personally find it hard to verify its impact is indeed minimum although intuitively it should be as mentioned by the author. So I'd like to invite @ajkr to take another look into the compatibility issue.

**Review by ajkr — COMMENTED** [review]
> So I'd like to invite @ajkr to take another look into the compatibility issue.

It's OK with me. `strict_capacity_limit=true` should be rare. The risk for custom `Cache` implementors who forget to migrate should be low. I only thought of users of cache charging may see `Status::Incomplete` where the contract and older versions were `Status::MemoryLimit`.

edit: There are also risks for DB users who rely on  `Status::Incomplete` although it's not guaranteed by contract (sounds unlikely), and direct Cache users who don't migrate.

**Comment by pdillinger** [comment]
Oh, right, I guess this is a potentially significant change to DB operation status results, but should be a long-term improvement because Incomplete already means other things.

**Review by hx235 — APPROVED** [review]
LGTM!

**Pull request closed without merging**
