### PR TITLE
Improve transaction C-API

### PR DESCRIPTION
**Pull request by yiyuanliu**
This PR wants to improve support for transaction in C-API:
* Support two-phase commit.
* Support `get_pinned` and `multi_get` in transaction.
* Add `rocksdb_transactiondb_flush`
* Support get writebatch from transaction and rebuild transaction from writebatch.

### CODE REVIEW

**Review by riversand963 — COMMENTED** [review]
@yiyuanliu thanks for the PR! Mostly LGTM.
I didn't do a very detailed review since this is language binding and covers quite a number of APIs and do not affect core functionality.

Can you update HISTORY.md to mention the C API additions?

**Comment by yiyuanliu** [comment]
> @yiyuanliu thanks for the PR! Mostly LGTM. I didn't do a very detailed review since this is language binding and covers quite a number of APIs and do not affect core functionality.
> 
> Can you update HISTORY.md to mention the C API additions?

I've added some more code to this PR and updated the HISTORY.md

**Comment by riversand963** [comment]
Thanks @yiyuanliu. Can you fix the following Github action?
```
Check buck targets and code format / Check TARGETS file and code format (pull_request) 
```

**Comment by riversand963** [comment]
Hi @yiyuanliu, it seems there are conflicts. Can you merge/rebase to latest version after resolving the conflicts?
I could have done it if your changes were on your repo's dev-branch other than your own 'main' branch.

**Pull request closed without merging**
