### PR TITLE
Expose PerfContext::ToString in Java.

### PR DESCRIPTION
**Pull request by rhubner**
Overrode `public String toString()` to use `PerfContext::ToString()`

### CODE REVIEW

**Comment by adamretter** [comment]
> I think public String toString() should not call native code

@rhubner What do you see as the potential issue with doing that?

**Comment by rhubner** [comment]
> > I think public String toString() should not call native code
> 
> @rhubner What do you see as the potential issue with doing that?

@adamretter 
`toString` is usually called by anybody enywhere, espetially some high level libraries or logging frameworks like to used it. This can cause unexpected call to native code. If you think it's ok. I'm happy to implement it.

**Comment by adamretter** [comment]
> This can cause unexpected call to native code. If you think it's ok. I'm happy to implement it.

I think it should be okay as long as the native function isn't doing anything especially complex, i.e. not much more than retrieving a string value from a native variable.

**Review by ajkr — APPROVED** [review]

**Comment by rhubner** [comment]
Closing, all changes incorporated to #12473

**Pull request closed without merging**
