### PR TITLE
Move memtable related files into memtable directory

### PR DESCRIPTION
**Pull request by yiwu-arbug**
Summary:
Move memtable related files into memtable directory.

Test Plan:
run existing tests.

### CODE REVIEW

**Comment by yiwu-arbug** [comment]
@ajkr Good point! Will work on it.

**Comment by yiwu-arbug** [comment]
The list of memtable->db dependencies:
```
memtable.cc:#include "db/dbformat.h"
memtable.cc:#include "db/merge_context.h"
memtable.cc:#include "db/merge_helper.h"
memtable.cc:#include "db/pinned_iterators_manager.h"
memtable.h:#include "db/dbformat.h"
memtable.h:#include "db/range_del_aggregator.h"
memtable.h:#include "db/version_edit.h"
memtablerep_bench.cc:#include "db/dbformat.h"
```
memtable.h contain too many dependencies from db. Shall we move it back to db directory?
And memtablerep_bench.cc is depending on InternalKeyComparator from db/dbformat.h. Do you think moving InternalKeyComparator to public header a good idea or not? Need suggestions.

**Comment by siying** [comment]
@yiwu-arbug yes, maybe move it back. Just leave the skiplist rep.

**Comment by yiwu-arbug** [comment]
@siying cool.

**Comment by yiwu-arbug** [comment]
Will land after windows build pass.

**Pull request closed without merging**
