### PR TITLE
BugFix: the block maybe compressed! If the blocked is compressed, each

### PR DESCRIPTION
**Pull request by fclh1991**
The Block content maybe the compressed block. For example, the value of the handle of the element in block_cache_compressed. The result of the operation of the Block with compressed data is undefined.

### CODE REVIEW

**Comment by siying** [comment]
@fclh1991 tests are failing. Can you take a look?

**Comment by fclh1991** [comment]
@siying , there are no compression_type in the content of PlainTable. However, the implement of **table/format.cc:ReadBlockContents**, it will try to get the compression_type for any block. 
`
table/format.cc:line 388    compression_type = static_cast<rocksdb::CompressionType>(slice.data()[n]);
`
For the block without compression_type and checksum code, the result of `compression_type`  is wrong. However,  the **wrong** `compression_type` is used to initialize the `BlockContents`, and the `BlockContents` with *wrong* `compression_type` is used to initialize the `Block`.

**Comment by siying** [comment]
@fclh1991 can you fix the Travis failures?

**Comment by fclh1991** [comment]
@siying I add a bool parameter `with_block_trailer` for **ReadBlockContents**. It may be not a good way to fix the bug.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.

**Pull request closed without merging**
