### PR TITLE
Replace deprecated RocksDB#addFile with RocksDB#ingestExternalFile

### PR DESCRIPTION
**Pull request by adamretter**
Previously the Java implementation of `RocksDB#addFile` was both incomplete and not inline with the C++ API.

Rather than fix it, as I see that `rocksdb::DB::AddFile` is now deprecated in favour of `rocksdb::DB::IngestExternalFile`, I have removed the old broken implementation and implemented `RocksDB#ingestExternalFile`.

Closes https://github.com/facebook/rocksdb/issues/2261

### CODE REVIEW

**Comment by sagar0** [comment]
I am not sure if there are any users of `addFileWithFilePath` and `addFileWithFileInfo` Java APIs, but, if there are such users their code will be broken with this change. 
However, I do agree that we should move over to `ingestExternalFile`  if `addFile*` is incomplete to start with.

**Comment by sagar0** [comment]
@adamretter Seems like the Java builds in Travis are failing in this as well as other PRs with: 
`clang: error: no such file or directory: 'util/build_version.cc'`, though not related to this PR. 

I will wait for the appveyor builds to start passing again before merging this.

**Comment by adamretter** [comment]
@sagar0 Yeah, I looked into Travis and saw the build failures for the file `util/build_version.cc` in RocksJava. Unfortunately the Makefile and the Travis config have become complicated to a state where I can't figure out why this fails for RocksJava and not for Rocks itself.

It seems that `util/build_version.cc` is not generated by the Makefile for when make is called with the targets `clean jclean rocksdbjava` but I can't see why?!?

**Comment by mikhail-antonov** [comment]
Looks good to me.

**Comment by sagar0** [comment]
@adamretter Could you please rebase and push again?
The corresponding appveyor build failed due to an unrelated reason (blob_db_test): https://ci.appveyor.com/project/Facebook/rocksdb/build/1.0.4382 , but now that the windows builds are fixed, I want to make sure that this PR passes the appveyor build before merging.

**Comment by adamretter** [comment]
@sagar0 Yup, done :-)

**Comment by sagar0** [comment]
Sorry for asking again, but possible to do another rebase? I just fixed the appveyor/windows build, and we can't have it broken again.

**Comment by adamretter** [comment]
@sagar0 Yup. Done

**Comment by sagar0** [comment]
The java builds on travis failed. Can you take a look? 
```
error: no such file or directory: 'java/rocksjni/ingest_external_file_options.cc'
```

**Comment by adamretter** [comment]
@sagar0 Oops! Okay I have added that now

**Pull request closed without merging**
