### PR TITLE
db_stress begin tracking expected state after verification

### PR DESCRIPTION
**Pull request by ajkr**
Previously we enabled tracking expected state changes during
`FinishInitDb()`, as soon as the DB was opened. This meant tracing was
enabled during the `VerifyDb()` in the setup phase (pre-`OperateDb()`). This cost extra CPU by requiring
`DBImpl::trace_mutex_` to be acquired on each read operation. It was
unnecessary since we know there are no expected state changes during the
setup phase. So, this PR delays tracking expected state changes
until the end of the setup phase.

Test Plan:

Measured this PR reduced the `VerifyDb()` time in the setup phase 76% (387 -> 92 seconds) with
`-disable_wal=1` (i.e., expected state tracking enabled).

- benchmark command: `./db_stress -max_key=100000000 -ops_per_thread=1 -destroy_db_initially=1 -expected_values_dir=/dev/shm/dbstress_expected/ -db=/dev/shm/dbstress/ --clear_column_family_one_in=0 --disable_wal=1 --reopen=0`
- without this PR, `VerifyDb()` in the setup phase takes 387 seconds:

```
2022/01/30-21:43:04  Initializing worker threads
Crash-recovery verification passed :)
2022/01/30-21:49:31  Starting database operations
```

- with this PR, `VerifyDb()` in the setup phase takes 92 seconds

```
2022/01/30-21:59:06  Initializing worker threads
Crash-recovery verification passed :)
2022/01/30-22:00:38  Starting database operations
```

### CODE REVIEW

**Comment by riversand963** [comment]
There is an option `verify_db_one_in` which allows the worker threads to perform verification while still executing `OperateDb()`. Should this be checked?

**Comment by ajkr** [comment]
Sorry let me update the description. I only meant to make the `VerifyDb()` in the setup phase faster as that one frequently takes longer than the whole crash interval (two minutes in our CI), causing entire `db_stress` runs to not mutate the DB at all.

**Review by riversand963 — APPROVED** [review]
LGTM

**Comment by ajkr** [comment]
Thanks for the review!

**Pull request closed without merging**
