### PR TITLE
[CI] Point bzip2 download address to http://sourceware.org/pub/bzip2

### PR DESCRIPTION
**Pull request by riversand963**
Download bzip2 from `https://sourceware.org/pub/bzip2` to `http://sourceware.org/pub/bzip2`
to resolve curl's ca verification error.

### CODE REVIEW

**Review by akankshamahajan15 — APPROVED** [review]
Thanks for the fix!

**Comment by riversand963** [comment]
Thanks @akankshamahajan15 for the review, but let me see if we can fix the issue without adding `--insecure`.

**Comment by jay-zhuang** [comment]
should we change it to https
https://github.com/facebook/rocksdb/blob/bda8d93ba95f34aa91ae8578fe7d3454f3324f6a/Makefile#L2034

**Comment by riversand963** [comment]
> ~should we change it to https~
> 
> https://github.com/facebook/rocksdb/blob/bda8d93ba95f34aa91ae8578fe7d3454f3324f6a/Makefile#L2034
> 
> never mind, if it's also impacting `BZIP2_DOWNLOAD_BASE`, then it's not https problem.

I tweaked the BZIP2_DOWNLOAD_BASE similarly, and it works. Thanks for the suggestion.

**Pull request closed without merging**
