### PR TITLE
Fixes for build_detect_platform

### PR DESCRIPTION
**Pull request by azat**

### CODE REVIEW

**Comment by azat** [comment]
@riversand963 yeah I also prefer `-Werror`, but not for code snippets for various compile checks (like you had for SSE).

So do you prefer to remove unused variable instead?

- before
```c
  #include <cstdint>
  #include <nmmintrin.h>
  int main() {
    volatile uint32_t x = _mm_crc32_u32(0, 0);
  }
```

- after
```c
  #include <cstdint>
  #include <nmmintrin.h>
  int main() {
    _mm_crc32_u32(0, 0);
  }
```

P.S. I preferred `-Wno-error`, because it is pretty easy to mess up (and not only during converting existing checks, but also for newly added), and there is no good error reporting passed from this script to the `make`.

**Comment by azat** [comment]
And for the history (and search engines), here is how I came up to this:

```
$ CFLAGS=-Werror USE_SSE=1 make -j8 release
  GEN      util/build_version.cc
make clean
make[1]: Entering directory '/work3/bl-jenkins/rocksdb'
rm -f db_bench table_reader_bench cache_bench memtablerep_bench persistent_cache_bench range_del_aggregator_bench sst_dump db_sanity_test db_stress write_stress ldb db_repl_stress rocksdb_dump rocksdb_undump blob_dump trace_analyzer  db_basic_test db_encryption_test db_test2 external_sst_file_basic_test auto_roll_logger_test bloom_test dynamic_bloom_test c_test
checkpoint_test crc32c_test coding_test inlineskiplist_test env_basic_test env_test hash_test thread_local_test rate_limiter_test perf_context_test iostats_context_test db_wal_test db_block_cache_test db_test db_blob_index_test db_bloom_filter_test db_iter_test db_iter_stress_test db_log_iter_test db_compaction_filter_test db_compaction_test db_dynamic_level_test db_flush_test db_inplace_update_test db_iterator_test db_memtable_test db_merge_operator_test db_options_test db_range_del_test db_secondary_test db_sst_test db_tailing_iter_test db_io_failure_test db_properties_test db_table_properties_test db_statistics_test db_write_test error_handler_test autovector_test blob_db_test cleanable_test column_family_test table_properties_collector_test arena_test block_test data_block_hash_index_test cache_test corruption_test slice_transform_test dbformat_test fault_injection_test filelock_test filename_test file_reader_writer_test block_based_filter_block_test full_filter_block_test partitioned_filter_block_test hash_table_test histogram_test log_test manual_compaction_test mock_env_test memtable_list_test merge_helper_test memory_test merge_test merger_test util_merge_operators_test options_file_test reduce_levels_test plain_table_db_test comparator_db_test external_sst_file_test prefix_test skiplist_test write_buffer_manager_test stringappend_test cassandra_format_test cassandra_functional_test cassandra_row_merge_test cassandra_serialize_test ttl_test backupable_db_test sim_cache_test version_edit_test version_set_test compaction_picker_test version_builder_test file_indexer_test write_batch_test write_batch_with_index_test write_controller_test deletefile_test obsolete_files_test table_test delete_scheduler_test options_test options_settable_test options_util_test event_logger_test timer_queue_test cuckoo_table_builder_test cuckoo_table_reader_test cuckoo_table_db_test flush_job_test wal_manager_test listener_test compaction_iterator_test compaction_job_test thread_list_test sst_dump_test compact_files_test optimistic_transaction_test write_callback_test heap_test compact_on_deletion_collector_test compaction_job_stats_test option_change_migration_test transaction_test ldb_cmd_test persistent_cache_test statistics_test lru_cache_test object_registry_test repair_test env_timed_test write_prepared_transaction_test write_unprepared_transaction_test db_universal_compaction_test trace_analyzer_test repeatable_thread_test range_tombstone_fragmenter_test range_del_aggregator_test sst_file_reader_test db_secondary_test  librocksdb.a
rm -rf  make_config.mk t LOG /dev/shm/rocksdb.h5QO unity.cc jls jl ios-x86 ios-arm scan_build_report
. -name "*.[oda]" -exec rm -f {} \;
/bin/bash: line 0: .: -n: invalid option
.: usage: . filename [arguments]
make[1]: *** [Makefile:1053: clean] Error 2
make[1]: Leaving directory '/work3/bl-jenkins/rocksdb'
make: *** [Makefile:713: release] Error 2
```

**Comment by riversand963** [comment]
> @riversand963 yeah I also prefer `-Werror`, but not for code snippets for various compile checks (like you had for SSE).
> 
> So do you prefer to remove unused variable instead?
> 
> * before
> 
> ```c
>   #include <cstdint>
>   #include <nmmintrin.h>
>   int main() {
>     volatile uint32_t x = _mm_crc32_u32(0, 0);
>   }
> ```
> 
> * after
> 
> ```c
>   #include <cstdint>
>   #include <nmmintrin.h>
>   int main() {
>     _mm_crc32_u32(0, 0);
>   }
> ```
> 
> P.S. I preferred `-Wno-error`, because it is pretty easy to mess up (and not only during converting existing checks, but also for newly added), and there is no good error reporting passed from this script to the `make`.

Yeah, I think we should fix these sample code snippets. For example maybe add `(void) x` in the main function.

**Comment by azat** [comment]
>I think we should fix these sample code snippets

So you definitely sure that nobody will write snippets with unused variables in future? (or/and it will be caught during review) If so I can updated those checks instead of course.

**Comment by riversand963** [comment]
> > I think we should fix these sample code snippets
> 
> So you definitely sure that nobody will write snippets with unused variables in future? (or/and it will be caught during review) If so I can updated those checks instead of course.

We will do our best to make sure we catch these warnings during review, e.g. unused variable, but naked eye is not always able to catch all these things. That's why we need the compiler `-Werror` to help us.

**Comment by azat** [comment]
@riversand963 updated

**Pull request closed without merging**
