### PR TITLE
Async Get() experimental

### PR DESCRIPTION
**Pull request by yuslepukhin**
This is an informational PR seeking input for an async
mode implementation of Get(). It is trivial to implement MultiGet()
which is what reworked db_bench essentially is doing.

RangeQuery code was not addressed at this time as it might
involve building async iteration which I plan to address shortly.

The main gist of the PR is to show positive dynamics in throughput
while keeping the number of threads to a minimum, possibly close
to the number of the cores on the machine. This is usually
achieved at the expense of an individual request latency (<5%) while
running in async mode only but increasing the overall X number of times and
allow to fully utilize the media bandwidth.

Attached results are ad-hoc testing and should not be interpreted
literally but demonstrate positive trend given HDD example. Results for
SSD are very similar.

This is achieved by making use  one of the well known async patterns.
To achieve that we use generic Callable<> class to build ad-hoc a necessary
chain of callbacks between the pariticipating dynamically allocated
contexts.

On the OS level Windows makes use kernel implemented Vista threadpool
with I/O completion functionality. As the async read completes the threadpool
invokes a supplied callback whcih resumes request processing where it was left off.

Other OS utilize similar facilities as long as they invoke a callback such as epoll,
aio_*() and other suitable facilities.

It is possible to implement a lock-free threadpool for more efficiency.

The nice property of the code is that is can run both sync and async.
Indeed, there is not another way since rocksdb can complete many
requests sync.

Thus we can switch the running mode simply by switching an option.
This also allows to re-use the same unit tests and obtain the same
coverage. There is very little of generic code that is purely async
specific. I have added a few unit tests that address specifically async mode
of operation. db_bench seems to be the most indicative of that.

### CODE REVIEW

**Comment by yuslepukhin** [comment]
Per results.
[Async.txt](https://github.com/facebook/rocksdb/files/1219372/Async.txt)

**Comment by yuslepukhin** [comment]
Ping...

**Comment by siying** [comment]
Wow, this is crazy. Thank you for running this experiment. I can see this is enormous code change. I personally like it, but I need to discuss with my team and see whether they are comfortable with the way to go.

**Comment by yuslepukhin** [comment]
@siying Thank you for taking a look at the code. The changes are confined to db and table folders with _request.[h|cc] files are of interest. Other changes include:

- Some code moves within the BlockBased table reader to make it accessible to request contexts
- some async operations continue to be sync notably loading tables at the end of compactions.  Compactions continue to be sync.

I am in the process of implementing RangeQuery async along with the iterators. There is a great interest here at MS to use it in real production and for that reason we greatly appreciate your feedback. I'd be happy yo answer any of the questions or address issues. I plan to be at the meetup at SF.

**Comment by PraveenSinghRao** [comment]
@siying - it would also be great if perf can be run on Linux on this fork (esp. to confirm that sync perf is not adversely affected). Would that be possible on your end?

My understanding is that on Windows we don't see sync latency being adversely affected.

**Comment by siying** [comment]
@PraveenSinghRao we can run benchmark on Linux and see whether the performance regress against without the PR.

**Comment by siying** [comment]
@PraveenSinghRao I have it compiled on my dev host (with some code changes and disable warning-as-error) and ran a normal readrandom benchmark against a DB on ramfs using 32 reader threads, I'm seeing 20% regression of QPS. I don't know what's the problem.

**Comment by yuslepukhin** [comment]
@siying Please, share with us the bench and its params. I have not ran it against RAMFS but eager to try.

**Comment by siying** [comment]
@yuslepukhin @PraveenSinghRao we had an internal discussion about the pull request. We need more time studying the code and see whether the complexity is worthy, and will get back to you. 

@yuslepukhin here is how I run the benchmarks: I first populate the LSM-tree with 10000000 keys. I did some tricks I like to play:
```
TEST_TMPDIR=/dev/shm/ ./db_bench --benchmarks=fillseq --num=10000000
TEST_TMPDIR=/dev/shm/ ./db_bench --benchmarks=overwrite,stats --duration=10 --num=10000000  --use_existing_db
```
and then
```
TEST_TMPDIR=/dev/shm/ ./db_bench --benchmarks=overwrite,stats --duration=10 --num=10000000 --benchmark_write_rate_limit=2000000 --use_existing_db
```
Several times. And the eventual LSM-tree structure looks like this:
```
** Compaction Stats [default] **
Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
----------------------------------------------------------------------------------------------------------------------------------------------------------
  L0      3/0   25.07 MB   0.8      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0
  L1      4/0   221.11 MB   0.9      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0
  L2     11/0   492.22 MB   0.2      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0
 Sum     18/0   738.40 MB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0
 Int      0/0    0.00 KB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0
```
(You probably can generate similar tree structure by --benchmarks=fillrandom with --benchmark_write_rate_limit=2000000 but it will just take longer.

And then I simply run:
```
TEST_TMPDIR=/dev/shm/ ./db_bench --benchmarks=readrandom --threads=32 --num=10000000 --use_existing_db --duration=30
```
and see the results.

**Comment by yuslepukhin** [comment]
@siying Thanks for the numbers. The 20% degradation is as compared with 5.4? I noticed that 5.6 is actually better in our numbers.

**Comment by siying** [comment]
@yuslepukhin forgot to answer the question. No, the regression was measured comparing to the commit in your pull request, which is b06bffc1cd67a7f776cdb1a94d6289ad9495a12e.

In my simple CPU perfiling, the first thing I noticed and puzzled me was, why rocksdb::async::DBImplGetContext::Get() wasn't inlined into rocksdb::DBImpl::Get()? Similarly, why rocksdb::async::BlockBasedGetContext::Get() wasn't inlined in BlockBasedTable::Get(). Is there any language syntax reason that prevents the compiler from doing that?

```
       │    Status DBImpl::Get(const ReadOptions& read_options,                                                                                                                                                ▒
       │                       ColumnFamilyHandle* column_family, const Slice& key,                                                                                                                            ▒
       │                       PinnableSlice* value) {                                                                                                                                                         ▒
  9.09 │      push   %rbp                                                                                                                                                                                      ▒
       │      mov    %rsp,%rbp                                                                                                                                                                                 ▒
       │      push   %rbx                                                                                                                                                                                      ▒
       │      mov    %rdi,%rbx                                                                                                                                                                                 ▒
       │      sub    $0x18,%rsp                                                                                                                                                                                ▒
  9.09 │      mov    %fs:0x28,%rax                                                                                                                                                                             ▒
       │      mov    %rax,-0x18(%rbp)                                                                                                                                                                          ▒
       │      xor    %eax,%eax                                                                                                                                                                                 ▒
       │      return async::DBImplGetContext::Get(this, read_options, column_family,                                                                                                                           ▒
       │        key, value, nullptr);                                                                                                                                                                          ▒
       │      pushq  $0x0                                                                                                                                                                                      ▒
       │      pushq  $0x0                                                                                                                                                                                      ▒
       │    → callq  rocksdb::async::DBImplGetContext::Get(rocksdb::DB*, rocksdb::ReadOptions const&, rocksdb::ColumnFamilyHandle*, rocksdb::Slice const&, rocksdb::PinnableSlice*, std::__cxx11::basic_string<▒
 45.45 │      pop    %rax                                                                                                                                                                                      ▒
       │    }                                                                                                                                                                                                  ▒
  9.09 │      mov    -0x18(%rbp),%rdi                                                                                                                                                                          ▒
  9.09 │      xor    %fs:0x28,%rdi                                                                                                                                                                             ▒
       │                                                                                                                                                                                                       ▒
       │    Status DBImpl::Get(const ReadOptions& read_options,                                                                                                                                                ▒
       │                       ColumnFamilyHandle* column_family, const Slice& key,                                                                                                                            ▒
       │                       PinnableSlice* value) {                                                                                                                                                         ▒
       │      return async::DBImplGetContext::Get(this, read_options, column_family,                                                                                                                           ◆
       │        key, value, nullptr);                                                                                                                                                                          ▒
       │      pop    %rdx                                                                                                                                                                                      ▒
       │    }                                                                                                                                                                                                  ▒
       │    ↓ jne    3e                                                                                                                                                                                        ▒
       │      mov    %rbx,%rax                                                                                                                                                                                 ▒
       │      mov    -0x8(%rbp),%rbx                                                                                                                                                                           ▒
       │      leaveq                                                                                                                                                                                           ▒
 18.18 │    ← retq                                               
```
and
```
       │    Status BlockBasedTable::Get(const ReadOptions& read_options, const Slice& key,                                                                                                                     ▒
       │                                GetContext* get_context, bool skip_filters) {                                                                                                                          ▒
       │      mov    %rsp,%rbp                                                                                                                                                                                 ▒
  6.25 │      push   %rbx                                                                                                                                                                                      ▒
 12.50 │      mov    %rdi,%rbx                                                                                                                                                                                 ▒
       │      sub    $0x18,%rsp                                                                                                                                                                                ▒
       │      mov    %fs:0x28,%rax                                                                                                                                                                             ▒
 12.50 │      mov    %rax,-0x18(%rbp)                                                                                                                                                                          ▒
       │      xor    %eax,%eax                                                                                                                                                                                 ▒
       │                                                                                                                                                                                                       ▒
       │      return async::BlockBasedGetContext::Get(this, read_options, key, get_context,                                                                                                                    ▒
       │                                              skip_filters);                                                                                                                                           ▒
       │    → callq  rocksdb::async::BlockBasedGetContext::Get(rocksdb::BlockBasedTable*, rocksdb::ReadOptions const&, rocksdb::Slice const&, rocksdb::GetContext*, bool)                                      ▒
       │    }                                                                                                                                                                                                  ▒
 18.75 │      mov    -0x18(%rbp),%rdi                                                                                                                                                                          ▒
       │      xor    %fs:0x28,%rdi                                                                                                                                                                             ▒
 18.75 │   ┌──jne    3d                                                                                                                                                                                        ▒
       │   │  add    $0x18,%rsp                                                                                                                                                                                ▒
  6.25 │   │  mov    %rbx,%rax                                                                                                                                                                                 ▒
  6.25 │   │  pop    %rbx                                                                                                                                                                                      ▒
       │   │  pop    %rbp                                                                                                                                                                                      ▒
       │   │← retq                                                                                            
```

**Pull request closed without merging**
