### PR TITLE
Avoid empty ranges vector with subsequent zero element access

### PR DESCRIPTION
**Pull request by yuslepukhin**

### CODE REVIEW

**Comment by yuslepukhin** [comment]
@siying @igorcanadi This test failure is not related to this PR since the changes are test only

**Comment by yuslepukhin** [comment]
@siying @igorcanadi btw, that test also fails on Windows

**Comment by siying** [comment]
@yuslepukhin we know the build is not stable now. We are currently freezing the branch and actively working on fixing it.

**Comment by IslamAbdelRahman** [comment]
@siying this is actually fixing a test so we should merge it

**Pull request merged**
