### PR TITLE
Fix copy constructors of Options and ColumnFamilyOptions

### PR DESCRIPTION
**Pull request by dfa1**
Looks like some fields are not copied by the copy constructor. 

Please confirm if it is a real issue!

### CODE REVIEW

**Comment by dfa1** [comment]
@pdillinger  @zhichao-cao hello :) another small fix... can you please review it?

**Review by adamretter — APPROVED** [review]
LGTM

**Comment by darionyaphet** [comment]
nice sight 👍

**Comment by adamretter** [comment]
@jay-zhuang @mrambacher Can you merge this one please?

**Pull request closed without merging**
