### PR TITLE
CI: add Arm support to travis CI matrix

### PR DESCRIPTION
**Pull request by guyuqi**
This patch based on #5932 offers a better solution to add arm64 to TravisCI matrix.
Really thank @adamretter for initiating Arm CI setup.

Difference comparing to amd64:
1. For CMake, as no official arm64 release ready on Kitware page,
a third party (conda-forge) released one is used instead of
building from source. The main reason is to save CI time.
2. Explicit export JAVA_HOME on arm64
3. Disable mingw test

Signed-off-by: Yuqi Gu <yuqi.gu@arm.com>

### CODE REVIEW

**Comment by guyuqi** [comment]
In order to make Arm64 CI work properly, PR #6437 also needs to be merged , thanks!

**Comment by adamretter** [comment]
@guyuqi so this does not require to install Java 8? Which version of Java does it use?

**Comment by JunHe77** [comment]
Hi, @adamretter , from TravisCI outputs, it has JDK-11 pre-installed:
`openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)`

**Comment by adamretter** [comment]
@JunHe77 I would prefer to stick with Java 8.

**Comment by JunHe77** [comment]
@adamretter I'm fine to use either Java8 or Java11. But to align with x86 tests it would be good to use same Java version on Arm64. For x86 test Travis uses JDK11 preinstalled. A reference log is [here](https://travis-ci.org/JunHe77/redis/jobs/653739141#L216).

**Comment by adamretter** [comment]
@JunHe77 that link for the reference log is from building Redis not RocksDB.

**Comment by JunHe77** [comment]
Ya, different repos, but same Travis runtime.
So I created a test PR to RocksDB and you can find the same Java info on x86 [here](https://travis-ci.org/facebook/rocksdb/jobs/654448943#L318):
`
openjdk version "11.0.2" 2019-01-15
320
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
321
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)`

**Comment by adamretter** [comment]
@JunHe77 Okay, but my point was that RocksDB's Java code is designed for compatibility with Java 7. The x64 testing of RocksDB happens against Java 7, the ARM64 testing therefore should also happen against Java 7.

Unfortunately, I could not find Java 7 for ARM64, so the next best option IMHO is Java 8.

**Comment by JunHe77** [comment]
Yes, Arm64 support in JDK starts from Java8.
I'm not sure if current Java11 used in Travis CI is what RocksDB intends to use (Java7 is pretty out-of-date). But if target version is Java8, then the .travis.yml needs to updated.
Maybe someone from RocksDB can help on clarify this?

**Comment by adamretter** [comment]
@JunHe77 Oh blast! I see that the RocksDB Travis CI is now using Java 11 for x64 as well - https://travis-ci.org/facebook/rocksdb/jobs/653848197

It was and still should be Java 7 AFAIK.  We actually specify in our [`.travis.yml`](https://github.com/facebook/rocksdb/blob/master/.travis.yml#L11):

```
jdk:
  - openjdk7
```

So I am not sure why Travis is ignoring that and using Java 11.

**Comment by guyuqi** [comment]
@siying  Could you please help to loop some guys in this PR and have a look into it?
Maybe someone from RocksDB can help on clarify it.

**Comment by adamretter** [comment]
@guyuqi I'm response for RocksJava so I can look into that

**Comment by JunHe77** [comment]
@adamretter 
> It was and still should be Java 7 AFAIK. We actually specify in our [`.travis.yml`](https://github.com/facebook/rocksdb/blob/master/.travis.yml#L11):
> 
> ```
> jdk:
>   - openjdk7
> ```
From what Travis guy's [reply](https://travis-ci.community/t/oracle-jdk-11-and-10-are-pre-installed-not-the-openjdk-builds/785/14):
>For jdk: to be read, you’ll need to specify language: java.

So it seems extra commands need to add to .travis.yml if Java8 should be used.

**Comment by guyuqi** [comment]
@adamretter 

> @guyuqi I'm responsible for RocksJava so I can look into that

@adamretter That‘s great and look forward to your conclusion.

**Comment by guyuqi** [comment]
@adamretter  Add JDK8 installation in the new commit.

**Comment by pdillinger** [comment]
@Little-Wallace Any advice on DBCompactionTestWithParam::FlushAfterIntraL0CompactionCheckConsistencyFail failing? (Re: #6061)

**Comment by pdillinger** [comment]
> @Little-Wallace Any advice on DBCompactionTestWithParam::FlushAfterIntraL0CompactionCheckConsistencyFail failing? (Re: #6061)

That was in TEST_GROUP=2. Last failure was something in TEST_GROUP=3 (which Travis seems to have cleared from my web browser tab, and from history, with the log open when I restarted the build in another tab 😡)

**Comment by pdillinger** [comment]
> Last failure was something in TEST_GROUP=3 (which Travis seems to have cleared from my web browser tab, and from history, with the log open when I restarted the build in another tab 😡)

I think same failure again: ExternalSSTFileTest.MultiThreaded...
external_sst_file_test: db/column_family.cc:1387: rocksdb::ColumnFamilySet::~ColumnFamilySet(): Assertion `last_ref' failed.

**Comment by adamretter** [comment]
@guyuqi after https://github.com/facebook/rocksdb/pull/6512 is merged, you might want to rebase. I took your code for enforcing JDK8, but modified the Travis YAML file so that it was also compatible with macOS.

**Comment by pdillinger** [comment]
> > Last failure was something in TEST_GROUP=3 (which Travis seems to have cleared from my web browser tab, and from history, with the log open when I restarted the build in another tab 😡)
> 
> I think same failure again: ExternalSSTFileTest.MultiThreaded...
> external_sst_file_test: db/column_family.cc:1387: rocksdb::ColumnFamilySet::~ColumnFamilySet(): Assertion `last_ref' failed.

I haven't been able to reproduce this using the same OS and compiler version in Amazon EC2. ☹️

**Comment by adamretter** [comment]
@pdillinger Seems that all tests are now passing on Travis ARM64 too :-)

**Pull request closed without merging**
